### ISSUE TITLE
Possibility to maintain the content in account deletion

### ISSUE THREAD

**Issue by EchedeyLR** [LemmyNet/lemmy#1654] opened 2021-07-09 14:40 UTC
### Is your proposal related to a problem?

I would like a possibility in which, at the deletion of an account, it is possible to maintain the comments and posts without being deleted.

### Describe the solution you'd like

GitHub and Disqus move or can move posts to a “Guest”/“Ghost” account.

So the content can be conserved at user desires.

### Describe alternatives you've considered

None.

I can just add that when I made a little comment system imitating Disqus I implemented this in the own SQL script to create the database.

I just created a default account called "Guest" and added a trigger before-deletion in the table of users to change the owner of their comments to the "Guest" account before deletion.

However, in this case, the content was maintained every time, not just at user election.

### Additional context

None.

**Comment by dessalines** [comment] 2021-07-09 15:23
Dupe of #1617

**Closed by dessalines** 2021-07-09 15:23 UTC
Labels: enhancement

**Comment by Nutomic** [comment] 2021-07-09 15:33
I would say the issue itself is different, even though a comment over there mentions the possibility of moving comments to a guest account.

**Comment by EchedeyLR** [comment] 2021-07-09 15:43
@Nutomic, I think @dessalines is right. The other issue is related with what I expected but I could not see it because the name is not accurate.
