### ISSUE TITLE
Implement a mastodon-style blocking mechanism

### ISSUE THREAD

**Issue by harcesz** [LemmyNet/lemmy#1831] opened 2021-10-12 12:20 UTC
Mastodon has a well developed and effective logic of blocking users (https://docs.joinmastodon.org/user/moderating/#blocking-and-muting), adapting it for lemmy might make a growing lemmyverse a better and safer space.

**Comment by dessalines** [comment] 2021-10-12 16:42
Dupe of #1832

**Closed by dessalines** 2021-10-12 16:42 UTC
Labels: enhancement, moderation
