### ISSUE TITLE
Sign in with... Provider

### ISSUE THREAD

**Issue by fLgI6FeL02hKr2g4qBj0hEfN4VvA6TpN** [LemmyNet/lemmy#3682] opened 2023-07-21 05:42 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

It currently requires user and password to register. Change it so people can also use providers. (Ex. Sign in with MetaMask, Google, Discord, etc) 

### Describe the solution you'd like.

Allow people to write providers for signing into accounts.

### Describe alternatives you've considered.

It is not necessary for me to write more. 

### Additional context

#3416 is related. 

I personally want this change so I can use blockchain based identitiy systems with instances.

**Comment by lionirdeadman** [comment] 2023-07-21 06:50
Duplicate of #489

**Closed by lionirdeadman** 2023-07-21 06:50 UTC
Labels: type: duplicate, enhancement
