### ISSUE TITLE
How to merge communities? Basically, I want to delete unused communities but move their posts to another community.

### ISSUE THREAD

**Issue by Bakcodi** [LemmyNet/lemmy#2809] opened 2023-04-15 08:12 UTC
Is there any technique to do this? During the initial days lot of communities were made, but now only handful are being used, and the rest has become a clutter. This is discouraging users from selecting the community while making a post, instead they would rather post it to the General community. Is there a way to remove those communities, but not delete its posts?

Maybe a direct database fix with some query?

**Comment by Nutomic** [comment] 2023-04-15 13:15
You could do it in the database by changing the `community_id` of these posts. However this might not play well with federation.

**Comment by dessalines** [comment] 2023-04-15 13:50
Queries are in #1445

**Comment by malcyon** [comment] 2023-05-08 06:37
Being able to move threads to another forum is a commonly implemented feature in software like vBulletin and phpbb. It helps keep conversation spaces focused on a particular thing. For example, if one particular sub-topic keeps repeatedly coming up, a new community can be spun up, and all new threads for that sub-topic can be moved to the new community. It's much better to have a thread be moved that just have it be deleted or locked. Just my opinion on the potential usefulness of this.

**Comment by Nutomic** [comment] 2023-05-10 19:26
I think this would be a useful feature, so lets keep this open. However its not on our roadmap, contributions are welcome!

**Comment by Nutomic** [comment] 2023-05-10 19:27
On second thought, this is kind of a duplicate of https://github.com/LemmyNet/lemmy/issues/2345. Once that is implemented, multiple posts could be moved with an api client.

**Closed** 2023-05-10 19:26 UTC
Labels: question
