### ISSUE TITLE
WebSocketService.Instance.site is undefined

### ISSUE THREAD

**Issue by lichao-eric** [LemmyNet/lemmy#894] opened 2020-07-03 04:08 UTC
Hello,when i refresh the page, Browser console print error message

```Cannot read property 'enable_downvotes' of undefined'``` , 

the reason is ```WebSocketService.Instance.site``` is undefined
![image](https://user-images.githubusercontent.com/25276032/86430446-e368f400-bd24-11ea-8c7b-034d32caf1da.png)
Can you check the reason for me, thank you

**Comment by dessalines** [comment] 2020-07-03 17:14
This happens on some routes, its an open issue. Dupe of #801

**Closed by dessalines** 2020-07-03 17:14 UTC
