### ISSUE TITLE
Automatically make an Announcements community

### ISSUE THREAD

**Issue by DShiller** [LemmyNet/lemmy#2440] opened 2022-09-13 17:50 UTC
Sometimes you want to make announcements that are important to the whole instance you own, for example when you change instance rules or update the software or whatever.

My idea is that when you install Lemmy, a community is automatically created called c/announcements.

The first thing about this community is when something is posted to it, it gets boosted up to the top of the front page and posts appear differently, like in red or bold so that everyone can see them. If pinned, posts will also appear at the top of the instance and not just at the top of the community.

Only instance admins can post to this community.

For implementation, the community is either created at installation, or when an admin creates a community they can check a box "use this community for announcements". Then they could give it a more custom name than just announcements.

**Comment by Nutomic** [comment] 2022-09-13 20:43
Here is another feature proposal which would solve the same issue: https://github.com/LemmyNet/lemmy/issues/2067

**Comment by dessalines** [comment] 2022-09-13 21:27
> My idea is that when you install Lemmy, a community is automatically created called c/announcements.

We used to have this until very recently, a subscribed default community that everyone is automatically subscribed to. Now since the default preferred view is `Local`, we've removed that.

@Nutomic is correct, this is a dupe of that issue.

**Closed by dessalines** 2022-09-13 21:27 UTC
Labels: enhancement
