### ISSUE TITLE
[Feature request] Upvoted, and Downvoted sections in user’s profile

### ISSUE THREAD

**Issue by marek-lach** [LemmyNet/lemmy#1653] opened 2021-07-08 14:02 UTC
Would make it possible to display/view, what posts a particular user has upvoted, or downvoted.

You can also think of it as a sort of bookmarking option of interesting posts for an user.

**Comment by dessalines** [comment] 2021-07-09 01:16
Dupe of #1634

**Comment by dessalines** [comment] 2021-07-09 01:17
You can also currently use star to favorite posts.

**Closed by dessalines** 2021-07-09 01:16 UTC
Labels: enhancement
