### ISSUE TITLE
Show deleted posts for your user, hide them from others.

### ISSUE THREAD

**Issue by ghost** [LemmyNet/lemmy#2624] opened 2022-12-16 13:36 UTC
There was a post I didn't want to keep public and deleted it, but then I wanted to see it again and couldn't. It would be nice to have a feature to hide or make our posts private, and a filter to see only those posts. Or otherwise be able to filter deleted posts which are already implemented.

**Comment by Nutomic** [comment] 2023-01-16 22:09
I think this is out of scope, if you delete it then its gone.

**Comment by JediMaster25** [comment] 2023-02-06 09:57
Except [posts deleted by creators aren't really deleted, they are just hidden](https://github.com/LemmyNet/lemmy/issues/2410).

**Comment by dessalines** [comment] 2023-02-06 18:30
> Except https://github.com/LemmyNet/lemmy/issues/2410. Either change the trash icon for a hide button and allow users to find their hidden posts or actually delete the posts from the database. Don't make users believe the content has been deleted when it hasn't and hide the post so they can't find it.

That's correct behavior, posts deleted by creators should not be doing any database deletes, as that could wipe out a lot of **other people's data.**

The correct way privacy-wise, is to delete your account through your profile settings, which overwrites all your content to remove any info.

> Basically, I would like to have the ability to filter my hidden posts so I can easily access them if I need to.

So after you delete a post, you want it to show up on your profile posts?

**Comment by JediMaster25** [comment] 2023-02-06 19:34
> So after you delete a post, you want it to show up on your profile posts?
If the post is hidden it should be for everyone else, not for me. So yes, I think this is the expected behavior. I guess I should do a different issue since this wasn't originally about that.

**Comment by dessalines** [comment] 2023-02-10 18:28
No problem, I'll just rename and re-open this one.

**Comment by dessalines** [comment] 2023-03-30 15:07
As stated in the other issue, my fix doesn't always work correctly, and needs to be fixed.

**Closed** 2023-07-20 14:36 UTC
Labels: enhancement, ux
