### ISSUE TITLE
Does indexing work?

### ISSUE THREAD

**Issue by 47773838382882828** [LemmyNet/lemmy#725] opened 2020-05-17 01:48 UTC
Since Lemmy is a web app not a single page website, googlebot and other similar bots won't be able to crawl the website.

Archiving through the internet archive also dosent work.

Any possible workarounds?

**Comment by dessalines** [comment] 2020-05-17 01:49
Dupe of #347

**Comment by dessalines** [comment] 2020-05-17 01:50
Errr #226

**Closed by dessalines** 2020-05-17 01:49 UTC
