### ISSUE TITLE
[Bug]: Images and videos don't federate to outside Lemmy reliably

### ISSUE THREAD

**Issue by JupiterRowland** [LemmyNet/lemmy#3644] opened 2023-07-17 17:59 UTC
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Images and videos embedded in Lemmy posts are often missing when these posts are federated to another Fediverse platform.

I'm a Hubzilla user. I've subscribed to several Lemmy communities on Hubzilla. And whenever there is supposed to be a picture or a video in a post, I can't see it in the post.

I've started [this thread](url=https://lemmy.world/post/1617295) [on Hubzilla](https://hub.netzgemeinde.eu/item/44e7aeee-8d08-4b7e-a28e-55f55ebe6216) to find out which other Fediverse projects are affected to which degrees. I'm still waiting for more replies, but from what I can see, this problem applies to Mastodon and Friendica as well and to /kbin only occasionally.

This is why I suspect it to be a Lemmy issue rather than one on the other side: It's an issue for vastly different projects. Mastodon doesn't have any code in common with Friendica and Hubzilla; it's based on entirely different technology. And while Hubzilla is a "fork of a fork" of Friendica, its backend has been mostly re-written and based on yet another protocol, so the two don't have much code in common anymore either. Also, they handle images differently. Friendica and Hubzilla support embedding images in posts wherever you want them; Mastodon always converts them to file attachments and attaches them below the post.

### Steps to Reproduce

1. Have one account on Lemmy + one account on Mastodon/one account on Friendica/one channel on Hubzilla or the like.
2. Subscribe to the same Lemmy community with both.
3. Submit a post to the Lemmy community from your Lemmy account with an image or a video in it.
4. Wait for your Mastodon account/Friendica account/Hubzilla channel/... to receive the post.
5. Look at the post.

**Expected result**
The image/the video is visible on Mastodon/Friendica/Hubzilla/... just like on Lemmy.

**Actual result**
The image/the video is not visible at all.

### Technical Details

I'm not an instance admin.

### Version

0.18.2 and older

### Lemmy Instance URL

Various

**Comment by Nutomic** [comment] 2023-07-20 14:25
Sounds like a duplicate of https://github.com/LemmyNet/lemmy/issues/2611

**Closed by Nutomic** 2023-07-20 14:25 UTC
Labels: bug, federation

**Comment by JupiterRowland** [comment] 2023-07-29 09:44
> Sounds like a duplicate of #2611

Not quite. I don't even get a link. I get nothing.

If a Lemmy post only contains a title and an image, all I get is the title.

**Comment by JupiterRowland** [comment] 2023-07-31 05:43
By the way, the issue persists with Lemmy 0.18.3.

For example, the video in [this post on lemmy.ml](https://lemmy.ml/post/2626859) which runs on Lemmy 0.18.3 is missing from the post when seen on [the Hubzilla hub Netzgemeinde](https://hub.netzgemeinde.eu) which runs the current version of Hubzilla, 8.6.1.

**Comment by Nutomic** [comment] 2023-08-01 10:00
Thats an issue for the Hubzilla devs, Lemmy definitely federates the link.

**Comment by ShittyKopper** [comment] 2023-11-04 15:30
this (?) is a part of the reason why federation with misskey and it's forks are broken. misskey expects a type:Image* with a url field, but lemmy sends a type:Link with a href field instead

*: misskey actually has another issue where it sends type:Link attachments into it's image code, which means it tries to parse non-image links as images, completely breaking post fetching. **that's not lemmy's fault** but worth mentioning as if it weren't for this then posts would still be fetched, just with images appearing as direct links. 

(that said lemmy should still try to federate images as images in my opinion)
