### ISSUE TITLE
Add ability to toggle communities to private and only allow approved users to see posts and comment

### ISSUE THREAD

**Issue by x4740N** [LemmyNet/lemmy#4981] opened 2024-08-16 16:11 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

No

### Describe the solution you'd like.

I'm really missing the ability to toggle the community I moderate to private like we could do on reddit 

On lemmy communities could be toggled to private by community moderators and only allow approved members to see, comment on and interact with posts

Benefits of this feature would

* Help prevent trolls entering the community 
*  Protect communities where the main topic would attract trolls from outside of the topic or niche especially trolls who specifically target the topic or niche
* Protect community from trolls
* Prevent abuse of voting system on lemmy by trolls
* Help to prevent trolls from taking content from community and posting it elsewhere to harass and troll communities
* 
* # Describe alternatives you've considered.

Already thought of using existing moderation features but those do little to protect from trolls and cannot bring the benefits listed above

**Comment by dullbananas** [comment] 2024-08-17 03:17
Duplicate of #187

**Closed by dullbananas** 2024-08-17 03:17 UTC
Labels: enhancement
