### ISSUE TITLE
[Feature Request] Ability to filter certian sites

### ISSUE THREAD

**Issue by BetaPictoris** [LemmyNet/lemmy#4422] opened 2024-02-04 01:59 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

It's supper annoying whenever some sites show up in my feed (ie. YouTube, Piped). 

### Describe the solution you'd like.

Being able to block certain sites from showing up in the feed would be supper helpful. 

### Describe alternatives you've considered.

The only other solution I could see is keyword filtering (with the domain name) in some client, but that might also remove conversation surrounding the site that I might still want (ie. an AskLemmy post about YouTube might include the words "youtube.com," but that might still be useful to see).  

### Additional context

Related: #3710

**Comment by dessalines** [comment] 2024-02-08 03:24
Dupe of #3710

**Closed by dessalines** 2024-02-08 03:24 UTC
Labels: enhancement

**Comment by BetaPictoris** [comment] 2024-02-08 03:49
> Dupe of #3710

Sorry if I'm misunderstanding something, but I don't think that keyword filters would fully solve this issue.  If I'm understanding #3710 correctly wouldn't it only remove conversation surrounding the site, as the phrasing of the request sounds like it would be titles only (therefore only removing posts such as "Check out this video on _example.com_", but not "Watch this amazing video!" - with `example.com` attached as a URL)?  

Again, sorry if I'm totally misinterpreting how keyword filtering would work. Also, thanks for all the amazing work on Lemmy!

**Comment by dessalines** [comment] 2024-02-08 04:07
The filter should probably work on everything: titles, urls, descriptions, etc. I'll edit that issue's text to reflect it.

No probs!
