### ISSUE TITLE
Log is spammed from lemmy-ui

### ISSUE THREAD

**Issue by xundeenergie** [LemmyNet/lemmy#2238] opened 2022-04-26 13:47 UTC
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Issue Summary

A summary of the bug.

My log is spammed with
```lemmy-ui_1  | Only elements types base, body, head, html, link, meta, noscript, script, style, title are allowed. Helmet does not support rendering <undefined> elements. Refer to our API for more information.
lemmy-ui_1  | Only elements types base, body, head, html, link, meta, noscript, script, style, title are allowed. Helmet does not support rendering <undefined> elements. Refer to our API for more information.
lemmy-ui_1  | Only elements types base, body, head, html, link, meta, noscript, script, style, title are allowed. Helmet does not support rendering <undefined> elements. Refer to our API for more information.
lemmy-ui_1  | Only elements types base, body, head, html, link, meta, noscript, script, style, title are allowed. Helmet does not support rendering <undefined> elements. Refer to our API for more information.
lemmy-ui_1  | Only elements types base, body, head, html, link, meta, noscript, script, style, title are allowed. Helmet does not support rendering <undefined> elements. Refer to our API for more information.
lemmy-ui_1  | Only elements types base, body, head, html, link, meta, noscript, script, style, title are allowed. Helmet does not support rendering <undefined> elements. Refer to our API for more information.
lemmy-ui_1  | Only elements types base, body, head, html, link, meta, noscript, script, style, title are allowed. Helmet does not support rendering <undefined> elements. Refer to our API for more information.
lemmy-ui_1  | Only elements types base, body, head, html, link, meta, noscript, script, style, title are allowed. Helmet does not support rendering <undefined> elements. Refer to our API for more information.
lemmy-ui_1  | Only elements types base, body, head, html, link, meta, noscript, script, style, title are allowed. Helmet does not support rendering <undefined> elements. Refer to our API for more information.
lemmy-ui_1  | Only elements types base, body, head, html, link, meta, noscript, script, style, title are allowed. Helmet does not support rendering <undefined> elements. Refer to our API for more information.
lemmy-ui_1  | Only elements types base, body, head, html, link, meta, noscript, script, style, title are allowed. Helmet does not support rendering <undefined> elements. Refer to our API for more information.
lemmy-ui_1  | Only elements types base, body, head, html, link, meta, noscript, script, style, title are allowed. Helmet does not support rendering <undefined> elements. Refer to our API for more information.
lemmy-ui_1  | Only elements types base, body, head, html, link, meta, noscript, script, style, title are allowed. Helmet does not support rendering <undefined> elements. Refer to our API for more information.
lemmy-ui_1  | Only elements types base, body, head, html, link, meta, noscript, script, style, title are allowed. Helmet does not support rendering <undefined> elements. Refer to our API for more information.
lemmy-ui_1  | Only elements types base, body, head, html, link, meta, noscript, script, style, title are allowed. Helmet does not support rendering <undefined> elements. Refer to our API for more information.
```
### Technical details

Lemmy Version is 0.16.3 on Debian bullseye.

**Comment by Nutomic** [comment] 2022-04-26 14:01
Please use the correct repo next time, and check if the issue was already reported. Duplicate of https://github.com/LemmyNet/lemmy-ui/issues/628

**Closed by Nutomic** 2022-04-26 14:01 UTC
Labels: bug
