### ISSUE TITLE
Upload multiple images

### ISSUE THREAD

**Issue by ismailghedamsi** [LemmyNet/lemmy#3143] opened 2023-06-16 11:57 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

Would be cool to have support for multiple image uploads. I wanted to upload images of new albums on a music community but it's impossible

### Describe the solution you'd like.

Once the post is created, the first image is shown then users can click on the next and previous image

### Describe alternatives you've considered.

No other alternative comes to my mind

**Comment by FriederHannenheim** [comment] 2023-06-16 14:14
I've looked into this and it is already possible in the backend. The way that Lemmy posts work is they have one or zero urls, in the case of image posts, this url points to the image. What currently isn't possible is having multiple urls. This could be a feature request. 
You can upload and embed multiple images in your post though, this is also supported by lemmy-ui.

**Comment by ismailghedamsi** [comment] 2023-06-16 14:33
I just realized that i can put more than one images in the body but they show one below the next which is not user friendly if there is lot of images. A slider woukd be better. There is always at least 10 releases on friday alone.

**Comment by lionirdeadman** [comment] 2023-07-23 04:25
Duplicate of https://github.com/LemmyNet/lemmy/issues/981

**Closed by lionirdeadman** 2023-07-23 04:25 UTC
Labels: type: duplicate, enhancement, area: media
