### ISSUE TITLE
Subscribe to thread for notification of new comments

### ISSUE THREAD

**Issue by slrgt** [LemmyNet/lemmy#3797] opened 2023-08-02 16:30 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Threads come and go after a few days even though people might really like a thread and have value in following any updates

### Describe the solution you'd like.

Being able to subscribe to a thread so you receive notifications on any new comment or any new reply to any comment would be very valuable for many threads and help some communities be more forum like and less “social media“ like

### Describe alternatives you've considered.

Lemmybb Forum ui

**Comment by lionirdeadman** [comment] 2023-08-02 19:23
Duplicate of https://github.com/LemmyNet/lemmy/issues/3069

**Closed by lionirdeadman** 2023-08-02 19:23 UTC
Labels: enhancement
