### ISSUE TITLE
[Bug]: Lemmy doesnt disable federation with offline servers

### ISSUE THREAD

**Issue by ImLunaHey** [LemmyNet/lemmy#3134] opened 2023-06-16 00:26 UTC
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

If I federate with another server and then stop my lemmy instance no matter how many errors the other server gets it never stop flooding my server with lemmy traffic.

After so many failed requests the other server really should stop sending traffic.

![image](https://github.com/LemmyNet/lemmy/assets/105922175/ffc95fbe-1fbc-4b1c-91b6-c2dee3f5fa96)

### Steps to Reproduce

1. Install lemmy
2. Search for another server on lemmy
3. Shutdown lemmy
4. Profit?

### Technical Details

N/A

### Version

N/A

**Comment by cperrin88** [comment] 2023-06-16 09:16
That is a bit of a hard problem to solve. What is the right amount of time/requests to wait. It is possible that the Instance is just in maintenance mode or overloaded. Maybe the source server has network problems. It is really difficult to find out if it is intentional. 

I think the best solution would be to find a way for an instance to signal that it will shut down and wants to be defederated. I don't know how the signaling works but maybe deleting all the communities and users before shutting down might work.

Apart from that maybe lemmy should have a longer back off after a while, like only retry daily or something similar.

**Comment by ImLunaHey** [comment] 2023-06-16 09:47
Would be great if I could send back a header or something to disable this from my end without needing to bring the lemmy instance back up.

**Comment by Neshura87** [comment] 2023-06-22 12:54
A quick retroactive fix would be to introduce some kind of timed hearbeat signal that needs to be sent once in a while in the future. The heartbeat could then be sent in the following scenarios:
- new federated instance
- graceful shutdown
- random time window before heart beat expires (ie for a weekly heartbeat maybe sometime between 1-2 days before heartbeat expiration)

Since the heartbeat is not frequent it should not impact load too much, the time window with revalidation before expiration would also allow for network outages and maintenance windows without de-federating from the majority of lemmy. Plus even in the case of a de-federation occuring resending the heartbeat could be used to catch up that instance more quickly

**Comment by Nutomic** [comment] 2023-06-30 13:31
Duplicate of #2221

**Closed by Nutomic** 2023-06-30 13:31 UTC
Labels: bug

**Comment by ImLunaHey** [comment] 2023-06-30 13:37
@Nutomic this is not a duplicate. That talks about checking if instances are live.

This is about requests that're sent without backing off on errors.

**Comment by LucifersCircle** [comment] 2024-12-10 15:33
Does lemmy still not stop sending requests to dead servers? I had one taken offline a year ago and my domain still gets hit tens of thousands of times daily. I have even been returning a 410 status code to tell lemmy servers my resource is permanently gone. I feel that sending a 410 on the domain should be plenty enough info for lemmy to stop trying to reach your server.

**Comment by ImLunaHey** [comment] 2024-12-11 02:31
@LucifersCircle yep i still get traffic that i have to blackhole. this needs to be fixed. 🙃

**Comment by Nothing4You** [comment] 2024-12-11 12:37
410 is a tolerable status code for federation currently and is considered as non retryable result. 5xx errors would trigger lemmys federation failure detection and lead to exponential backoff.

if your goal is to reduce the amount of requests this should help a lot, although some requests may still happen over time.

**Comment by LucifersCircle** [comment] 2024-12-11 23:13
Wow! Thank you so much for this!
