### ISSUE TITLE
How to implement new user settings?

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#3584] opened 2023-07-11 13:36 UTC
Many of the currently open pull requests are for adding new lemmy-ui user settings, for example keyboard navigation or infinite scroll. These settings are surely useful, but the process for adding them is unnecessarily complicated. Not only does a new setting have to be implemented in lemmy-ui, it also requires changes to this repo for adding a database migration, as well as adding the setting to various database and api structs.

This results in very repetetive work to implement and review such changes. It would be good if the process could be simplified in one way or another. A related problem is that we only store settings for lemmy-ui, but it would also be useful to store settings for alternative frontends and client apps.

One possible solution would be not to store individual settings, but an arbitrary json blob where Lemmy doesnt need to care about the content at all. This would also allow a user to store multiple settings blobs for different frontends/clients. Lemmy would have to do nothing more than provide endpoints for writing/reading the settings, and enforce a size limit. 

Are there other solutions worth considering?

**Comment by dessalines** [comment] 2023-07-11 13:44
Its cumbersome mainly because of all the pieces that need to fit together: lemmy settings -> client libraries -> front end apps. That's an unavoidable process, even if we were to "untype" settings.

I definitely want to keep the well-typed settings table, because it ensures that X field is available to the UI's after it gets added to the lemmy backend, (and the client libraries auto-generate their types from it). 

Adding arbitrary json as settings would cause a ton of problems: UI's would add fields that aren't necessarily included in the release, and it would make the client libraries ignorant of what data and abilities they actually have.

>  A related problem is that we only store settings for lemmy-ui

Jerboa and other client apps can use the settings as well, for things like `hide_vote_scores`, and plenty of others.

We should just be lenient about adding whatever extra settings people would like, for all front ends to use.

**Comment by Dogeek** [comment] 2023-07-11 20:20
I definitely agree on typing being a huge plus, but as it stands, it is very cumbersome to implement new UI behaviours that can sync, since you need to edit the backend to store such settings. I can also see a problem where the local user table will become very bloated with a lot of settings (let's look at RES and it's ginormous settings pannel). Postgres has thankfully a max number of columns of 1600 per table, but that's still a lot, and will eventually be too bloated.

Furthermore alternative UI clients may want to be able to store user settings on the server that would not benefit other frontends. In that case, editing the backend is troublesome and doesn't provide much value to the ecosystem as a whole.  Having an extra JSON field here might make it more flexible for such use cases.

If typing is an issue, maybe a JSON blob + a JSON schema to provide the typing metadata might be used ? I'm just spitballing here, but we could have the settings be stored in a JSON blob in the db, and have a JSON schema file describing that blob on the repo that can be used to generate the typescript interfaces from (or other languages, tools already exist to do that sort of thing). It would limit the PRs to just that one JSON schema, easing the maintenance of the settings, and lowering the workload on the maintainers ?

**Comment by Dogeek** [comment] 2023-07-13 04:53
I don't think a table (id,user_id,pref_key,pref_value) would achieve anything better than a JSON blob. The issue is still there, you cannot *statically* type the value of the preference. You could add an extra column `pref_type` to be able to do type assertions "safely" in the front end, but you won't be able to get the clean interface like we have right now.

**Comment by phiresky** [comment] 2023-07-13 10:38
In my opinion (and something I've done with success in the past) a good compromise would be to use a JSON blob on the postgresql side, but that is fully typed at the very least on the TypeScript (client) side and potentially also on the Rust side. On Rust side it could look something like the RawAnnounceableActivities struct with flattening unknown properties:

```rust
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct SaveUserSettings {
  show_nsfw: Option<bool>,
  setting_2: String,
  setting_3: bool,
  .....
  #[serde(flatten)]
  other: Map<String, Value>,
}
```

Or without (flatten) and keeping others in a separate property (`type Settings { show_nsfw?: boolean; ...; other: Record<string, unknown> }`). That has the advantage of preventing issues when new "official" settings are added, but the disadvantage that existing custom settings in `other` can't be made "official" after some time.

The performance overhead of fetching / writing whole json blobs shouldn't start mattering if there's less than like 1kB of data in there (remember that PG already rewrites the whole row except for uninlined toast strings when you update a single column). Of course it would need a reasonable size limit to prevent DOS.


> Adding arbitrary json as settings would cause a ton of problems: UI's would add fields that aren't necessarily included in the release, and it would make the client libraries ignorant of what data and abilities they actually have.

That is an annoying problem, but I don't think it's really 100% preventable in the real world regardless of how it's done - you always need to account for client-server version drift and you don't want the UI to instantly start throwing visible errors if there's some setting it doesn't understand yet.

**Comment by Nutomic** [comment] 2023-07-13 11:27
I agree, it makes a lot of sense to have a Rust struct for validation of user settings, which gets stored in the database in a single json column. The new settings struct would essentially consist of most `LocalUser` members, excluding id, person_id, password_encrypted and email. To keep the current behaviour of well-typed settings, it musnt have any `other` property with serde flatten. Adding new settings would then only require a new field in the settings struct, no need for any db migrations or other code changes. Removing or editing settings would probably require code migrations to rewrite existing db entries, but thats not common anyway.

This approach doesnt require any api changes, only some internal refactoring. I agree that we dont need to handle settings for other apps, it would get too complicated.

**Comment by not-my-profile** [comment] 2023-07-13 13:03
I think we should distinguish between settings that effect the API and settings that do not effect the API (and only effect the user-interface of the client). Let's call them backend user settings and client-only user settings.

I think it's quite clear that client-only user settings are not of concern to the backend and should thus simply be stored in an opaque JSON object. There is precedence for that in the form of the OpenStreetMap editing API, [which allows editors to store arbitrary user preferences](https://wiki.openstreetmap.org/wiki/API_v0.6#Preferences_of_the_logged-in_user:_GET_/api/0.6/user/preferences).

> Adding arbitrary json as settings would cause a ton of problems: UI's would add fields that aren't necessarily included in the release, and it would make the client libraries ignorant of what data and abilities they actually have.

With the above distinction in mind, this concern doesn't make sense. While backend settings do indeed represent "client abilities" and should thus of course be strongly typed, client-only settings can be completely arbitrary and depend entirely on the user-interface of the client ... they are independent from the backend version.

Clients may want to introduce settings that are not relevant for other clients, for instance a client focused on accessibility may want to introduce a bunch of settings focused on that. And lastly it surely doesn't make sense for client-only settings to only work with backends that are aware of them (since they do not need to be).

**Comment by dessalines** [comment] 2023-07-14 15:00
I strongly advise against using a json column for settings, and really dislike mixing the JSON approach with SQL, which should only store tabular data. Some reasons against:

- It will make migrations really annoying, or impossible. What if we need to remove settings columns, change their defaults, change their names? We'll have to do a complicated migration that scans a JSON column for names / values.
- How will column defaults be handled? SQL columns have a lot of extra info around them, that would need to be manually added to the JSON definitions.
- What if we need to add indexes / filters / sorts based on user settings later? It *might* be useful for some admin-related actions in the future.
- It would then be possible for the DB to be inconsistent with the columns marked in code. The DB JSON column might contain things the code is ignorant about, or vice versa. I see a lot of issues in UI development from potential inconsistencies.
- It makes it difficult to see what the DB is actually holding.

The only benefit from moving to a duck-typed column, is that an explicit DB migration isn't required. We have tons of examples of those already, and its mostly a copy-paste process. Isn't really that irksome IMO, and we should **always** prefer explicit typing over ease of development.

**Comment by not-my-profile** [comment] 2023-07-14 15:35
Right, I agree that it makes sense to keep backend user settings as regular SQL columns ... however none of what you just said speaks against modeling client-only user settings as opaque JSON values. (Since the backend shouldn't be concerned with anything (type, default or value) of client-only settings). Note that clients can still totally use strong typing for their client-only settings ... the opaque value is just how these settings would be stored in the database.

**Comment by SorteKanin** [comment] 2023-08-03 10:06
@dessalines I think maybe you are misunderstanding the suggestion here? Nobody here is suggesting to keep server-side settings in JSON columns.

> * It will make migrations really annoying, or impossible. What if we need to remove settings columns, change their defaults, change their names? We'll have to do a complicated migration that scans a JSON column for names / values.

You won't have to do any of these things because the JSON is opaque to the backend and entirely in control by the client. The client will have to do setting update requests to do its own "migrations".

> * How will column defaults be handled? SQL columns have a lot of extra info around them, that would need to be manually added to the JSON definitions.

Clients will manage their own defaults, the server will not care to verify anything with these client settings (aside from reasonable size limits on the JSON). It is up to the client to control the defaults.

> * What if we need to add indexes / filters / sorts based on user settings later? It _might_ be useful for some admin-related actions in the future.

You won't, the client will only request these settings on their own. The server won't ever look into the JSON and won't care about the client settings.

> * It would then be possible for the DB to be inconsistent with the columns marked in code.

No, because the code will again not care about what is in the JSON. It is opaque, client-only settings.

The suggestion could be used, just as one simple example, to hold the theme settings for an app or frontend. Imagine a frontend or app that allows the user to specify specific colors for various things (like specific colors for the background, links, usernames, whatever). As it is right now, the client would have to store that information _in the client_, using some local storage or whatever. But when the user then switches their phone or browser, the settings are lost. The suggestion here is to allow clients to save client-specific settings in a JSON column so that it can later retrieve it again from the server without relying on local storage.

For example, all the various colors mentioned before could be stored in a JSON server-side and the client could retrieve it from the server again. The server _does not need to know and does not care_ about what is actually in the JSON, aside from ensuring that the JSON is not abused in some way (i.e. size).

**Comment by dessalines** [comment] 2023-08-03 15:50
> The suggestion here is to allow clients to save client-specific settings in a JSON column so that it can later retrieve it again from the server without relying on local storage.

That has nothing to do with this issue. We already return every user setting in the `MyUserInfo` struct as json to clients, and also have a SaveUserSettings endpoint. How clients use and store that is their business.

This issue is about moving from well typed user settings sql columns, to a single untyped json column, to avoid database migrations, and allow users to put any untyped data they want in a json sql column.

**Comment by SorteKanin** [comment] 2023-08-03 16:03
That is not how I understood the issue, but maybe I've misunderstood as well.

The way I see it, we want two kinds of settings saved in the database:

1. Server-side settings. Examples are:
    - What communities a user is subscribed to.
    - What users a user has blocked.
    - What communities a user moderates.
    These settings affect API responses and should therefore be saved server-side and the server should _know and care_ about these settings. **These settings should be strongly typed in SQL**.
2. Client-side settings. Examples are:
    - The appearance of the client.
    - Settings for post-API filtering of posts.
    - Anything the client wants really. A client could even for instance allow the use of custom CSS or something.
    These settings _do not_ affect API responses and the server _does not know and does not care_ about these settings. **These settings should be kept as a JSON column** and it is up to the client to figure out what data goes in or out of that JSON. Actually, each client should have its own JSON. So each user could have separate client-only settings for lemmy-ui and some other app/frontend.

As far as I can tell, `MyUserInfo` is of the first type, so is not affected by the suggestion here (as I understand it) and should stay strongly typed and nobody is suggesting it should be weakly typed JSON in the database.

Am I totally off? Is this not what was meant? @Nutomic could you maybe explain the idea more thoroughly, cause I think there is confusion here about what the actual suggestion is.

**Comment by dessalines** [comment] 2023-08-03 16:14
Splitting them into two types of settings, would be unecessarily complicated imo. Sure something like hide-scores doesn't affect business logic, but a setting like hide-read-posts does. 

Also all clients could make use of hide-scores, and it might even affect business logic in the future(say if we decide to make all the scores optional so that front ends never even receive them).

Again, SQL works fine for storing settings, and the benefits of doing a migration to add settings columns vastly outweighs the benefits of untyping user settings.

**Comment by Nutomic** [comment] 2023-08-11 11:13
Splitting the settings isnt really complicated, and certainly easier than having to write database migrations for every new client setting. Examples for such client settings are `open_links_in_new_tab` or `infinite_scroll_enabled` which are completely irrelevant for the backend.

These client settings would still be strictly typed, not on the database level but in the `SaveUserSettings` api handler. So its not possible to store any custom settings values.

**Comment by SorteKanin** [comment] 2023-08-11 13:18
>These client settings would still be strictly typed, not on the database level but in the SaveUserSettings api handler. So its not possible to store any custom settings.

Hmm if custom settings aren't possible then I don't see the benefit as much and in that case I would agree with @dessalines that it would be better to have them strictly typed in the database as well. If they are strictly typed in the API, that typing should follow everywhere. It shouldn't be forgotten in the database.

**Comment by sbordeyne** [comment] 2023-08-22 19:16
> > These client settings would still be strictly typed, not on the database level but in the SaveUserSettings api handler. So its not possible to store any custom settings.
> 
> Hmm if custom settings aren't possible then I don't see the benefit as much and in that case I would agree with @dessalines that it would be better to have them strictly typed in the database as well. If they are strictly typed in the API, that typing should follow everywhere. It shouldn't be forgotten in the database.

To recenter on the core issue of the current state of things, we currently need to edit the backend of lemmy (in rust) to create and sync settings strictly meant to be used in the front end part of the application. Adding a db migration, modifying the API responses etc is no trivial matter for someone not well versed in rust (and diesel as an ORM).

It's especially aggravating since the order of the column matters (for some reason) which is really not trivial to figure out.

Maybe an alternative would be to automate the adding of settings to the user settings table with a script that anyone can run, something like `cargo run add-setting $SETTING $TYPE` (i.e. `cargo run add-setting open_links_in_new_tab bool`) which would then edit the code in the relevant places, and generate the correct migrations.

It would keep the whole thing strictly typed as @dessalines seems to be very attached to that, and would provide a better developer experience for anyone ~~crazy enough to want~~ wanting to contribute to the lemmy project

**Comment by dessalines** [comment] 2023-08-31 15:25
Side point, but we have *a lot* of merged PRs for people adding settings. Anyone can look at those to see how its done. 

I wouldn't be opposed to someone writing a script to add them, but occasionally settings can get more complicated.

**Closed** 2024-03-14 15:34 UTC
Labels: type: discussion
