### ISSUE TITLE
Add Mastodon-style custom profile fields

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#246] opened 2019-08-29 00:37 UTC
Can be either links or plaintext. Mastodon allows a maximum of 4 such fields. Example:

![Screenshot_20220801_200412](https://user-images.githubusercontent.com/1044450/182213079-e4fe1b6e-6faf-4fb9-b9e0-9a65d2ab56ae.png)

**Comment by growl360** [comment] 2019-11-17 04:09
Flairs would be better than nicknames

**Comment by Nutomic** [comment] 2021-03-03 12:08
This is basically done, we are just missing the 4 link fields. But I dont think thats important, I've already seen someone reproduce it with a markdown table. So I'd say we can close this issue.

**Comment by dessalines** [comment] 2021-03-03 16:33
No I think we need this open, because those special URL link fields can be used to verify identity: 

IE like `<a rel="me" href="https://mastodon.social/@dessalines">Mastodon</a>`

**Comment by Nutomic** [comment] 2021-03-03 16:35
Okay, but might be worth to open a new issue specifically for that identity verification, because it would need some additional work which isnt mentioned here.

**Comment by Nutomic** [comment] 2024-03-15 11:26
Unnecessary.

**Closed by Nutomic** 2024-03-15 11:26 UTC
Labels: enhancement, area: profiles

**Comment by m-p-3** [comment] 2024-04-07 14:11
Sorry to comment on a closed issue, but would it be a good idea to automatically add the `rel="me"` tag on all links in the Lemmy bio? That way they could be used to *verify* Lemmy accounts on Mastodon profiles without having custom URL fields like on Mastodon.

**Comment by dessalines** [comment] 2024-04-09 23:58
That re-writing would probably be best in lemmy-ui. I'll re-open and transfer this.
