### ISSUE TITLE
CSS no longer rendering correctly in Pale Moon

### ISSUE THREAD

**Issue by gitbugged** [LemmyNet/lemmy#898] opened 2020-07-03 16:42 UTC
Up until recently, the site worked fine in the [Pale Moon](https://www.palemoon.org) browser.

However, a recent update to the site caused it to look like this: https://i.imgur.com/kRC4hgi.jpg

The entire style sheet is essentially white. If there has been a recent underlying API/framework update perhaps it could be correlated with [UXP](https://github.com/MoonChildProductions/UXP) developers.

Thanks!

**Comment by dessalines** [comment] 2020-07-03 17:05
Dupe of #570

**Closed by dessalines** 2020-07-03 17:05 UTC
