### ISSUE TITLE
iframely.config.local.js error 404

### ISSUE THREAD

**Issue by altilunium** [LemmyNet/lemmy#1721] opened 2021-08-23 06:58 UTC
https://join-lemmy.org/docs/en/administration/install_docker.html
![image](https://user-images.githubusercontent.com/70379302/130403935-03a09b5f-0824-44bb-a030-57ee07ecfbc0.png)

![image](https://user-images.githubusercontent.com/70379302/130403902-da330bfc-99c5-4285-90f1-b41b739b4618.png)

**Comment by dessalines** [comment] 2021-08-23 11:59
Also dupe of #1717

**Comment by Nutomic** [comment] 2021-08-23 12:07
Lets leave this open in case more users run into it (until the new version is out).

**Comment by dessalines** [comment] 2021-09-13 15:46
This is out now.

**Closed by dessalines** 2021-09-13 15:46 UTC
Labels: bug
