### ISSUE TITLE
Lemmy not able to be crawled/indexed

### ISSUE THREAD

**Issue by 47773838382882828** [LemmyNet/lemmy#726] opened 2020-05-17 01:52 UTC
Since it is a web app, googlebot and other bots aren't able to index the site. 

Archiving with the internet archive also dosent work.

Any possible workarounds?

**Comment by dessalines** [comment] 2020-05-17 01:54
You just opened up this exact same issue: #725 

Are you spamming issues?

Dupe of #226

**Closed by dessalines** 2020-05-17 01:54 UTC

**Comment by 47773838382882828** [comment] 2020-05-17 01:57
Sorry must have clicked twice or something

**Comment by dessalines** [comment] 2020-05-17 02:15
Ah, cool.
