### ISSUE TITLE
marked as deleted posts are still visible when knowing the URL

### ISSUE THREAD

**Issue by toogley** [LemmyNet/lemmy#891] opened 2020-07-02 21:28 UTC
https://dev.lemmy.ml/post/36746 is a post that is deleted by the creator. But with the link, it is still visible, even when not being logged in. Also happens if a mod removes a post.

**Comment by dessalines** [comment] 2020-07-02 22:22
That's true, tbh I'm not quite sure *how* much to censor removed info.

For example we've gotten requests that the modlog shouldn't even show what was removed, have it just say (*removed post*), which IMO doesn't give you much context.

My initial thinking was removed posts should still be available so that ppl can see them, but only if they know the url, they're not visible from the main site, and clearly removed by the admin / mod. This one needs some discussion.

I also have to check if its possible for an admin to lock / unlock posts, which would make it so that no more comments can be added.

**Comment by RayBB** [comment] 2020-07-03 20:15
I don't know about your legal status as an org but may want the ability at some level to completely remove content that is illegal to host.

**Comment by dessalines** [comment] 2020-07-03 22:45
Obvi we can easily remove things in the DB, since we have access to that, but it might be helpful to add an admin ability to "super-delete" something which removes any trace of it. I'll make an issue for it.

**Comment by Nutomic** [comment] 2020-07-04 11:37
We could also consider keeping removed posts, but making it so that only logged in users can see them. Or only admins/mods.

**Comment by dessalines** [comment] 2020-07-11 15:50
This is kinda a dupe of #904 . Adding a purge functionality could make posts completely unavailable, but just a remove should probably at least still have the content available to see by url.

**Closed by dessalines** 2020-07-11 15:50 UTC
