### ISSUE TITLE
Subscription Groups

### ISSUE THREAD

**Issue by trymeouteh** [LemmyNet/lemmy#3875] opened 2023-08-13 05:21 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Organizing hundreds of community subscriptions.

### Describe the solution you'd like.

The ability to create, edit and delete community groups.

Lets say a user is subscribed to many gaming communities, The user can create a group named "Gaming" and add all the gaming communities can be added to that group such as !skyrim@lemmy.world and !pcgaming@lemmy.ml.

And allowing a subscribed community be under multiple groups. Lets say a user has a group named "Tech" and another group named "Linux". The user could have !linux@lemmy.ml under both the Tech grouo and Linux group.

When sorting your feed by subscription, you can filter your feed further by view all subscribed feeds or filtering what groups to see in your feed.

### Describe alternatives you've considered.

Adding tags to subscribed communities.

**Comment by lionirdeadman** [comment] 2023-08-14 04:26
Duplicate of https://github.com/LemmyNet/lemmy/issues/818

**Closed by lionirdeadman** 2023-08-14 04:26 UTC
Labels: enhancement
