### ISSUE TITLE
Add way to determine if server supports pictrs

### ISSUE THREAD

**Issue by fishcharlie** [LemmyNet/lemmy#5218] opened 2024-11-20 20:01 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

There is no way as a Lemmy developer to determine if a server supports pictrs. Which can lead to errors if you try to upload a picture to pictrs and it doesn't exist or the server doesn't support it.

Additionally I want to present different UI if pictrs is enabled on the server vs not.

### Describe the solution you'd like.

A value in [GetSiteResponse](https://join-lemmy.org/api/interfaces/GetSiteResponse.html) to indicate if pictrs is supported on the server.

### Describe alternatives you've considered.

I can't think of any other alternatives that meet my criteria here.

### Additional context

I don't really know how common/uncommon it is for servers to not have pictrs enabled.

I also posted about this [here](https://eventfrontier.com/post/196011).

**Comment by dessalines** [comment] 2024-11-21 13:43
Kind of a duplicate of #1118 and #1772 , which will by necessity need to show these.

**Comment by Nutomic** [comment] 2024-11-22 13:33
The thing is that there is no clear concept in Lemmy of "supporting pictrs". There is a config option for the pictrs url, but even if it is not set it uses a default value. And with pictrs configured and installed, it is still possible that pictrs is temporarily down, or uploads fail because the disk is full. However it does make sense to indicate whether image uploads are supported.

What we could do is remove the default config value for `pictrs.url` so that it needs to be specified explicitly. This would be a breaking change. Then we can add a field `images_enabled` to `/api/v3/site`. Alternatively we could ping the pictrs url at regular intervals, and set `images_enabled` based on that (so no breaking change).

**Comment by Nutomic** [comment] 2024-11-25 10:21
That endpoint is currently not public, but Im exposing it with https://github.com/LemmyNet/lemmy/pull/5224

**Comment by dessalines** [comment] 2024-11-25 16:55
Fixed by above PR.

**Closed by dessalines** 2024-11-25 16:55 UTC
Labels: enhancement, area: media
