### ISSUE TITLE
Have an option when creating a thread for it to automatically sort by New when displayed

### ISSUE THREAD

**Issue by abstruction** [LemmyNet/lemmy#3600] opened 2023-07-12 20:54 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

The motivation for this feature is sports game-day threads, which people participate in while following a game in real-time. Sorting by new makes the most sense, and asking people to manually change their sort to New for each thread is tiresome. Reddit did eventually implement this feature and it works great.

### Describe the solution you'd like.

I'd like to see a simple check box that says "Sort by New" on the post creation page, probably right next to the checkbox for NSFW. Additionally this would need to be exposed via the API so bots could set it.  
It might only be available to moderators, which I believe is the case on Reddit.

### Describe alternatives you've considered.

You could complicate matters with a Default Sort dropdown with all of the different sort types, rather than just a checkbox for the New type. I'm not sure what the usecase is for that, though.  
Alternatively, you could only expose the option through the API.

**Comment by dessalines** [comment] 2024-05-04 16:23
For this, we should either utilize the user's default_post_sort (with the post -> comment sort mapping), or add a default_comment_sort field. Shouldn't be too difficult tho.

**Comment by dessalines** [comment] 2024-05-04 17:16
Dupe of #4128 , which is more clear.

**Closed by dessalines** 2024-05-04 17:16 UTC
Labels: enhancement
