### ISSUE TITLE
Allow users to block instances

### ISSUE THREAD

**Issue by TalOrenshtein** [LemmyNet/lemmy#2625] opened 2022-12-21 03:07 UTC
### Is your proposal related to a problem?

Kind of. When I'm browsing at the "All" section, I ran into a lot of non-english  instances. 

### Describe the solution you'd like

Being able to use the user's block function at the settings to block whole instances.
For example: instead of entering community.instance.abc , we could enter *.instance.abc and it'll filter out all of the posts from communities from that specific instance.

### Describe alternatives you've considered

Using the "Subscribed " sort instead. But this way I miss a lot of content.

**Comment by kartikynwa** [comment] 2022-12-22 19:21
Next release will add support for specifying language of posts. Not sure if it allows filtering by it.

**Comment by dessalines** [comment] 2022-12-22 21:43
It does allow filtering by language. 

But as to this issue, another thing is that individual users want to block whole instances, not just communities. That could be doable, now that we have an `instance` table. Having a "regex block", would probably not be as doable.

**Comment by TalOrenshtein** [comment] 2022-12-22 22:02
Alright, can't wait for the next release :)
So I'm closing this issue. Thanks.

**Comment by dessalines** [comment] 2022-12-22 22:36
We don't have an issue for the other one, so I'll re-open and rename this one :)

**Comment by dessalines** [comment] 2022-12-22 22:36
My bad, nm. Dupe of #2397

**Closed by dessalines** 2022-12-22 22:36 UTC
Labels: enhancement
