### ISSUE TITLE
Allow moderators to flag posts as NSFW

### ISSUE THREAD

**Issue by QazCetelic** [LemmyNet/lemmy#4887] opened 2024-07-05 18:56 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

I moderate a couple communities and sometimes posts miss the NSFW flag but don't violate the rules. This is a problem because there is only 1 tag and hundreds of reasons whether to apply it or not, which can make it unclear for posters what to choose. Additionally, many communities also have their own specific conditions, further increasing confusion.

### Describe the solution you'd like.

Allow moderators to flag user posts in their community as NSFW

### Describe alternatives you've considered.

- Remove the post even though it doesn't really violate the rules, even though that's rude to do when the OP has no ill intent.
- Send a DM to the user asking them to do it, even though this requires waiting and might take several days

**Comment by dessalines** [comment] 2024-07-09 14:06
We've discussed this in another issue at length, but I'm personally against any moderator / admin ability to "modify" other people's content in any way other than removing / restoring it. 

Its a vector for abuse, and a slippery slope that eventually leads to mods and admins being able to edit other people's posts and comments.

**Comment by dullbananas** [comment] 2024-07-09 18:12
Duplicate of #3566

**Closed** 2024-07-09 18:13 UTC
Labels: enhancement, area: moderation

**Comment by QazCetelic** [comment] 2024-09-07 07:54
@dullbananas this is not a duplicate. The other issue wanted the ability to fully change post metadata and was rejected because it was too broad. This issue wants a 1 way ability to set a post as NSFW.
