### ISSUE TITLE
ability to search/view list of all communities on all linked instances

### ISSUE THREAD

**Issue by Die4Ever** [LemmyNet/lemmy#4412] opened 2024-01-28 14:18 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently users need to use https://lemmyverse.net/communities or https://browse.feddit.de/ to find communities. Lemmy should have a built in way to do this.

### Describe the solution you'd like.

I don't think it would take much disk space for every instance to save the ID/name of every community on every other linked instance. It could be a config option, I'm sure it'd be a drop in the bucket for large instances to enable this.

Alternatively Lemmy could make an API call to an external database like lemmyverse.net, or host it on join-lemmy.org. The API call would maybe just put the list of blocked instances in the request, or filter after receiving the list back from the API.

### Describe alternatives you've considered.

The communities page and search page could have a link to https://lemmyverse.net/communities

**Comment by Die4Ever** [comment] 2024-01-28 14:20
spawned from this discussion https://sh.itjust.works/post/13638806

**Comment by Nutomic** [comment] 2024-01-29 13:36
This is essentially a duplicate of https://github.com/LemmyNet/lemmy/issues/2951 because we can only search/view communities which are stored in the local database.

**Closed by Nutomic** 2024-01-29 13:36 UTC
Labels: enhancement
