### ISSUE TITLE
Add "Warning" as a valid mod action

### ISSUE THREAD

**Issue by SomethingElseForAChange123** [LemmyNet/lemmy#4410] opened 2024-01-28 01:56 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

No, it's not a problem, I just like to warn users that hey, you're breaking rules, here's a copy of the rules, please read, and have that as part of the official record, so I don't have to keep track of it myself. I'm probably too lenient of a mod, but still.

### Describe the solution you'd like.

Add "Warning" as a sort of no-op moderator actions.

### Describe alternatives you've considered.

Keeping an external spreadsheet, but that kinda defeats the purpose of a modlog

**Comment by Nothing4You** [comment] 2024-01-28 22:40
this looks like it's a duplicate of #1424

**Closed** 2024-01-29 10:00 UTC
Labels: enhancement
