### ISSUE TITLE
Comment count is calculated twice for remote posts

### ISSUE THREAD

**Issue by Tealk** [LemmyNet/lemmy#2998] opened 2023-06-09 09:06 UTC
### Issue Summary

On my instance, the number of comments of the remote posts are always considered twice as high as they actually are.

### Steps to Reproduce

1. Subscribe to Community
2. wait until a post receives comments

### Technical details

https://lemmy.rollenspiel.monster/post/79693:
![image](https://github.com/LemmyNet/lemmy-ui/assets/12276250/aa475a40-76f4-4207-9914-ab18e8351bd4)

https://feddit.de/post/772004:
![image](https://github.com/LemmyNet/lemmy-ui/assets/12276250/c3ca204e-995b-4a43-8a36-1be7e092b950)

**Comment by dessalines** [comment] 2023-06-09 16:58
Back end, not front end issue, as the comment counts are just read from the back end.

Likely a comment count trigger issue.

**Comment by dessalines** [comment] 2023-10-18 20:47
Dupe of #3722

**Closed by dessalines** 2023-10-18 20:47 UTC
Labels: bug, area: federation
