### ISSUE TITLE
multiple clicks of "Post" button make multiple posts/comments

### ISSUE THREAD

**Issue by dioraman** [LemmyNet/lemmy#737] opened 2020-05-23 18:38 UTC
If one clicks multiple times the "post" button to post a post/comment, then posts/comments as many as the number of clicks will appear.
One expects only one post/comment will appear.

*N.B.: this multiple submits may happen in other cases too, so a general solution is preferred instead of one working only for these two reported cases.*

Post case picture:
![](https://dev.lemmy.ml/pictshare/13p41k.jpg)
OT question: why has the last no upvote?

Comment case picture:
![](https://dev.lemmy.ml/pictshare/6mc7sl.jpg)

**Comment by dessalines** [comment] 2020-05-23 22:04
Dupe of #706

**Closed by dessalines** 2020-05-23 22:04 UTC
