### ISSUE TITLE
Search communities by instance

### ISSUE THREAD

**Issue by fiskfisk33** [LemmyNet/lemmy#3207] opened 2023-06-20 06:15 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

I find there is a lack of a way to search for communities on a specific instance.
If I for example search for "lemmy.ml" i get the singular hit: [lemmy.ml meta@lemmy.ml](https://lemmy.one/c/meta@lemmy.ml), while what I really wanted was to list off all the communities on that instance.

### Describe the solution you'd like.

The simplest solution would be to include the instance name in what is being searched, so for example a search for kbin.social would list off all the magazines on kbin.social as well as any community named kbin.social on other instances, for whatever reason.

Another would of course be to have a check box or something so you could do both.

### Describe alternatives you've considered.

Right now the only work around I know of is to open the other instance in another tab/window and list there, then manually search or test the federated links one by one from the instance I come from. 

### Additional context

This MIGHT be a lemmy-ui thing, but I'm not sure, I don't know how the search is implemented.

**Comment by jordan1776** [comment] 2023-06-21 00:58
It's been talked about on #3105 and had I mentioned something similar in [lemmy-ui #1298](https://github.com/LemmyNet/lemmy-ui/issues/1298). The issue with simply adding @ instance is you would only be listing communities that been discovered, so if you try that with a small instance, you might find only a few of a dozen communities in that search.

**Comment by That-Annoying-Guy** [comment] 2023-06-21 19:14
This is more like [Lemmy-ui #1397](https://github.com/LemmyNet/lemmy-ui/issues/1397) [Make it easier to browse communities on other instances.]

**Comment by dessalines** [comment] 2023-10-18 21:46
Dupe of #2951

**Closed by dessalines** 2023-10-18 21:46 UTC
Labels: enhancement, area: discovery, area: search
