### ISSUE TITLE
Reports don't federate to every instance of all moderators

### ISSUE THREAD

**Issue by SomethingElseForAChange123** [LemmyNet/lemmy#4411] opened 2024-01-28 02:01 UTC
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Reports don't federate to every instance of all moderators

https://lemm.ee/c/conservative had to have peepingoodargs create a new account on lemm.ee just to see all the reports

### Steps to Reproduce

1. Community on instance X adds moderator on instance Y
2. Report is created on instance X
3. That report goes to the moderators and admins of the community, and the users involved. But not to every moderator

### Technical Details

I'm not a technical person

### Version

0.19.3

### Lemmy Instance URL

lemm.ee

**Comment by Nothing4You** [comment] 2024-01-28 22:41
duplicate of #3781

**Closed** 2024-01-29 13:39 UTC
Labels: bug
