### ISSUE TITLE
Planned posts

### ISSUE THREAD

**Issue by EmilJacobs** [LemmyNet/lemmy#4882] opened 2024-07-04 00:13 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

I post multiple articles a day on a Lemmy board. It would be helpful to be able to plan them. For example, post articles from a certain language when people in that language's timezone are mostly active on Lemmy.

### Describe the solution you'd like.

Being able to plan my posts during a certain moment in the day.

### Describe alternatives you've considered.

There are currently no alternatives for doing this.

**Comment by Nutomic** [comment] 2024-07-04 09:42
Duplicate of https://github.com/LemmyNet/lemmy/issues/234

**Closed by Nutomic** 2024-07-04 09:42 UTC
Labels: enhancement
