### ISSUE TITLE
[Bug]: Some Lemmy instances sending every activity twice 

### ISSUE THREAD

**Issue by freamon** [LemmyNet/lemmy#4609] opened 2024-04-08 14:35 UTC
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

This is discussed [this post on on Lemmy](https://lemmy.world/post/14031504) - you can see me protesting that it should be me filing the report, but I've slept since then, and Nutomic said please (?!). There's a question of whether it's due to instance configuration, Lemmy itself, or some combination of the two (it only stated with 0.19.x, but not all instances do it, and there isn't always a correlation between it happening and the amount of containers an instance is using). I was reluctant to make this Issue because there's information you'll need about instance config that I'm not going to be able to give to you, because I'm not running Lemmy, so this is all second-hand info and observation.

The post on Lemmy has a video. The background to it is that I wanted to use ActivityPub for an Automod on lemmy.world/c/starwarsmemes, so I sent a Follow request to that community (using a Ruby script). When anything happens lemmy.world sends an Announce activity to my server, and the Automod can, amongst other things, send a notification to my phone when a new post is made. In the video, the red terminal is showing a `tail -f` on the nginx log; the green terminal is showing the `.object.id`, `.object.type`, and `.object.actor` from the JSON contained inside each request. starwarsmemes is pretty quiet at the minute, so I was able to monitor the results of activity that I myself was generating as a user on lemmy.world. Hopefully, the video makes it clear that duplicate activity is being sent every time.

I've seen similar behaviour before: [post on lemmy.ca](https://lemmy.ca/post/15758963) and [post on endlesstalk.org](https://endlesstalk.org/post/23521063). The background to those posts is that I was running a fake lemmy community ([best viewed from here](https://lemmy.ml/c/tails@lemmon.website)), that was using a basic ActivityPub server to federate comments and votes, and I could tell from that that those instances (among others) were duplicating everything.

I saw it first with lemmy.world when they upgraded to 0.19.3, and my dumb AutoMod pinged my phone 4 times to tell me about the same new post (I mentioned it to the admins [in this comment](https://lemmy.world/comment/8115704)).

Outside of my server, you can also see duplicate activity trip other recipients up. One place is Lemmy modlogs. For example, [this modlog](https://endlesstalk.org/modlog/7376) shows me manually restoring a comment that the AutoMod removed. I did this with my own fair hand, using the lemmy-ui, so I know that whilst I didn't do the same thing twice, activity was sent twice to endlesstalk.org about it. Another is PieFed. They've tightened up their ability to filter out duplicates now, but - if they've not been deleted since - you can still see what happened [here](https://piefed.social/post/78174) and [here](https://piefed.social/post/78175), as well as [here](https://piefed.social/post/78017) and [here](https://piefed.social/post/78018) (the originals weren't updated, btw). In both circumstances (modlogs and piefed), I'm guessing it's hit-and-miss because it depends on how much time there was between the original activity and its duplicate. 

It's entirely possible that is down to instance mis-configuration (in which, quite a few instances are making the same mistake, which is a problem in itself). It's only slightly vague suggestions from admins that the software itself is at fault. That's why I'd prefer it was them making this Issue instead of me, but I've been requested to do it, so here it is.

 

 

 

### Steps to Reproduce

1. Be a server admin, using software that lets you monitor incoming activity
2. Subscribe to a community on an affected instance like lemmy.world
3. Generate some activity using an actor unrelated to your own server, and see how many times the instance Announces it

### Technical Details

(I can't you much here, for the aforementioned I'm-not-running-Lemmy reasons)

### Version

0.19.3

### Lemmy Instance URL

lemmy.world

**Comment by Nutomic** [comment] 2024-04-09 09:51
This seems like a bug in Lemmy so youre definitely right to report it here. Doesnt matter if you observe it from another platform. It looks like all requests go to `/inbox` and you respond with status 200 without producing error codes or timeouts, so it doesnt look like a problem on your side.

@phiresky Do you have any idea about this? All I can think of is that theres more than one federation worker active for a single target instance, but the code looks correct.

**Comment by phiresky** [comment] 2024-04-09 10:57
I know that lemmy.world definitely had a misconfiguration for a bit where they had multiple instances of Lemmy running without the appropriate -federation-worker flags set (since those where not required before 0.19). 

If this issue doesn't happen always and for every instance then it's likely a misconfiguration in those instances. 

That doesn't mean we shouldn't do something to improve the situation. For example we could add a heuristic to the federation workers that detects and logs an error when the federation_queue_state table has been updated by someone else which would mean overlapping federation workers running.

The best solution would be a horizontal scaling method that does not require manual configuration of federation instance ranges but I can't think of a way to do that without huge complexity.

**Comment by Nutomic** [comment] 2024-04-09 11:22
The bug also seems to happen for instances that are running only a single Lemmy backend, eg [mander.xyz](https://lemmy.ca/comment/7467127).

**Comment by Nothing4You** [comment] 2024-04-10 10:19
I've seen duplicate activities on Lemmy <-> Lemmy before, it seems unlikely to be related to the software on the receiving side.

**Comment by phiresky** [comment] 2024-04-10 12:32
It would be good to get a reproduction with an instance that someone actually controls because otherwise it's hard to say whether there is a misconfiguration or not and to get the relevant logs / db entries (which are on the sending side)

**Comment by phiresky** [comment] 2024-04-10 12:34
> it seems unlikely to be related to the software on the receiving side.

It might be relevant since in general every actor has their own inbox, and the merging of these inboxes into a single site-wide inbox might not work correctly depending on how other end presents their inboxes

**Comment by Nutomic** [comment] 2024-04-11 08:36
> It might be relevant since in general every actor has their own inbox, and the merging of these inboxes into a single site-wide inbox might not work correctly depending on how other end presents their inboxes. If lemmy sees inboxes as separate then it may send events to multiple inboxes

I also thought about that, but based on the logs posted by @freamon, all activities were sent to `/inbox`. So I dont see any way for deduplication to fail. Also all inbox requests receive response status 200, so it cant be retries due to errors.

I messaged the admin of mander.xyz to help investigate, but havent received a response so far.

**Comment by freamon** [comment] 2024-04-26 14:31
Some good news / bad news for you - lemmy.ml is duplicating activities. I subscribed to asklemmy@lemmy.ml from a test Lemmy instance tunnelled through via ngrok, so I could screenshot the 'inspect' window - you can see a pattern of 200 OK, 400 Bad Request for every activity. I've included two images to demonstrate that they are the same activity.

![Lemmy0 19 3 on DESKTOP-2B5PCTI - Virtual Machine Connection 26_04_2024 15_15_59](https://github.com/LemmyNet/lemmy/assets/5073325/53608655-d1aa-4fdc-a4b3-dde8189df4a4)

![Lemmy0 19 3 on DESKTOP-2B5PCTI - Virtual Machine Connection 26_04_2024 15_16_24](https://github.com/LemmyNet/lemmy/assets/5073325/2ba2376d-9733-42c2-baa1-88cc056afbdf)

(I don't imagine it's a config issue for you guys, but LW [changed their config](https://lemmy.world/comment/9377435) to fix the problem when they were doing it)

**Comment by jlandahl** [comment] 2024-05-14 01:16
Note that the duplication has returned: https://lemmy.ml/comment/11010288

Anyone know if lemmy.world is testing that config change again or something?

**Comment by Nothing4You** [comment] 2024-05-14 01:21
@freamon brought this up in their matrix chat the other day and the answer was nothing changed on lemmy.world's end

**Comment by freamon** [comment] 2024-05-14 22:17
@jlandahl - LW had to reset a container, so you shouldn't be getting any more duplicate activity from them. It was the same with lemmy.ml incidentally - a few comments up I was saying that they were duplicating too, but then they reset as part of testing an upgrade to 0.19.4, and that stopped it. 

---

As a Issue that seems to start randomly, and is stopped by 'turning it off and on again', I suspect this will be a hard problem to solve. I'm also inferring a reluctance on the part of the admins of affected instances to provide data, so that adds a further complication.

I noticed when I was recording the video the other day (of which [this](https://imgur.com/a/lX0LPZk) is an excerpt), that there was a recurring pattern: 30 seconds of nothing, then a flood of activity, then back to 30 seconds of nothing, etc. I imagine this is by design, and my instance has to wait its turn to get a bunch in one, rather than get activities as they are created. It made me wonder whether 'version 1' of an activity was being generated but not actually sent, just queued up and stuck somewhere. Then Lemmy was generating 'version 2' because it thought the first version wasn't delivered successfully, and then both versions were being sent at the same time.

**Comment by Nutomic** [comment] 2024-05-15 08:55
To fix this we have to narrow down what exactly is causing the duplicate activities. My understanding is that the bug doesnt happen with the default ansible configuration, and affected instances have some different config. Some things worth trying on a test instance:

- Does the bug get triggered by running multiple Lemmy processes with `--disable-activity-sending`, `--disable-http-server` etc?
- Is the bug random and goes away after restarting Lemmy?
- Are all activities sent out multiple times, or only specific activity types?

**Comment by freamon** [comment] 2024-05-15 11:30
Yeah - restarting seems to fix it (at least from my perspective).

It's for all activities - anything a remote community might Announce, and - for my one local community - anything a user might send. 

(I just verified that last part by upvoting a random post on endlesstalk.org. You can tell how broke that instance is anyway by how out-of-sync it is with votes generally (e.g. compare https://endlesstalk.org/post/34649989 with the fedi-link), but the upvote I gave for a post on !tails@lemmon.website was sent to me a sweet 7 times. There's some info [here](https://endlesstalk.org/post/23521063) about his container setup, with a comment that also suggests that a restart fixes it.)

**Comment by Nutomic** [comment] 2024-05-20 10:20
I added some extra logging in https://github.com/LemmyNet/lemmy/pull/4726 to figure out where the problem is coming from. Once that is merged and released, run Lemmy with `RUST_LOG="warn,lemmy_server=debug` or `RUST_LOG="warn,lemmy_server=trace` (preferably with a separate process only for federation). Then see if any of these log lines are printed more than once, and report them here.

**Comment by Nutomic** [comment] 2024-05-27 11:21
@MrKaplan-lw Yes that definitely looks like there is more than one worker active. So far its not clear where exactly in the code this is caused, but maybe my changes in https://github.com/LemmyNet/lemmy/pull/4733 and further testing/refactoring will help.

Does this jumping between different states happen only for a single remote instance at a time, or are multiple/all of them affected at once?

**Comment by Nutomic** [comment] 2024-05-28 09:23
I think that is normal as Lemmy processes a batch of outgoing activities, then goes to sleep for 30s, new activities get generated and then sent out after the sleep is over.

**Comment by Nutomic** [comment] 2024-05-29 09:04
That particular logic was removed [here](https://github.com/LemmyNet/lemmy/pull/4733/files#r1609799891). So if were lucky the problem is already fixed in 0.19.4-rc.3.

**Comment by phiresky** [comment] 2024-05-29 10:12
That error is actually an example why that loop you removed is necessary, because the init_and_loop function exits the loop and returns an error when it errors unexpectedly. So when this kind of error happens, the worker exits the loop, and the loop with "task exited, restarting:" restarts the task.

At least, that's how it should work. I don't know why it's sending activities twice and this is a good hint, but logically your change isn't right

**Comment by phiresky** [comment] 2024-05-29 10:22
I think I know what the issue is!

When there is some internal error (e.g. database pool full) during a query, that query throws.

If this throw happens within an InstanceWorker, the worker exits its loop, that is logged and is restarted by the CancellableTask it is wrapped in.

If this throw happens within the SendManager, the SendManager exits and is restarted by the CancellableTask it is wrapped in. The SendManager then starts creating all the InstanceWorkers for each instance.

The problem is that when the SendManager dies due to this, it does not cleanup all the InstanceWorkers it has created. So the InstanceWorkers of the old SendManager are still running (orphaned) and are never cancelled / cleaned up.


This CancellableTask restart code was wrongly removed here: https://github.com/LemmyNet/lemmy/pull/4733/files/451d1fd24fdabda6556b044fc3e601ccea05a6e3#diff-899cee276e9713c57bb5ff473ec9bd72df7831111780c0d2de7a543544667b7e and needs to be readded in some form - without it neither SendManager nor InstanceWorker will restart when they fail which will cause federation to stop working randomly

**Closed** 2024-05-30 10:45 UTC
Labels: bug, area: federation
