### ISSUE TITLE
Unsubscribe from own posts

### ISSUE THREAD

**Issue by PrincessMiki** [LemmyNet/lemmy#2646] opened 2023-01-06 15:11 UTC
### Is your proposal related to a problem?

If a post blows up and gets like 50+ replies, I don't have time to read all 50 replies that fill up my inbox. But i have another active posts that gets like 2 replies. If i mark all as read in my inbox, i miss the 2 replies to my small post. 

### Describe the solution you'd like

A good solution would be unsubscribing to individual posts. Currently, afaik, for OP to subscribe to their own posts, they have to delete their own post. But some people might want to read all 50 replies.

### Describe alternatives you've considered

Using reddit since it has an unsubscribe button

**Comment by binary3141** [comment] 2023-01-07 14:51
lemmy could have unsubscribe button for OP and who replied, and let who replied subscribe all new replied in the same post.

**Comment by dessalines** [comment] 2023-01-09 23:21
You don't "subscribe" to posts in reddit or lemmy, only communities/subreddits. I think this is called "mute inbox replies for posts", which might be doable.

**Comment by dessalines** [comment] 2023-02-16 18:42
Dupe of #833

**Closed by dessalines** 2023-02-16 18:42 UTC
Labels: enhancement
