### ISSUE TITLE
Require account to view content

### ISSUE THREAD

**Issue by bjoern-tantau** [LemmyNet/lemmy#3546] opened 2023-07-08 16:27 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

I have launched my own instance so that I can control myself which instances get blocked and which remain. But now I get of course picked up by Google and everyone can infer what communities I've subscribed to.

### Describe the solution you'd like.

I'd like the ability to restrict every page on my instance (apart from what's needed for federation) to logged in users. If a non-logged-in user visits the site they should be redirected to the login page.

### Describe alternatives you've considered.

At least the ability to customise the robots.txt would be nice, to ward off search engines. I'll take a look at docker to see if I can fix that there.

### Additional context

This is similar to #1963 but I want to take it one step further. Blocking every page but the login might even be easier to achieve as a short-term solution.

**Comment by wereii** [comment] 2023-07-09 17:54
For now you can add this on top of the first `location` block in nginx.conf to stop search indexers.

```nginx
location = /robots.txt {
  add_header Content-Type text/plain always;
  return 200 "User-agent: *\nDisallow: /\n";
}
```

**Comment by bjoern-tantau** [comment] 2023-07-09 18:15
Thanks. I'm actually using Apache as a proxy, so I put

        <Location "/robots.txt">
                ProxyPass !
        </Location>

Under the proxy for Lemmy and put the desired robots.txt in my document root.

**Comment by ubergeek77** [comment] 2023-07-09 18:20
I don't know that Lemmy will ever support this feature, and I also don't know what the closest alternative for Apache would be, but you might be able to stick an auth portal in front of all the UI routes, and leave the `/api`/`well-known`/etc routes open for federation.

If you use Cloudflare, you can set up Zero Trust to do this. For a self hosted solution, if you used Caddy it would be easiest to use this:

https://github.com/greenpau/caddy-security

For Apache, I'm not sure. Keycloak maybe?

If you're just trying to stop search results, the robots method would be best. For this scorched earth method of actually blocking the UI, it would be a lot of tinkering, but it can probably be done.

**Comment by Nutomic** [comment] 2023-10-02 14:21
Basically a duplicate of https://github.com/LemmyNet/lemmy/issues/1963. If you want to completely disable public access, do it via nginx or similar as already explained.

**Closed by Nutomic** 2023-10-02 14:21 UTC
Labels: enhancement, area: privacy, area: administration
