### ISSUE TITLE
Limit number of posts from popular communities on "All"

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2230] opened 2022-04-19 16:40 UTC
Some users dislike that the "All" page is too much dominated by lemmygrad, and specifically genzedong. I think they have a point, because at this time, 10 out of 20 posts on the first page of All are from genzedong community. This gets annoying for anyone who is not interested in the particular community, and makes it harder to discover new communities.

[Here is a recent discussion about this](https://lemmy.ml/post/233632). 

One solution i can think of is to limit the number of posts from a particular community shown on All. So for example it would list a maximum of 2 posts from each community.

**Comment by dessalines** [comment] 2022-04-19 19:23
The tough part is figuring out how to do this in SQL. I've posted a question on stackoverflow to see if anyone knows how to do this, or what this should be called.

https://stackoverflow.com/questions/71930247/how-to-limit-the-number-of-joined-items-in-sql-to-populate-a-front-page-of-many

**Comment by Nutomic** [comment] 2022-05-03 12:00
There is [currently a discussion on Lemmy](https://lemmy.ml/post/252002) about a similar issue, that the local/all view shouldnt include many posts from the same user in a row. I think that makes a lot of sense, and posts from the same user/community should both be limited.

**Comment by dessalines** [comment] 2023-02-13 19:46
Duplicate of #1026

**Closed by dessalines** 2023-02-13 19:46 UTC
Labels: enhancement
