### ISSUE TITLE
an ''Avatar'' for the communities and a reform to the categorization of the communities

### ISSUE THREAD

**Issue by MaddRaccoon** [LemmyNet/lemmy#760] opened 2020-06-01 20:52 UTC
So I think having an option to put an ''Avatar'' for a community would help with visibility because if you search for a precise community it may blend with all the other since it is all text, so an Icon for a community could make it easier to find a particular community.

Also, the categorization of communities is pretty vague and if there would be a sort of reform to make it more precise, it could help to find a particular community. While some of the categories are fine like: ''movie'' ''Programming/Software'' etc. other like: ''politic'' ''Society'' and ''discussion'' are really vague.

PS: first time ever using Github so that why it might seem weird or different

**Comment by dessalines** [comment] 2020-06-01 21:14
I'm wondering if we should also add instance avatars, as well as instance and community banners?

**Comment by dessalines** [comment] 2020-07-08 21:16
Dupe of #899

**Closed by dessalines** 2020-07-08 21:16 UTC
Labels: duplicate, enhancement
