### ISSUE TITLE
[Bug]: local links

### ISSUE THREAD

**Issue by snan** [LemmyNet/lemmy#3261] opened 2023-06-22 09:31 UTC
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

On https://lemmy.world/comment/434103 I linked to /multiroll intending to link to https://idiomdrottning.org/multiroll (local / relative to my instance) but as the post got copied over to lemmy.world, the link broke.

### Steps to Reproduce

Link to a /relative-path on one instance commenting on another instance.

### Technical Details

I was on Pleroma and they were on Lemmy I guess.

### Version

🤷🏻‍♀️ 

### Lemmy Instance URL

lemmy.world

**Comment by marbovo** [comment] 2023-06-22 13:20
I think this is a major problem of the federation, not just broken links but being thrown out of our instances into another one where we cannot interact because we are not logged in there.

All federation links should be localized to the local instance of the user

**Comment by necropola** [comment] 2023-06-24 19:56
Duplicate of #2987 and/or #1101

**Closed** 2023-06-24 20:00 UTC
Labels: bug
