### ISSUE TITLE
Unable to follow lemmy community from streams

### ISSUE THREAD

**Issue by macgirvin** [LemmyNet/lemmy#2744] opened 2023-02-19 00:45 UTC
### Issue Summary

Follow requests from streams are rejected with a 400 error and no obvious text description. These activities work elsewhere in the fediverse. This software does support recent versions of http-signatures w/r/t (created) and (expires); which was found to be an issue in some related projects. 

### Steps to Reproduce

1. From streams, follow somebody on lemmy. 
2. Message never arrives. Local logs report 400 error with no error text

### Technical details

Activity: 

```
{
  "@context":[
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    "https://www.w3.org/ns/did/v1",
    "https://w3id.org/security/data-integrity/v1",
    {
      "nomad":"https://unfediverse.com/apschema#",
      "toot":"http://joinmastodon.org/ns#",
      "schema":"http://schema.org#",
      "litepub":"http://litepub.social/ns#",
      "sm":"http://smithereen.software/ns#",
      "fep":"https://codeberg.org/fediverse/fep#",
      "manuallyApprovesFollowers":"as:manuallyApprovesFollowers",
      "oauthRegistrationEndpoint":"litepub:oauthRegistrationEndpoint",
      "sensitive":"as:sensitive",
      "movedTo":"as:movedTo",
      "alsoKnownAs":"as:alsoKnownAs",
      "EmojiReact":"as:EmojiReact",
      "PropertyValue":"schema:PropertyValue",
      "value":"schema:value",
      "discoverable":"toot:discoverable",
      "wall":"sm:wall",
      "capabilities":"litepub:capabilities",
      "acceptsJoins":"litepub:acceptsJoins",
      "Hashtag":"as:Hashtag",
      "canReply":"toot:canReply",
      "approval":"toot:approval",
      "Identity":"fep:Identity",
      "isContainedConversation":"nomad:isContainedConversation",
      "conversation":"nomad:conversation",
      "commentPolicy":"nomad:commentPolicy",
      "eventRepeat":"nomad:eventRepeat",
      "emojiReaction":"nomad:emojiReaction",
      "expires":"nomad:expires",
      "directMessage":"nomad:directMessage",
      "Category":"nomad:Category",
      "replyTo":"nomad:replyTo",
      "copiedTo":"nomad:copiedTo",
      "canSearch":"nomad:canSearch",
      "searchContent":"nomad:searchContent",
      "searchTags":"nomad:searchTags"
    }
  ],
  "id":"https://unfediverse.com/follow/372",
  "type":"Follow",
  "actor":"https://unfediverse.com/channel/lem",
  "object":"https://lemmy.ml/c/green",
  "to":[
    "https://lemmy.ml/c/green"
  ],
  "cc":[

  ],
  "signature":{
    "type":"RsaSignature2017",
    "nonce":"56ec8c4391d625539ef50d8ec077e0c3706b363bc9af9d4aa1dab0f00bd106d8",
    "creator":"https://unfediverse.com/channel/lem",
    "created":"2023-02-19T00:21:16Z",
    "signatureValue":"qWBaMyQJjzd9eWi3Zbq/tQ3/d2PEn0L437yMsTAiN/nWBd2U1h46OtwMA88dfzNaTBWJUzxkUviY4dFfHpwHjKng8SJlOV1zSa+/jOv7aEUzFB+sfJct4XGOJ3wLoKA9wk+KKO0KEEuh9CiOKcfLjHYjKAmbeBgcylV3VaKhj1VXuVFzt3jk00j0+eL5TN46j/sbOWzFYHlLFnLPyr1Sc+uEMPPf77IT8vndyMaLfiXCrS/dw6Q8hmxLBaRVoftxa0MvbPkhHZ3w0qLIDDw44Gspi4Jtv1iRNeU9SdhGoJHp9iw3BffOS7Z2s1s2XDMMcLPwqrOjDjoV1ji2Fv16wrV+JnAkvJ9GlH6GJz7rb47GB7v9wCpdVh3LazkrielA/wFTWakPjdvUwNC2QFgFH271KBJFrn58aFLcwNCKmbSA1EgOYa7P4SkNIh85EcgP20NHpeNFr1C9Ck85DrwuEmGSCB7jtTsnrqgQyd4bqUixWYL5QfciT19aoGc5OglB9VvxP94HSdRdD0emVStcIRtpSKXvO1gSeTAG42sCcKQszvJe1Erkgi3OvbJbnXimmy77zObGN60T8Qrhv31i9ZFATsQmxGeP1gYOIemCiJFNLHU+BomxvWJJuuyzaEqS6kbVtlNOswTGdz43dIvWd5fTthk0q4Wyjb8Pchs57Xs="
  }
}
```

Site log entry:

```

2023-02-19T00:21:21Z:LOG_INFO:123eb47e0e:Url.php:442:post: error: https://lemmy.ml/c/green/inbox:
2023-02-19T00:21:21Z:LOG_INFO:123eb47e0e:Url.php:443:post: debug: 2023-02-19 00:21:21<br>^M
url: https://lemmy.ml/c/green/inbox<br>^M
http_code: 400<br>^M
error_code: <br>^M
error_string: <br>^M
content-type: text/plain<br>^M
request-header: POST /c/green/inbox HTTP/1.1^M
Host: lemmy.ml^M
User-Agent: Mozilla/5.0 (compatible)^M
Accept: */*^M
Accept-Encoding: deflate, gzip^M
Content-Type: application/ld+json; profile="https://www.w3.org/ns/activitystreams"^M
Date: Sun, 19 Feb 2023 00:21:20 GMT^M
Digest: SHA-256=2oGZMydxLsT8r9Vt612Hsp6SDVBuihvs3ZhosMP/jlU=^M
Signature: keyId="https://unfediverse.com/channel/lem",algorithm="rsa-sha256",headers="content-type date digest host (request-target)",signature="KsEU4Ecr6gz+FeVfmTGjvOMdyQ990uZjZk3ldxHONPSMOnkPYoB/limuC7dOzv13WKcXyLguN8iq2jm8A1Z8DCEwGKQNCHU7asfPIxbmcdGyw63PkD1XBmdMzDjJDak7bNJgsap9x5FKWwl/J7Q2eLSxni0Yl/m+pOkUdW7QT8MovYp1XEVbDxip2i5Y8z5rvsX24LqzuQ9VB7YR758rLUdB527D4smeAcAHVqidVehkn/grqlG6F14DNuJsiMLRCgf04n75hjlCp8YKfQITYIeT9pPl9xyCAkh6601JDHGs4tD9UB3OOV4eOVNmyXW/OwZs2WXF/YYy85b96j1O+A/Fs56cDtVp8qTh/QuQrPC/jFwbb2RgM/4bJ9Bkbn4Bc974mLNVFtuOl0Y/Y9QoFdzK5qvdmxnb8fWdtAkb5/x5KvJ9gfcxLtOshtDPRXSKLXUFxb9y34JtbL2yK99BY1BCaI/+DEz4xP9vUF3udQjZ09teC/vpmEW2vSu6mjw09Q62VHhvI9nAq2HnPEx90Xb6tlXgOsLbWeMvnjUHzR1vala9cPHAre/lEIkDZMdHOpU9alItLe/eHz+MrGK86SbFKrWU5FX8Lsv7MV++Je6TZpMvBgU0NQIe8UKawG7SSIVzx5mcs7P7eGEpuXzTQ82k8ybXt2XGA+pT87UQ4is="^M
Content-Length: 2451^M
Expect: 100-continue^M
^M
<br>^M
```

**Comment by Nutomic** [comment] 2023-02-19 13:27
Hmm this is odd. There is an error in the logs which indicates that it gets parsed as the wrong activity type, but I have no idea why. The json parses fine, and older HTTP signature draft versions without (created) and (signed) fields are supported for receiving. One thing you could try is delivering to shared inbox instead. Do other activities such as `Create/Comment` work?

**Comment by macgirvin** [comment] 2023-02-20 03:04
Haven't tried create/comment. I started with Follow to get some things locally to comment on. My schedule is hectic but I'll give the shared inbox a try and will let you know.

**Comment by macgirvin** [comment] 2023-02-20 18:04
FWIW, I got the same result (400 response) from the shared inbox.

**Comment by macgirvin** [comment] 2023-02-20 18:18
Incidentally, was the "wrong activity type" a Join perchance? We send both a Follow and a Join for groups since we don't know which of the dozen fediverse group federation mechanisms they are using - the ActivityStreams spec uses Join in their groups example but a number of projects require a Follow. Usually the Follow is the first one that arrives - by maybe a few seconds. We expect one of these to get rejected as an unsuitable type depending on your group federation model. In this case both were bounced.

**Comment by Nutomic** [comment] 2023-02-23 03:03
Im not sure because its dropped out of the logs now. I already checked that your `Follow` and `Person` parse fine, so the problem is probably not related to JSON. Do you have a test server where I could register and try some things?

**Comment by macgirvin** [comment] 2023-02-23 07:44
Yeah, I've just set https://rebble.net to register-with-approval. I'm on the other side of the world but I'll approve you in short order. Consider anything on that site to be throw-away. You'll want to look for the Connections app in the menu. To send a follow, put the webfinger address in the text box on the left. This will  take you to the connection editor. To remove an unsuccessful  connection and start over, delete the connection from a dropdown at the top of that page.

**Comment by Nutomic** [comment] 2023-02-23 16:11
I tried that connection search a couple of actors which are available over webfinger, including `green@lemmy.ml` and other variatons. No matter what I do there are no results.

**Comment by macgirvin** [comment] 2023-02-23 19:16
![menu](https://user-images.githubusercontent.com/95073331/221007790-5906aa84-4a45-4727-987d-dfda6c93612f.png)


![add-connection](https://user-images.githubusercontent.com/95073331/221006660-a9d6af31-6040-4759-aee8-1426e6a28451.png)

**Comment by Nutomic** [comment] 2023-02-24 08:11
Thanks, I use a narrow browser window and that dialog on the left wasnt shown at all.

**Comment by macgirvin** [comment] 2023-02-24 08:26
When the sidebar is hidden there's an arrow pinned to the navbar which will toggle it into view.

**Comment by Nutomic** [comment] 2023-02-24 08:49
![Screenshot 2023-02-24 at 17-48-55 Connections Snuffleupagus](https://user-images.githubusercontent.com/1044450/221134079-308201d5-439c-4367-84da-a5e42cd1e321.png)

That arrow seems to be missing for me (Firefox).

**Comment by Nutomic** [comment] 2023-02-24 13:04
Alright the `Follow` Im seeing looks a bit different, with actor as a nested object instead of a plain link. That is currently not supported. Strangely enough I was able to follow a user (`nutomic@ds9.lemmy.ml`) without problems, even though I dont see any difference in the json or in our code.

**Comment by macgirvin** [comment] 2023-02-24 19:56
That's something I can sort out. We started off sending objects, but I had to change that to a URL for some other project back in 2018 and don't recall changing it back to sending an object. So that's a possible regression on our side, but it is totally legal ActivityStreams so I'd encourage supporting it - as well as arrays of authors and urls and other objects if you don't already; as we do see all of these in the wild. Anyway, thanks for the assistance. The arrow is just above the "Buscar" button in your screenshot. Looks like I also need to make the side panel navigation more obvious. 

Since I can work around this, I would close the issue, but since there's still a bug from my perspective, I'll let you decide to keep it open or not.

**Comment by macgirvin** [comment] 2023-02-24 20:22
Update: I actually cannot find that in the code or in my logs. We *are* sending an object for Undo/Follow, which I've been sending to reset and start over. I'll fix that right now - but it appears we are sending a URL in the original Follow activity. If you can come up with a snippet of what you're seeing from your logs I'll do my best to track it down.

**Comment by Nutomic** [comment] 2023-04-04 19:53
I tested it again now, Lemmy receives the Follow as expected and successfully sends back an Accept activity. Maybe some problem was fixed when I recently rewrote the federation code. However streams still shows a red warning icon for the connection, so that seems like there is still a problem?

![Screenshot_20230404_150954](https://user-images.githubusercontent.com/1044450/229802015-567376d1-da74-40f2-a9f6-636a7296e89d.png)


```json
{
  "id":"https://ds9.lemmy.ml/activities/accept/8cde53de-67ac-472f-9715-dbe8b4cce9fb",
  "type":"Accept",
  "actor":"https://ds9.lemmy.ml/c/main",
  "object":{
    "id":"https://rebble.net/follow/106",
    "type":"Follow",
    "actor":"https://rebble.net/channel/nutomic",
    "object":"https://ds9.lemmy.ml/c/main"
  },
  "@context":[
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    {
      "pt":"https://joinpeertube.org/ns#",
      "sc":"http://schema.org/",
      "lemmy":"https://join-lemmy.org/ns#",
      "expires":"as:endTime",
      "litepub":"http://litepub.social/ns#",
      "language":"sc:inLanguage",
      "stickied":"lemmy:stickied",
      "sensitive":"as:sensitive",
      "identifier":"sc:identifier",
      "moderators":{
        "@id":"lemmy:moderators",
        "@type":"@id"
      },
      "removeData":"lemmy:removeData",
      "ChatMessage":"litepub:ChatMessage",
      "matrixUserId":"lemmy:matrixUserId",
      "distinguished":"lemmy:distinguished",
      "commentsEnabled":"pt:commentsEnabled",
      "postingRestrictedToMods":"lemmy:postingRestrictedToMods"
    }
  ]
}
```

**Comment by macgirvin** [comment] 2023-04-05 20:27
From a different actor on the same site, I'm still seeing persistent 400 errors on all deliveries. I just tried both green@lemmy.ml and the actor shown just above on ds9. And all of these deliveries failed. 

The red indicator generally means we didn't get an Accept back. 
I looked at the Accept you referred to above in the logs and a couple of things stand out. The first isn't necessarily an issue, but the JSON is being logged with a double linebreak. For example:

```
{

  "@context": channel/nutomic",

    "object": "https://ds9.lemmy.ml/c/main",

    "type": "Follow",

    "id": "https://rebble.net/follow/101"

  },
```
etc... This isn't necessarily an issue, but it might mean there's a line terminator discrepancy somewhere. I'm logging the pretty-printed json, so some mangling of the input text has taken place - as most activities arrive with "compressed json", but I don't see this on any other activities from any other source so it seems that something might be off with the line endings on the received activity. 

The other thing worth noting is that there is no to/cc/audience in the activity, so it didn't get delivered to anybody. This is why the connection didn't show up as accepted.

**Comment by Nutomic** [comment] 2023-04-06 20:08
Well Mastodon also sends Follow activities without any to or cc, so based on that it shouldnt be a problem. Strings are all UTF-8 and whitespace should be irrelevant in JSON. For your activity above, the following response was sent:
```json
{
  "id":"https://ds9.lemmy.ml/activities/accept/b111c3ea-ee83-459e-9cfd-3d52c2c504d8",
  "type":"Accept",
  "actor":"https://ds9.lemmy.ml/c/main",
  "object":{
    "id":"https://rebble.net/follow/101",
    "type":"Follow",
    "actor":"https://rebble.net/channel/nutomic",
    "object":"https://ds9.lemmy.ml/c/main"
  },
  "@context":[
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    {
      "pt":"https://joinpeertube.org/ns#",
      "sc":"http://schema.org/",
      "lemmy":"https://join-lemmy.org/ns#",
      "expires":"as:endTime",
      "litepub":"http://litepub.social/ns#",
      "language":"sc:inLanguage",
      "stickied":"lemmy:stickied",
      "sensitive":"as:sensitive",
      "identifier":"sc:identifier",
      "moderators":{
        "@id":"lemmy:moderators",
        "@type":"@id"
      },
      "removeData":"lemmy:removeData",
      "ChatMessage":"litepub:ChatMessage",
      "matrixUserId":"lemmy:matrixUserId",
      "distinguished":"lemmy:distinguished",
      "commentsEnabled":"pt:commentsEnabled",
      "postingRestrictedToMods":"lemmy:postingRestrictedToMods"
    }
  ]
}
```

**Comment by macgirvin** [comment] 2023-04-23 04:07
Update - sorry for the delay. I've just added code specifically to handle these activities when there are no delivery recipients. It was mentioned that Mastodon doesn't provide them either. We do accept deliveries to the actor's inbox with no to/cc/etc., because it could be a bcc. But for the sharedInbox we need to dig around and try and figure out who to deliver it to and in this case, lemmy didn't tell us directly, so we have to look for very specific type/obj combinations and then see if one of our channels is in one of the fields - which varies depending on the type/obj. Don't know how you do it, but this isn't an elegant and scalable workflow. I would suggest (maybe?) sending these straight to the actor's inbox unless there is a strong reason not to. 

The issue can be closed.

**Comment by Nutomic** [comment] 2023-04-23 21:32
Alright I added the `to` field back in for all follow related activities. Hopefully you can remove your compatiblity code once that is released.

Is federation between Streams and Lemmy working fine now?

**Comment by macgirvin** [comment] 2023-04-24 06:08
I haven't looked at any other activities yet - but likes probably won't work if you're also sending them to the sharedInbox. 

If you send them to my personal inbox you're sending them to somebody - with or without to/cc recipients. This is how bcc works. It's OK for posts to your personal inbox to not have 'to' and 'cc' fields. 

The sharedInbox is different. It is a bulk delivery endpoint and gets its instructions about where to deliver from the to/cc fields - and it works very poorly (if at all) with bcc's. If the to/cc addressing fields don't exist, you've literally sent the activity to nobody.

So I'd like to turn the question around. Is sending these activities to my inbox (not the sharedInbox) a problem for you? You'll need to support personal inboxes anyway because the sharedInbox is optional. What would happen if I removed it?

**Comment by Nutomic** [comment] 2023-04-24 19:54
Lemmy doesnt distinguish between private inbox or shared inbox, its parsed exactly the same way. For the like/dislike Im not even sure who they should be addressed to, probably the comment author or the community? Anyway the community is included in `audience`. Lemmy handles these by resolving the object and going from there.

**Closed** 2023-04-24 21:19 UTC
Labels: bug, federation

**Comment by macgirvin** [comment] 2023-04-25 21:38
Please review section 7 of the ActvityPub specification. Since I do not own the object in the audience property, I am not permitted to deliver it according to section 7.1.2. According to 7.1.3 this makes it your responsibility to deliver it to my personal inbox since the sharedInbox does not contain my actor in the to, bto, cc, bcc, and audience fields of the activity (per section 7.1).

**Comment by Nutomic** [comment] 2023-04-25 22:16
We always send the `audience` field, although to a group and not a collection like described in [FEP-1b12](https://codeberg.org/fediverse/fep/src/branch/main/feps/fep-1b12.md).

[Here is an example](https://github.com/LemmyNet/lemmy/blob/main/crates/apub/assets/lemmy/activities/create_or_update/create_page.json)
