### ISSUE TITLE
Add the ability to create personal lists of subscribed communities

### ISSUE THREAD

**Issue by ducula** [LemmyNet/lemmy#1524] opened 2021-03-27 18:18 UTC
When subscribed to a large number of communities, it may be useful to group related communities together into lists that can be previewed individually, akin to the lists feature in Mastodon.

**Comment by dessalines** [comment] 2021-03-29 17:28
I'm up for suggestions on the best way to do community groupings. I think I'd prefer this be done as shareable urls like reddit: https://www.reddit.com/r/NoStupidQuestions+explainlikeimfive/ .

Then possibly your right sidebar, maybe above `Subscribed communities`, would list your saved multi-communities? And when viewing a multi-community, you could have the option to save that to your profile.

**Comment by dessalines** [comment] 2021-03-30 02:20
Realized this is a dupe of #818

**Closed by dessalines** 2021-03-30 02:20 UTC
Labels: enhancement
