### ISSUE TITLE
[Bug]: Upvotes no longer associated with my account (0.19.0-rc8 lemmy.ml)

### ISSUE THREAD

**Issue by Atemu** [LemmyNet/lemmy#4208] opened 2023-11-28 16:04 UTC
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When I look into my post/comment history or posts/comments of others I have upvoted, they have the same amount of votes as before but it's as if I didn't vote on any of them anymore.

Not sure whether this is a BE or UI issue but it smells BE.

### Steps to Reproduce

1. Log into Lemmy.ml account after update
2. Look at your posts/comments

### Technical Details

Firefox on macOS

### Version

0.19.0-rc8

### Lemmy Instance URL

lemmy.ml

**Comment by dessalines** [comment] 2023-11-28 21:31
Its a front end issue, but its proving difficult to reproduce. Dupe of https://github.com/LemmyNet/lemmy-ui/issues/2243

**Closed by dessalines** 2023-11-28 21:31 UTC
Labels: bug

**Comment by Atemu** [comment] 2023-11-28 21:32
Interestingly, I can no longer repro.
