### ISSUE TITLE
instance-defined default communities for newly registered users

### ISSUE THREAD

**Issue by eiknat** [LemmyNet/lemmy#1309] opened 2020-12-04 23:16 UTC
### user stories:
- as a newly-registered user, i want to be automatically subscribed to some interesting or helpful communities to help me get started with lemmy.
- as a lemmy instance admin, i want to be able to control which communities are subscribed to by default so that i can help new users get started with lemmy and promote new and interesting communities.
- as a community moderator, i want to be able to opt-in to an admin setting my community as a default community so that i can help grow my community.

### proposed solution:
**add two new columns to the community_settings table:**
1. allow_as_default (boolean, default false, not null)
2. is_default_community (boolean, default false, not null)

**allow_as_default details:**
- opt-in.
- only community moderators may change this setting, an admin (unless they are also a moderator of the community) would not be allowed to change this setting.
- setting this to false while a community is a default community, would also set is_default_community to false.

**is_default_community details:**
- editable only by instance admins
- communities set as default would automatically subscribe newly-registered users to the community.
- not retroactive, affects only new registrations.

**endpoints:**
GET /api/v1/community/default
- returns the current list of default communities
- no authentication necessary

POST /api/v1/community/default?id=<community_id>&is_default=<false/true>
- updates a single community's is_default_community boolean
- returns error if the authenticated user is not an admin
- returns error if the community has allow_as_default set to false

**UI:**
- add allow_as_default to the current community setting area
- TBD

**additional notes:**
- removing or deleting a community should automatically remove it as a default

### questions:
- what, if any modlog entries should be generated?
- any federation considerations or should this be a completely local feature? (for an initial implementation, it should be)

**Comment by Nutomic** [comment] 2020-12-07 12:16
>as a community moderator, i want to be able to opt-in to an admin setting my community as a default community so that i can help grow my community.

This makes it overly complicated. Its enough to talk with the admins if mods dont agree to being a default community. But otherwise its a good suggestion!

>any federation considerations or should this be a completely local feature? (for an initial implementation, it should be)

This feature can completely ignore federation, and set `is_default_community` for remote communities as well (so that new local users are subscribed to them).

**Comment by eiknat** [comment] 2020-12-07 22:25
> 
> 
> > as a community moderator, i want to be able to opt-in to an admin setting my community as a default community so that i can help grow my community.
> 
> This makes it overly complicated. Its enough to talk with the admins if mods dont agree to being a default community. But otherwise its a good suggestion!
> 
i see it as an "escape hatch" for community mods, but it can be left out and we can always add it later.

**Comment by Nutomic** [comment] 2022-03-14 20:27
Duplicate of https://github.com/LemmyNet/lemmy/issues/2068

**Closed by Nutomic** 2022-03-14 20:27 UTC
Labels: enhancement
