### ISSUE TITLE
Tag-driven onboarding guide/wizard for new users

### ISSUE THREAD

**Issue by rclabough** [LemmyNet/lemmy#2924] opened 2023-06-05 23:19 UTC
For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Is your proposal related to a problem?
Kind of, helping onboarding users and distribute them to other instances

### Describe the solution you'd like
I think Instance users should be able to add "tags" to their instances, easy one word tags that could be published to join-lemmy.org just like the name and description.  These could show up as [badges](https://getbootstrap.com/docs/4.0/components/badge/) on the card for each instance.

Then, to help users find other instances that they may be interested in, they could be asked what they are interested in, checking different tags, which would narrow down the list of instances that have those communities. 

This is a potential idea to help people feel like they're choosing where to join, rather than the giant list of instances that feels intimidating to them.  It may also help them feel like they belong more.

### Describe alternatives you've considered

Some sort of wizard-like onboarding process on join-lemmy.org would work, or a listing of communities already on the instances.  That is hard though because most will still go for the big instances already.

(Write your answer here.)

### Additional context

General worries,

* People like the concept of going to lemmy.ml, there would need to be some obvious thing that says "This is where you go to log in now".  
* Verbiage needs to be added that explains that they do not need to experience FOMO by joining another instance, that they can still access other content by joining other instances.  (It may be good to show the instances blocklist though, to show what they would in fact be missing)
* If they still went to lemmy.ml by accident, could there be a cookie stored or something that would redirect them back to their home instance?  This may also be a good idea when navigating around, like if I'm on my own instance and get directed to lemmy.ml and click subscribe, it would know to redirect me back to my home instance to subscribe.

This was just an idea I had, and it rambled a bit at the end.  You're doing great work here, I'm hoping to spark some inspiration even if this idea isn't taken directly, to help some of the onboarding woes.  On Reddit, the two biggest complaints I hear from people are 1) onboarding is difficult and instances are confusing and 2) Joining communities is difficult.  I think something like this would help both of those.

**Comment by Nutomic** [comment] 2023-06-05 23:27
The concept sounds good but who will implement it?

**Comment by dessalines** [comment] 2023-06-06 19:11
Dupe of https://github.com/LemmyNet/joinlemmy-site/issues/36

**Closed by dessalines** 2023-06-06 19:11 UTC
Labels: enhancement
