### ISSUE TITLE
[Bug]: Reports do not federate to community mods on federated instances

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy#4396] opened 2024-01-22 22:34 UTC
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

As described in [this comment](https://lemmygrad.ml/comment/3493330), if a user is a moderator of a community on a federated instance, reports on that community do not federate to the mod. In the example given a user from lemm.ee mods a community on lemmy.world and cannot receive reports from that community.

### Steps to Reproduce

1. Appoint a user from another instance as a moderator of a community on your local instance.
2. Report a post or comment in your community.
3. The non-local mod cannot see the report.

### Technical Details

n/a

### Version

BE 0.19.2 (lemm.ee), 0.18.5 (lemmy.world)

### Lemmy Instance URL

lemm.ee, lemmy.world

**Comment by Nothing4You** [comment] 2024-01-23 09:28
duplicate of #3781

**Closed** 2024-01-23 10:04 UTC
Labels: bug
