### ISSUE TITLE
[Bug]: Purging users or communities with 10k posts fail

### ISSUE THREAD

**Issue by kroese** [LemmyNet/lemmy#3718] opened 2023-07-24 23:04 UTC
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When trying to delete or ban a user with a few thousand posts, the postgres process will go to 100 percent CPU and stay there for hours until aborted. Essentially hanging the server. Same goes for trying to purge a community with a large amount of posts.

### Steps to Reproduce

1. Create user + community
2. Create 10.000 posts in community
3. Try to purge the user or the community
4. Postgress query never finishes

### Technical Details

Docker

### Version

0.18.3-rc2

**Comment by phiresky** [comment] 2023-07-24 23:41
duple of https://github.com/LemmyNet/lemmy/issues/3165 ?

**Comment by lionirdeadman** [comment] 2023-07-25 06:17
Closing as duplicate of https://github.com/LemmyNet/lemmy/issues/3165

**Closed by lionirdeadman** 2023-07-25 06:17 UTC
Labels: bug

**Comment by phiresky** [comment] 2023-07-25 09:37
That's true I guess. I think the discussions and possible fixes in that issue do include / fix cases without comments due to the site_aggregate updates. Maybe @RocketDerp can clarify whether their PR should also fix the case without comments.

**Comment by RocketDerp** [comment] 2023-07-25 19:00
> Create 10.000 posts in community

We have one report that says an account with only 352 comments ran into problems: https://github.com/LemmyNet/lemmy/issues/3649

My instance is getting incoming federation from every big community I could find. And it hasn't hung endlessly  on a delete in over 45 days. I think the local activity of the server plays a big role on site_aggregates contention given local additions of comments and posts trigger it into write operations on 1700 rows.

I don't think we have even looked  yet at vote triggers.
