### ISSUE TITLE
A way to link posts across instances

### ISSUE THREAD

**Issue by Dakkaron** [LemmyNet/lemmy#3259] opened 2023-06-22 08:59 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

I currently can't link a post/comment in a way that it works for different instances.

In the issue I will be talking about posts, but everything there also applies to comments in the same way.

Since the same post has a different ID on different instances, the only think I can link to is a post on a specific instance.

Say, I am an user on instance A. I create a post here, that lives on A/post/1234. On community B it is replicated on B/post/4321.

The only thing I can link to is A/post/1234. If now a user from instance B wants to follow my link, it will open on instance A, but they will not be able to comment or interact with that post on instance A with their account which currently lives on instance B.

So if they want to comment, they will then have to copy the title of the post and search for it in the search bar of instance B, which is super clunky.

### Describe the solution you'd like.

Have some sort of UUID for each post, so that this UUID can be linked. An UUID are unique enough that instances don't have to coordinate their creation.

This UUID would be added as an additional form of linking, so in the example above, the post might be reached by all of these URLs:

- A/post/1234
- B/post/4321
- A/post/0cc0dd96-4a8b-4fcd-98bd-93f2e3620446
- B/post/0cc0dd96-4a8b-4fcd-98bd-93f2e3620446

This way, I can then create a relative link in a comment, that just links to `/post/0cc0dd96-4a8b-4fcd-98bd-93f2e3620446`, and it will work both on instance A and B, taking me to `A/post/0cc0dd96-4a8b-4fcd-98bd-93f2e3620446` or `B/post/0cc0dd96-4a8b-4fcd-98bd-93f2e3620446` respectively. In either way, I will get the same post and be still on the instance where I have my account.

### Describe alternatives you've considered.

Another option would be to add the origin instance of the post/comment to the URL. That way, the post could be reached as follows:

- A/post/1234
- A/post/1234@A
- B/post/4321
- B/post/1234@A

This way, I can then create a relative link in a comment, that just links to `/post/1234@A`, and it will work both on instance A and B, taking me to `A/post/1234@A` or `B/post/1234@A` respectively. In either way, I will get the same post and be still on the instance where I have my account.

### Additional context

This should make it much easier to link between posts, thus allowing for users to stay "in the flow" more.

Edit: Thinking about it, the alternative way is probably the better option, since it follows the style of how other inter-instance links work in Lemmy, it is more human-readable and the links are shorter.

**Comment by WayneSheppard** [comment] 2023-06-23 13:54
I like the idea, I just complained about this yesterday.  But what would happen if I follow a link to a post in a community that my server doesn't subscribe to?  404?  I could see the server checking to see if the link exists, and rewriting the link if needed.  But this just complicates things.

**Comment by Dakkaron** [comment] 2023-06-23 15:05
Yeah, that's a general issue with e.g. communities and users. If you try to access `myinstance.org/c/notonmyinstance@anotherinstance.org`, then you will also get a 404.

What would be easily possible, though, would be to show a 404 page explaining that this post/comment/community/user isn't mirrored on the local instance and then gives the opportunity to either mirror it or link to the post/comment/community/user on the other instance.

So something like this:

    This post is not currently available on the current instance.
    Press this button (link that searches for the target community to download it locally) to make it available on the current instance, or follow this link (link to anotherinstance.org/notonmyinstance@anotherinstance.org) to view it on it's original instance.

**Comment by necropola** [comment] 2023-06-24 19:54
Duplicate of #2987 and/or #1101

**Comment by lionirdeadman** [comment] 2023-07-24 04:36
Duplicate of https://github.com/LemmyNet/lemmy/issues/2987

**Closed by lionirdeadman** 2023-07-24 04:36 UTC
Labels: enhancement
