### ISSUE TITLE
Recreate the private/public key of community when changed the hostname

### ISSUE THREAD

**Issue by gnh1201** [LemmyNet/lemmy#2019] opened 2022-01-02 13:08 UTC
### Is your proposal related to a problem?

There is a problem that the community cannot be found when the hostname is forcibly changed. #2018

### Describe the solution you'd like

I think I should recreate my private key and public key (in the `community` table) according to the changed hostname. However, Lemmy does not provide this function.

### Describe alternatives you've considered

For the time being, I will use it as the name `my_domain`. But this is not a solution.

### Additional context

Maybe it's not related. I just modified 'actor_id' and it worked normally. But this is not the right solution either. This is because I have to use the hostname as it is.

**Comment by gnh1201** [comment] 2022-01-02 13:21
Added:

Maybe it's not related. I just modified 'actor_id' and it worked normally. But this is not the right solution either. This is because I have to use the hostname as it is.

**Comment by dessalines** [comment] 2022-01-03 16:30
Dupe of #2018

**Closed by dessalines** 2022-01-03 16:30 UTC
Labels: enhancement
