### ISSUE TITLE
Combined subscriber counts

### ISSUE THREAD

**Issue by Hikiru** [LemmyNet/lemmy#3464] opened 2023-07-03 06:32 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently it can be hard to tell how many people are actually in a community since you can only see how many are subbed in your instance. This can make it harder to choose between multiple communities of the same name and can lead to further fragmentation when people dismiss a community for not having many subscribers on their instance.

### Describe the solution you'd like.

If possible, combine the subscriber count from all instances with a separate one for subscribers on your instance.

### Describe alternatives you've considered.

None

**Comment by BarterClub** [comment] 2023-07-17 03:44
Yes. Needs to happen sooner rather than later. Fixes duplicate communities

**Comment by Asudox** [comment] 2023-08-27 14:30
You don't actually have to combine the subscriber counts and make unnecessary API requests to all the instances.
The instance that the community resides in has the total subscriber count, so the instance can just ask that communities instance for the total subscriber count instead.

**Comment by Nutomic** [comment] 2023-10-02 14:42
Duplicate of https://github.com/LemmyNet/lemmy/issues/1440

**Closed by Nutomic** 2023-10-02 14:42 UTC
Labels: enhancement, area: federation
