### ISSUE TITLE
Iframely not installed with Ansible playbook

### ISSUE THREAD

**Issue by harcesz** [LemmyNet/lemmy#1722] opened 2021-08-23 12:50 UTC
Might be somewhat connected to https://github.com/LemmyNet/lemmy/issues/1721 but it seems the Ansible playbook is missing iframely part.

```
x@x:~# docker ps -a
CONTAINER ID   IMAGE                        COMMAND                  CREATED        STATUS        PORTS                      NAMES
2f680c0df737   dessalines/lemmy-ui:0.11.3   "docker-entrypoint.s…"   40 hours ago   Up 39 hours   127.0.0.1:1235->1234/tcp   lemmy_lemmy-ui_1
dac5c82696a7   dessalines/lemmy:0.11.3      "/app/lemmy"             40 hours ago   Up 39 hours   127.0.0.1:8536->8536/tcp   lemmy_lemmy_1
b8d825e0badf   asonix/pictrs:v0.2.6-r2      "/usr/bin/tini -- /u…"   40 hours ago   Up 40 hours   127.0.0.1:8537->8080/tcp   lemmy_pictrs_1
08eec7fd6ce5   postgres:12-alpine           "docker-entrypoint.s…"   40 hours ago   Up 40 hours   5432/tcp                   lemmy_postgres_1
5c0496b0a9a8   mwader/postfix-relay         "/root/run"              40 hours ago   Up 40 hours   25/tcp                     lemmy_postfix_1
x@x:~# docker start lemmy_iframely_1
Error response from daemon: No such container: lemmy_iframely_1
Error: failed to start containers: lemmy_iframely_1
```

**Comment by dessalines** [comment] 2021-08-23 13:07
Follow the instructions in #1717.

**Comment by dessalines** [comment] 2021-08-23 13:07
Dupe of #1717 , #1721

**Closed by dessalines** 2021-08-23 13:07 UTC
Labels: bug
