### ISSUE TITLE
Don't show remote posts for non-logged-in users.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2169] opened 2022-03-28 17:28 UTC
This would effectively hide the `All` view for non-logged-in users, meaning they could only see `Local`.

**Comment by Nutomic** [comment] 2022-05-24 19:32
Why close this?

**Comment by dessalines** [comment] 2022-05-25 03:33
Seems like its not necessary right?  The default view is Local, but some instances might want not logged in users to see all. I don't remember the reasoning behind wanting to hide remote content.

**Comment by Nutomic** [comment] 2022-05-25 21:19
Essentially, if a post or comment can be viewed on your instance, you as admin are responsible for it to some degree. This also goes for federated posts, because people who just come across the site dont know about federation. They might ask you to take things down, and you have to point them to the right instance to contact (happened to me with Peertube). And it generally increases the risk of being an admin, because any federated instance can create a problematic post on your instance. 

If users without login can only view local communities, the risk is much lower because they know how federation works, and can use the report function when necessary. In this case its also not possible to make an abuse report to the hosting provider, because the hosting provider wont have an account. 

On the other hand, no one else has requested this yet, so its probably low priority. Anyway will reopen.

**Comment by poVoq** [comment] 2022-09-20 11:37
Any update on this? Basically all other federated software has this option and it is quite vital for hosting in some countries.

**Comment by dessalines** [comment] 2022-09-26 23:58
Should this be a site setting, or should we just say that the `All` view should never be public.

**Comment by Nutomic** [comment] 2023-01-15 21:25
Duplicate of https://github.com/LemmyNet/lemmy/issues/1963.

**Closed by Nutomic** 2023-01-15 21:25 UTC
Labels: enhancement
