### ISSUE TITLE
Feed for empty community contains random posts

### ISSUE THREAD

**Issue by remram44** [LemmyNet/lemmy#2117] opened 2022-03-07 17:01 UTC
### Issue Summary

This community is empty: https://lemmy.ml/c/reproducibility

Its feed is not: https://lemmy.ml/feeds/c/reproducibility.xml?sort=Active

### Steps to Reproduce

1. Find empty community
2. Open feed

### Technical details

* Started happening recently

**Comment by dessalines** [comment] 2022-03-07 18:15
Dupe of #2116

**Closed by dessalines** 2022-03-07 18:15 UTC
Labels: bug
