### ISSUE TITLE
Blocking\Hiding communities from Local\All

### ISSUE THREAD

**Issue by NIXOYE** [LemmyNet/lemmy#1339] opened 2020-12-30 04:08 UTC
It's frustrating to browse Local\All and see posts from communities I know I don't want to see posts about like Memes while I'm trying to discover new communities.

I'd like to be able to block or hide communities so I don't see them in Local\All and have them only available if I search for them.

**Comment by dessalines** [comment] 2020-12-30 15:39
Dupe of #426

**Closed by dessalines** 2020-12-30 15:39 UTC
Labels: enhancement
