### ISSUE TITLE
Add ability to ignore users

### ISSUE THREAD

**Issue by heylix** [LemmyNet/lemmy#1629] opened 2021-06-05 11:21 UTC
### Is your proposal related to a problem?

Some users don't go well with others. It's hard to deescalate and not interact with people if you see their comments and reactions everywhere. Some can cope better with provocations than others. It would be nice if you could help the "others" by providing technical features to support ignoring users on the site.

### Describe the solution you'd like

I once saw a forum based on vBulletin where you could add users to your ignore list. This had the following effects:

- you didn't get notifications when they commented on one of your posts
- you didn't get notifications for messages
- every post or private message they wrote was hidden.
  - the comment/message text was replaced with *User heylix is on your ignore list.* with two buttons next to it:
    - show anyway – which showed the text of the post/message until you reloaded the page
    - go to your ignore list – which enabled you to remove them from your ignore list.
      - this button added an URL parameter to the ignore list page which highlighted their username so you could find it if you ignored many users
- if you went to your "recent posts" list, comments by those users weren't listed.
- if you looked at the forum view, topics with no new posts other than those by ignored users were considered "read".
  - this meant that the link which was usually bold when new comments were made, wasn't bold
  - it also meant that the small indicator who made the last comment didn't include ignored users.

### Describe alternatives you've considered

There could be a feature to completely hide all interactions with the user, not even showing the user name itself. This removes context in many situations where the hidden comment has answers which reference it.

You could also leave the burden of ignoring people on the users being bothered by others. This wastes their time because they accidentally read the comments from people they want to ignore and it may enable emotional reactions.

Reporting users to the mods or admins for them to ban them only creates more drama. You could additionally report them, though, if they're violating the rules of the instance/community.

#### Relevant posts on the main Lemmy instance:

- [What do you think about recent events on c/worldnews? Should we try to prevent such behaviors?](https://lemmy.ml/post/68017)
- [@soferman@lemmy.ml banned on !worldnews@lemmy.ml for hostile behaviour](https://lemmy.ml/post/68605)

#### Relevant literature:

- [Trolling in Online Discussions: From Provocation to Community-building](https://www.researchgate.net/publication/269652088_Trolling_in_Online_Discussions_From_Provocation_to_Community-building). Hopkinson, Chris. (2013). Brno Studies in English. 39. 5-25. 10.5817/BSE2013-1-1.<br /><blockquote>Trolls’ opening moves […] can be seen as dropping ‘bait’ into the water and waiting for the in-group members to ‘bite’. […] If this strategy is successful, a ‘flame war’ may ensue […]</blockquote>
- [How to Stop Caring About Trolls and Get On With Your Life](https://lifehacker.com/how-to-stop-caring-about-trolls-and-get-on-with-your-li-5854053). Gordon, Whitson (2014). Lifehacker.com.<br /><blockquote>While I highly recommend avoiding the trolls at all costs, if you accidentally get yourself lured into a discussion, you can either try avoiding, or attempt to fizzle out the argument yourself.</blockquote>
- [Ignore feature - an open discussion](https://www.dndbeyond.com/forums/d-d-beyond-general/general-discussion/110296-ignore-feature-an-open-discussion). UrthTheThoughtless (2021). D&D Beyond forums.<br /><blockquote>To me, the ignore feature needs to be available as a tool for users to protect themselves from abuse.</blockquote>

**Comment by Nutomic** [comment] 2021-06-07 21:23
Duplicate of #426.

**Closed by Nutomic** 2021-06-07 21:23 UTC
Labels: enhancement

**Comment by heylix** [comment] 2021-06-27 09:42
The scope of this Issue and the other one does overlap, but is not the same. However, if you think you can implement two things at once, I'll post my idea over there, too, that it doesn't get lost in the conversation.
