### ISSUE TITLE
RSS feed URL parameter to make it link to post, rather than external URL

### ISSUE THREAD

**Issue by mariomadproductions** [LemmyNet/lemmy#4849] opened 2024-06-19 14:57 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Currently, when I open an entry from a lemmy RSS feed, it goes straight to the external URL (if there is one). I'd like to go to the lemmy post itself, so I can see the comments etc.

### Describe the solution you'd like.

A URL parameter for to make all the links internal should work with any standard RSS reader.

### Describe alternatives you've considered.

Don't think there are any good alternatives.

**Comment by Nutomic** [comment] 2024-06-20 10:49
It doesnt make sense to have too many config options, we can simply change the value of the url field. [Here](https://github.com/LemmyNet/lemmy/blob/main/crates/routes/src/feeds.rs#L545) is the code, need to replace `url` with `post_url` and set mime type `text/html`.

**Comment by dessalines** [comment] 2024-06-20 18:22
Dupe of #1378

Also what version are you running? `0.19.4` should correctly link to the comments, `0.19.3` doesn't.

**Closed** 2024-06-20 18:22 UTC
Labels: enhancement, area: rss

**Comment by mariomadproductions** [comment] 2024-06-20 19:01
> Dupe of #1378
> 
> Also what version are you running? `0.19.4` should correctly link to the comments, `0.19.3` doesn't.

My mistake, I didn't read that issue carefully enough. Sorry.

Yeah, 0.19.3, I'll look into upgrading. Thanks.
