### ISSUE TITLE
Add Email Activation

### ISSUE THREAD

**Issue by trymeouteh** [LemmyNet/lemmy#691] opened 2020-05-03 02:19 UTC
When I signed up to lemmy.ml and entered my email, I did not get a email to verify my email address with the lemmy account. This is needed to prevent people from signing up with email addresses that they do not own.

**Comment by dessalines** [comment] 2020-05-03 02:43
Email is only used for password resets right now, not verification, which is why its an optional field. So all that using another persons email would do is ensure that they are the only ones that can reset your password.

And instead of email for onboarding, we're really preferrering #209 , which is at least how mastodon does onboarding.  

dupe of #209

**Closed by dessalines** 2020-05-03 02:43 UTC

**Comment by StaticallyTypedRice** [comment] 2020-05-03 07:38
Another issue is that notifications sent to the wrong person's email can be seen as spam at best and leak private information at worst.

**Comment by StaticallyTypedRice** [comment] 2020-05-03 07:38
Another issue is that notifications sent to the wrong person's email can be seen as spam or even leak private information.
