### ISSUE TITLE
Score posts based on community size at the time of voting

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy#2794] opened 2023-03-30 19:44 UTC
As a community grows posts receive more votes making it appear as if newer posts are better than old posts. In order to actually be able to find the best posts the top filter would have to use another score that takes into account the size of the community at the time of voting. Otherwise if a community grows fast enough the top posts of all time would be the same as the top posts of last month.

**Comment by dessalines** [comment] 2023-03-30 19:45
Dupe of #1026 

Please search for an issue before you create one.

**Closed by dessalines** 2023-03-30 19:45 UTC
Labels: enhancement

**Comment by JediMaster25** [comment] 2023-06-13 10:48
The original post is about different communities. And what I'm mentioning is about the same community at different times.

**Comment by krestenlaust** [comment] 2023-06-15 20:24
I agree with you that this is not a dupe. But this issue is something reddit didn't even address. But it would be interesting to see implemented.

**Comment by maegul** [comment] 2023-07-03 10:07
Implementation details may vary, but conceptually, it seems we're talking about normalising a post's score either by its location/origin or its time of creation ... ie, Space and/or time.  So there's a certain sense of duplication IMO.

**Comment by krestenlaust** [comment] 2023-07-03 10:12
> Implementation details may vary, but conceptually, it seems we're talking about normalising a post's score either by its location/origin or its time of creation ... ie, Space and/or time. So there's a certain sense of duplication IMO.

Conceptually yes. But since this is a technical issue, I believe we compare issues depending on implementation rather than concept. I'm not a developer on this project, but I'm confident that the implementation isn't related at all on these two issues.

**Comment by 8ullyMaguire** [comment] 2023-07-12 08:27
bump
