### ISSUE TITLE
Private communities

### ISSUE THREAD

**Issue by TurkeyMan** [LemmyNet/lemmy#2266] opened 2022-05-17 05:44 UTC
### Is your proposal related to a problem?

I manage a community discussion space, and some of the discussion spaces should be private to certain members.
Members should not be able to see private communities by default, and permitted only by invitation.

### Describe the solution you'd like

Allow private communities which are invisible to non-subscribed users.
Allow subscriber list to be directly managed by admins, or for admins to issue invitations.

As stretch-goals, allow private communities which appear in the community list, and allow users to "Request subscription", which can be accepted or rejected by an admin.

### Describe alternatives you've considered

I'm not sure how to effect this other than to run 2 separate lemmy instances, and maintain separate user databases?

**Comment by Nutomic** [comment] 2022-05-17 14:35
Duplicate of #187.

**Closed by Nutomic** 2022-05-17 14:35 UTC
Labels: enhancement

**Comment by TurkeyMan** [comment] 2022-05-17 23:56
To be fair, I'm not sure this is a duplicate of #187.
That one says "only mods can [...]", I wouldn't be satisfied with a solution where every subscriber to a community had to be a moderator. I want my moderators to be moderators...

**Comment by TurkeyMan** [comment] 2022-05-18 05:22
Sadly, I think this issue is a limiter to adoption of lemmy for my org. I'll keep an eye on the project, and look forward to a resolution on this matter. I can't use it without user access rights/control.
