### ISSUE TITLE
[Bug]: image delete endpoint doesn't seem to work and always responds with a 204 status

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/lemmy#3999] opened 2023-09-29 14:49 UTC
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

The delete endpoint for images doesn't to work (`GET /pictrs/image/delete/{delete_token}/{file}`)

EX: 
https://lemmy.one/pictrs/image/2b5b5b64-269f-40f9-bcd7-2818074ad6e6.jpeg

delete:
https://lemmy.one/pictrs/image/delete/7e9b4ec3-ed91-48e3-b039-f14b08e75cb2/2b5b5b64-269f-40f9-bcd7-2818074ad6e6.jpeg

Also the endpoint seems to always respond with 204 statuscode.

### Steps to Reproduce

upload a image, gets is delete token and filename, construct its delete url and visible url

1. click on this link https://lemmy.one/pictrs/image/delete/7e9b4ec3-ed91-48e3-b039-f14b08e75cb2/2b5b5b64-269f-40f9-bcd7-2818074ad6e6.jpeg
2. open this link: https://lemmy.one/pictrs/image/2b5b5b64-269f-40f9-bcd7-2818074ad6e6.jpeg
3. Image this visible

### Technical Details

Got it from this response object

Success(UploadImageResponse(msg=ok, files=[ImageFile(file=9a6978f4-a930-441a-9680-722abf01f84e.jpeg, delete_token=963a0306-54d2-4a1e-b95f-6d38ea3eaf62), ImageFile(file=2b5b5b64-269f-40f9-bcd7-2818074ad6e6.jpeg, delete_token=7e9b4ec3-ed91-48e3-b039-f14b08e75cb2)], url=null, delete_url=null))

Another response from PostMan that you can test

{
    "msg": "ok",
    "files": [
        {
            "file": "5ab91f6c-62aa-4e05-9aa7-7ffce36edaa2.jpeg",
            "delete_token": "3eb8530a-2132-4ef6-8c2e-e220a65cbe56"
        }
    ]
}

### Version

0.18.4

### Lemmy Instance URL

lemmy.one

**Comment by Nutomic** [comment] 2023-10-02 14:45
Do you see anything relevant in the server logs?

cc @asonix

**Comment by asonix** [comment] 2023-10-02 20:44
The file used as an example here seems to have been deleted

**Comment by asonix** [comment] 2023-10-02 20:48
I think I can shed some light on this, though. Deletions in pict-rs are queued, rather than done inline, so the image may still be accessible for a short time after the delete endpoint was invoked. 

Additionally, pict-rs sets HTTP headers that instruct your browser to cache images. It's possible for your browser to still render the image even after pict-rs has removed it. You can generally test this by "hard refreshing" the image with `ctrl+shift+R` instead of `ctrl+R`

**Comment by MV-GH** [comment] 2023-10-02 23:40
It was still accessible less than 6 hours ago. It wasn't cached. I ran this through PostMan. and multiple browsers, different devices, If something was caching it, it would ve been something server side. But that would mean it was cached for over 3 days

**Comment by asonix** [comment] 2023-10-04 00:41
what version of pict-rs are you running?

**Comment by MV-GH** [comment] 2023-10-04 07:08
I am not the owner of lemmy.one but it uses Lemmy 0.18.3 it should ve the version specified somewhere.

**Comment by Nutomic** [comment] 2023-10-04 09:11
I can reproduce the problem with pictrs 0.4.3 and Lemmy 0.18.5, here are the logs:

```
pictrs_1    | 2023-10-04T09:06:52.213373Z  INFO HTTP request{http.method=GET http.route=/image/delete/{delete_token}/{filename} http.flavor=1.1 http.scheme=http http.host=pictrs:8080 http.client_ip=88.14.249.166 http.user_agent=Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0 http.target=/image/delete/46f6f5ca-d73c-49b3-a696-c195c6e6f0d3/9436259a-eb74-4091-942a-8c6febfd8e47.png otel.name=HTTP GET /image/delete/{delete_token}/{filename} otel.kind="server" request_id=c49283a3-3d5e-47d3-b435-44a6b9d3dbbb}: tracing_actix_web::root_span_builder: new
pictrs_1    | 2023-10-04T09:06:52.213986Z  INFO HTTP request{http.method=GET http.route=/image/delete/{delete_token}/{filename} http.flavor=1.1 http.scheme=http http.host=pictrs:8080 http.client_ip=88.14.249.166 http.user_agent=Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0 http.target=/image/delete/46f6f5ca-d73c-49b3-a696-c195c6e6f0d3/9436259a-eb74-4091-942a-8c6febfd8e47.png otel.name=HTTP GET /image/delete/{delete_token}/{filename} otel.kind="server" request_id=c49283a3-3d5e-47d3-b435-44a6b9d3dbbb trace_id=00000000000000000000000000000000 http.status_code=204 otel.status_code="OK"}: tracing_actix_web::root_span_builder: close time.busy=410µs time.idle=206µs
```

Not much info there, I tried with debug log too but it doesnt show anything else.

**Comment by asonix** [comment] 2023-10-04 15:35
There should be corresponding `cleanup` jobs that are queued when you hit that endpoint. I think a reasonable change here would be to check the delete token in the endpoint before queuing the job, since if the token is wrong the job will silently do nothing.

**Comment by asonix** [comment] 2023-10-04 17:34
fwiw I can't reproduce the issue of deletes not working locally, but I will inline the delete operation anyway, since that will provide better errors in the event something goes wrong.

**Comment by asonix** [comment] 2023-10-05 04:22
Released 0.4.5, which inlines the image deletion

**Comment by Nutomic** [comment] 2023-10-05 08:35
Tried with 0.4.5, deletion is still not working and same log messages as before.

**Comment by asonix** [comment] 2023-10-05 16:26
Are you sure? Any failure to remove the image should cause error responses now.

**Comment by asonix** [comment] 2023-10-05 16:39
Also how are you changing the log levels. pict-rs' logging is governed by `PICTRS__TRACING__LOGGING__TARGETS` and not `RUST_LOG`. the default value is `warn,tracing_actix_web=info,actix_server=info,actix_web=info`

documented here: https://git.asonix.dog/asonix/pict-rs/src/branch/v0.4.x/pict-rs.toml#L40

**Comment by asonix** [comment] 2023-10-05 18:36
server: `lemmy.ml`
command:
```bash
curl -i 'https://lemmy.ml/pictrs/image/delete/5576adef-0278-4a8a-8c2e-7df908f9b8b0/6a0d257b-b741-4afe-b9ac-79a781a06a75.png'
```
result: image is no longer accessible
https://lemmy.ml/pictrs/image/6a0d257b-b741-4afe-b9ac-79a781a06a75.png

This is in fact a bug, because it's my understanding that the `delete` endpoint requires authentication: https://github.com/LemmyNet/lemmy/blob/main/crates/routes/src/images.rs#L210

I should not have been able to delete this with `curl`.

regardless, I told lemmy to delete the image and it did.

**Comment by Nutomic** [comment] 2023-10-06 08:47
Ah I just assumed that the standard var for logging would work. Here are the proper debug logs from deletion:
```

pictrs_1    | 2023-10-06T08:44:48.312669Z  INFO HTTP request{http.method=GET http.route=/image/delete/{delete_token}/{filename} http.flavor=1.1 http.scheme=http http.host=pictrs:8080 http.client_ip=xxx http.user_agent=xxx http.target=/image/delete/3faec56d-cdfa-4608-87ca-4febfc7ef85a/c1ae8f87-ead3-4627-a565-e8aae398de2c.png otel.name=HTTP GET /image/delete/{delete_token}/{filename} otel.kind="server" request_id=0f345e78-43e6-40f3-b869-cbf829e893d1}: tracing_actix_web::root_span_builder: new
pictrs_1    | 2023-10-06T08:44:48.313539Z  INFO HTTP request{http.method=GET http.route=/image/delete/{delete_token}/{filename} http.flavor=1.1 http.scheme=http http.host=pictrs:8080 http.client_ip=xxx http.user_agent=xxx http.target=/image/delete/3faec56d-cdfa-4608-87ca-4febfc7ef85a/c1ae8f87-ead3-4627-a565-e8aae398de2c.png otel.name=HTTP GET /image/delete/{delete_token}/{filename} otel.kind="server" request_id=0f345e78-43e6-40f3-b869-cbf829e893d1 trace_id=00000000000000000000000000000000}:Deleting file{path_entries=Path(("3faec56d-cdfa-4608-87ca-4febfc7ef85a", "c1ae8f87-ead3-4627-a565-e8aae398de2c.png"))}: pict_rs: new
pictrs_1    | 2023-10-06T08:44:48.313595Z  INFO HTTP request{http.method=GET http.route=/image/delete/{delete_token}/{filename} http.flavor=1.1 http.scheme=http http.host=pictrs:8080 http.client_ip=xxx http.user_agent=xxx http.target=/image/delete/3faec56d-cdfa-4608-87ca-4febfc7ef85a/c1ae8f87-ead3-4627-a565-e8aae398de2c.png otel.name=HTTP GET /image/delete/{delete_token}/{filename} otel.kind="server" request_id=0f345e78-43e6-40f3-b869-cbf829e893d1 trace_id=00000000000000000000000000000000}:Deleting file{path_entries=Path(("3faec56d-cdfa-4608-87ca-4febfc7ef85a", "c1ae8f87-ead3-4627-a565-e8aae398de2c.png"))}:alias: pict_rs::queue::cleanup: new
pictrs_1    | 2023-10-06T08:44:48.314188Z  INFO HTTP request{http.method=GET http.route=/image/delete/{delete_token}/{filename} http.flavor=1.1 http.scheme=http http.host=pictrs:8080 http.client_ip=xxx http.user_agent=xxx http.target=/image/delete/3faec56d-cdfa-4608-87ca-4febfc7ef85a/c1ae8f87-ead3-4627-a565-e8aae398de2c.png otel.name=HTTP GET /image/delete/{delete_token}/{filename} otel.kind="server" request_id=0f345e78-43e6-40f3-b869-cbf829e893d1 trace_id=00000000000000000000000000000000}:Deleting file{path_entries=Path(("3faec56d-cdfa-4608-87ca-4febfc7ef85a", "c1ae8f87-ead3-4627-a565-e8aae398de2c.png"))}:alias:cleanup{alias=Alias { id: Uuid(c1ae8f87-ead3-4627-a565-e8aae398de2c), extension: Some(".png") }}: pict_rs::repo::sled: new
pictrs_1    | 2023-10-06T08:44:48.314661Z  INFO HTTP request{http.method=GET http.route=/image/delete/{delete_token}/{filename} http.flavor=1.1 http.scheme=http http.host=pictrs:8080 http.client_ip=xxx http.user_agent=xxx http.target=/image/delete/3faec56d-cdfa-4608-87ca-4febfc7ef85a/c1ae8f87-ead3-4627-a565-e8aae398de2c.png otel.name=HTTP GET /image/delete/{delete_token}/{filename} otel.kind="server" request_id=0f345e78-43e6-40f3-b869-cbf829e893d1 trace_id=00000000000000000000000000000000}:Deleting file{path_entries=Path(("3faec56d-cdfa-4608-87ca-4febfc7ef85a", "c1ae8f87-ead3-4627-a565-e8aae398de2c.png"))}:alias:cleanup{alias=Alias { id: Uuid(c1ae8f87-ead3-4627-a565-e8aae398de2c), extension: Some(".png") }}: pict_rs::repo::sled: close time.busy=131µs time.idle=342µs
pictrs_1    | 2023-10-06T08:44:48.315024Z  INFO HTTP request{http.method=GET http.route=/image/delete/{delete_token}/{filename} http.flavor=1.1 http.scheme=http http.host=pictrs:8080 http.client_ip=xxx http.user_agent=xxx http.target=/image/delete/3faec56d-cdfa-4608-87ca-4febfc7ef85a/c1ae8f87-ead3-4627-a565-e8aae398de2c.png otel.name=HTTP GET /image/delete/{delete_token}/{filename} otel.kind="server" request_id=0f345e78-43e6-40f3-b869-cbf829e893d1 trace_id=00000000000000000000000000000000}:Deleting file{path_entries=Path(("3faec56d-cdfa-4608-87ca-4febfc7ef85a", "c1ae8f87-ead3-4627-a565-e8aae398de2c.png"))}:alias:aliases: pict_rs::repo::sled: new
pictrs_1    | 2023-10-06T08:44:48.315299Z  INFO HTTP request{http.method=GET http.route=/image/delete/{delete_token}/{filename} http.flavor=1.1 http.scheme=http http.host=pictrs:8080 http.client_ip=xxx http.user_agent=xxx http.target=/image/delete/3faec56d-cdfa-4608-87ca-4febfc7ef85a/c1ae8f87-ead3-4627-a565-e8aae398de2c.png otel.name=HTTP GET /image/delete/{delete_token}/{filename} otel.kind="server" request_id=0f345e78-43e6-40f3-b869-cbf829e893d1 trace_id=00000000000000000000000000000000}:Deleting file{path_entries=Path(("3faec56d-cdfa-4608-87ca-4febfc7ef85a", "c1ae8f87-ead3-4627-a565-e8aae398de2c.png"))}:alias:aliases: pict_rs::repo::sled: close time.busy=143µs time.idle=131µs
pictrs_1    | 2023-10-06T08:44:48.315483Z  INFO HTTP request{http.method=GET http.route=/image/delete/{delete_token}/{filename} http.flavor=1.1 http.scheme=http http.host=pictrs:8080 http.client_ip=xxx http.user_agent=xxx http.target=/image/delete/3faec56d-cdfa-4608-87ca-4febfc7ef85a/c1ae8f87-ead3-4627-a565-e8aae398de2c.png otel.name=HTTP GET /image/delete/{delete_token}/{filename} otel.kind="server" request_id=0f345e78-43e6-40f3-b869-cbf829e893d1 trace_id=00000000000000000000000000000000}:Deleting file{path_entries=Path(("3faec56d-cdfa-4608-87ca-4febfc7ef85a", "c1ae8f87-ead3-4627-a565-e8aae398de2c.png"))}:alias:push{queue_name="cleanup" job={"Hash":{"hash":"NzZV/jTKmyGykjQq3ZpUQPAUR6Jj1y92e0jRl/ii6dU="}}}: pict_rs::repo::sled: new
pictrs_1    | 2023-10-06T08:44:48.315813Z  INFO HTTP request{http.method=GET http.route=/image/delete/{delete_token}/{filename} http.flavor=1.1 http.scheme=http http.host=pictrs:8080 http.client_ip=xxx http.user_agent=xxx http.target=/image/delete/3faec56d-cdfa-4608-87ca-4febfc7ef85a/c1ae8f87-ead3-4627-a565-e8aae398de2c.png otel.name=HTTP GET /image/delete/{delete_token}/{filename} otel.kind="server" request_id=0f345e78-43e6-40f3-b869-cbf829e893d1 trace_id=00000000000000000000000000000000}:Deleting file{path_entries=Path(("3faec56d-cdfa-4608-87ca-4febfc7ef85a", "c1ae8f87-ead3-4627-a565-e8aae398de2c.png"))}:alias:push{queue_name="cleanup" job={"Hash":{"hash":"NzZV/jTKmyGykjQq3ZpUQPAUR6Jj1y92e0jRl/ii6dU="}}}: pict_rs::repo::sled: close time.busy=66.0µs time.idle=264µs
pictrs_1    | 2023-10-06T08:44:48.317174Z  INFO HTTP request{http.method=GET http.route=/image/delete/{delete_token}/{filename} http.flavor=1.1 http.scheme=http http.host=pictrs:8080 http.client_ip=xxx http.user_agent=xxx http.target=/image/delete/3faec56d-cdfa-4608-87ca-4febfc7ef85a/c1ae8f87-ead3-4627-a565-e8aae398de2c.png otel.name=HTTP GET /image/delete/{delete_token}/{filename} otel.kind="server" request_id=0f345e78-43e6-40f3-b869-cbf829e893d1 trace_id=00000000000000000000000000000000}:Deleting file{path_entries=Path(("3faec56d-cdfa-4608-87ca-4febfc7ef85a", "c1ae8f87-ead3-4627-a565-e8aae398de2c.png"))}:alias: pict_rs::queue::cleanup: close time.busy=3.54ms time.idle=33.5µs
pictrs_1    | 2023-10-06T08:44:48.317342Z  INFO HTTP request{http.method=GET http.route=/image/delete/{delete_token}/{filename} http.flavor=1.1 http.scheme=http http.host=pictrs:8080 http.client_ip=xxx http.user_agent=xxx http.target=/image/delete/3faec56d-cdfa-4608-87ca-4febfc7ef85a/c1ae8f87-ead3-4627-a565-e8aae398de2c.png otel.name=HTTP GET /image/delete/{delete_token}/{filename} otel.kind="server" request_id=0f345e78-43e6-40f3-b869-cbf829e893d1 trace_id=00000000000000000000000000000000}:Deleting file{path_entries=Path(("3faec56d-cdfa-4608-87ca-4febfc7ef85a", "c1ae8f87-ead3-4627-a565-e8aae398de2c.png"))}: pict_rs: close time.busy=3.75ms time.idle=54.0µs
pictrs_1    | 2023-10-06T08:44:48.317598Z  INFO HTTP request{http.method=GET http.route=/image/delete/{delete_token}/{filename} http.flavor=1.1 http.scheme=http http.host=pictrs:8080 http.client_ip=xxx http.user_agent=xxx http.target=/image/delete/3faec56d-cdfa-4608-87ca-4febfc7ef85a/c1ae8f87-ead3-4627-a565-e8aae398de2c.png otel.name=HTTP GET /image/delete/{delete_token}/{filename} otel.kind="server" request_id=0f345e78-43e6-40f3-b869-cbf829e893d1 trace_id=00000000000000000000000000000000 http.status_code=204 otel.status_code="OK"}: tracing_actix_web::root_span_builder: close time.busy=4.72ms time.idle=216µs
pictrs_1    | 2023-10-06T08:44:48.318553Z DEBUG pop{queue_name="cleanup" worker_id=pict-rs-1-0}: sled::pagecache::iobuf: advancing offset within the currentsegment from 4786003 to 4786262
pictrs_1    | 2023-10-06T08:44:48.319475Z DEBUG sled::pagecache::iobuf: wrote lsns 39389011-39389269 to disk at offsets 4786003-4786261, maxed false complete_len 259
pictrs_1    | 2023-10-06T08:44:48.319581Z DEBUG sled::pagecache::iobuf: mark_interval(39389011, 259)
pictrs_1    | 2023-10-06T08:44:48.319669Z DEBUG sled::pagecache::iobuf: new highest interval: 39389011 - 39389269
pictrs_1    | 2023-10-06T08:44:48.319821Z DEBUG pop{queue_name="cleanup" worker_id=pict-rs-1-0}: sled::pagecache::iobuf: make_stable(39389269) returning
pictrs_1    | 2023-10-06T08:44:48.320178Z  INFO pop{queue_name="cleanup" worker_id=pict-rs-1-0}: pict_rs::repo::sled: close time.busy=2.08ms time.idle=13.8s
pictrs_1    | 2023-10-06T08:44:48.321597Z  INFO Running Job{worker_id="pict-rs-1-0"}: pict_rs::queue: new
pictrs_1    | 2023-10-06T08:44:48.321833Z  INFO Running Job{worker_id="pict-rs-1-0"}:hash: pict_rs::queue::cleanup: new
pictrs_1    | 2023-10-06T08:44:48.321935Z  INFO Running Job{worker_id="pict-rs-1-0"}:hash:aliases: pict_rs::repo::sled: new
pictrs_1    | 2023-10-06T08:44:48.322099Z  INFO Running Job{worker_id="pict-rs-1-0"}:hash:aliases: pict_rs::repo::sled: close time.busy=39.1µs time.idle=126µs
pictrs_1    | 2023-10-06T08:44:48.322194Z  INFO Running Job{worker_id="pict-rs-1-0"}:hash:variants{hash="373655fe34ca9b21b292342add9a5440f01447a263d72f767b48d197f8a2e9d5"}: pict_rs::repo::sled: new
pictrs_1    | 2023-10-06T08:44:48.326946Z  INFO Running Job{worker_id="pict-rs-1-0"}:hash:variants{hash="373655fe34ca9b21b292342add9a5440f01447a263d72f767b48d197f8a2e9d5"}: pict_rs::repo::sled: close time.busy=4.56ms time.idle=195µs
pictrs_1    | 2023-10-06T08:44:48.327542Z  INFO Running Job{worker_id="pict-rs-1-0"}:hash:push{queue_name="cleanup" job={"Identifier":{"identifier":"MDAyLzAxNy8wNzgvMTdkMDVlOWEtNjUwMS00ZjMzLTk3ZDMtNGJiNmYzODE2OTY1"}}}: pict_rs::repo::sled: new
pictrs_1    | 2023-10-06T08:44:48.327695Z  INFO Running Job{worker_id="pict-rs-1-0"}:hash:push{queue_name="cleanup" job={"Identifier":{"identifier":"MDAyLzAxNy8wNzgvMTdkMDVlOWEtNjUwMS00ZjMzLTk3ZDMtNGJiNmYzODE2OTY1"}}}: pict_rs::repo::sled: close time.busy=72.2µs time.idle=80.9µs
pictrs_1    | 2023-10-06T08:44:48.327758Z  INFO Running Job{worker_id="pict-rs-1-0"}:hash:cleanup{hash="373655fe34ca9b21b292342add9a5440f01447a263d72f767b48d197f8a2e9d5"}: pict_rs::repo::sled: new
pictrs_1    | 2023-10-06T08:44:48.327926Z  INFO Running Job{worker_id="pict-rs-1-0"}:hash:cleanup{hash="373655fe34ca9b21b292342add9a5440f01447a263d72f767b48d197f8a2e9d5"}:aliases: pict_rs::repo::sled: new
pictrs_1    | 2023-10-06T08:44:48.328060Z  INFO Running Job{worker_id="pict-rs-1-0"}:hash:cleanup{hash="373655fe34ca9b21b292342add9a5440f01447a263d72f767b48d197f8a2e9d5"}:aliases: pict_rs::repo::sled: close time.busy=70.4µs time.idle=63.5µs
pictrs_1    | 2023-10-06T08:44:48.328217Z  INFO Running Job{worker_id="pict-rs-1-0"}:hash:cleanup{hash="373655fe34ca9b21b292342add9a5440f01447a263d72f767b48d197f8a2e9d5"}: pict_rs::repo::sled: close time.busy=42.4µs time.idle=417µs
pictrs_1    | 2023-10-06T08:44:48.328262Z  INFO Running Job{worker_id="pict-rs-1-0"}:hash: pict_rs::queue::cleanup: close time.busy=1.84ms time.idle=4.60ms
pictrs_1    | 2023-10-06T08:44:48.328334Z  INFO Running Job{worker_id="pict-rs-1-0"}: pict_rs::queue: close time.busy=2.12ms time.idle=4.62ms
pictrs_1    | 2023-10-06T08:44:48.328384Z  INFO pop{queue_name="cleanup" worker_id=pict-rs-1-0}: pict_rs::repo::sled: new
pictrs_1    | 2023-10-06T08:44:48.328463Z DEBUG pop{queue_name="cleanup" worker_id=pict-rs-1-0}: sled::pagecache::iobuf: advancing offset within the currentsegment from 4786262 to 4786612
pictrs_1    | 2023-10-06T08:44:48.328640Z DEBUG sled::pagecache::iobuf: wrote lsns 39389270-39389619 to disk at offsets 4786262-4786611, maxed false complete_len 350
pictrs_1    | 2023-10-06T08:44:48.328674Z DEBUG sled::pagecache::iobuf: mark_interval(39389270, 350)
pictrs_1    | 2023-10-06T08:44:48.328699Z DEBUG sled::pagecache::iobuf: new highest interval: 39389270 - 39389619
pictrs_1    | 2023-10-06T08:44:48.328751Z DEBUG pop{queue_name="cleanup" worker_id=pict-rs-1-0}: sled::pagecache::iobuf: make_stable(39389619) returning
pictrs_1    | 2023-10-06T08:44:48.328870Z  INFO pop{queue_name="cleanup" worker_id=pict-rs-1-0}: pict_rs::repo::sled: close time.busy=387µs time.idle=98.7µs
pictrs_1    | 2023-10-06T08:44:48.328912Z  INFO Running Job{worker_id="pict-rs-1-0"}: pict_rs::queue: new
pictrs_1    | 2023-10-06T08:44:48.328964Z  INFO Running Job{worker_id="pict-rs-1-0"}:identifier: pict_rs::queue::cleanup: new
pictrs_1    | 2023-10-06T08:44:48.330990Z  INFO Running Job{worker_id="pict-rs-1-0"}:identifier:remove{self=FileStore { path_gen: "generator", root_dir: "/mnt/files" } identifier=FileId("002/017/078/17d05e9a-6501-4f33-97d3-4bb6f3816965")}: pict_rs::store::file_store: new
pictrs_1    | 2023-10-06T08:44:48.332604Z  INFO Running Job{worker_id="pict-rs-1-0"}:identifier:remove{self=FileStore { path_gen: "generator", root_dir: "/mnt/files" } identifier=FileId("002/017/078/17d05e9a-6501-4f33-97d3-4bb6f3816965")}: pict_rs::store::file_store: close time.busy=1.57ms time.idle=45.6µs
pictrs_1    | 2023-10-06T08:44:48.333262Z  INFO Running Job{worker_id="pict-rs-1-0"}:identifier: pict_rs::queue::cleanup: close time.busy=2.30ms time.idle=2.00ms
pictrs_1    | 2023-10-06T08:44:48.333330Z  INFO Running Job{worker_id="pict-rs-1-0"}: pict_rs::queue: close time.busy=4.38ms time.idle=38.3µs
pictrs_1    | 2023-10-06T08:44:48.333367Z  INFO pop{queue_name="cleanup" worker_id=pict-rs-1-0}: pict_rs::repo::sled: new
pictrs_1    | 2023-10-06T08:44:48.333440Z DEBUG pop{queue_name="cleanup" worker_id=pict-rs-1-0}: sled::pagecache::iobuf: advancing offset within the currentsegment from 4786612 to 4786844
pictrs_1    | 2023-10-06T08:44:48.334829Z DEBUG sled::pagecache::iobuf: wrote lsns 39389620-39389851 to disk at offsets 4786612-4786843, maxed false complete_len 232
pictrs_1    | 2023-10-06T08:44:48.335420Z DEBUG sled::pagecache::iobuf: mark_interval(39389620, 232)
pictrs_1    | 2023-10-06T08:44:48.335466Z DEBUG sled::pagecache::iobuf: new highest interval: 39389620 - 39389851
pictrs_1    | 2023-10-06T08:44:48.336563Z DEBUG pop{queue_name="cleanup" worker_id=pict-rs-1-0}: sled::pagecache::iobuf: make_stable(39389851) returning
```

Give it a try on enterprise.lemmy.ml, thats where this is happening for me.

The auth check for delete endpoint is [not present in 0.18](https://github.com/LemmyNet/lemmy/blob/release/v0.18/crates/routes/src/images.rs).

**Comment by asonix** [comment] 2023-10-06 13:46
The logs you posted show pict-rs removing the alias and then removing the backing file from the filesystem.

I doubt pict-rs is capable of serving that file anymore. If your browser still shows the file, it's likely cached.

**Comment by asonix** [comment] 2023-10-06 14:04
Just confirmed on enterprise: deleting the image does work. Browser caching may make it seem like it doesn't, but if you try a hard refresh or opening the image URL in a private window, it is inaccessible

**Comment by Nutomic** [comment] 2023-10-17 10:47
True, closing this issue.

**Closed by Nutomic** 2023-10-17 10:47 UTC
Labels: bug

**Comment by MV-GH** [comment] 2023-10-17 10:49
Is the 204 fixed?

**Comment by Nutomic** [comment] 2023-10-17 13:40
That comes from pictrs. Whats wrong with 204?

**Comment by Nutomic** [comment] 2023-10-19 13:16
Sounds like a bug in pictrs, cc @asonix

**Comment by asonix** [comment] 2023-10-19 21:35
0.4.5 does fix that
