### ISSUE TITLE
Decentralized / multi instance accounts

### ISSUE THREAD

**Issue by Kryptortio** [LemmyNet/lemmy#3110] opened 2023-06-14 18:32 UTC
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support.
- [x] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

**Describe the feature request below**

**What**

When first joining Lemmy some might find it difficult to decide what instance to join so I think it would a good idea if there was an option for decentralized accounts. The main goal would be to protect your account/identity from getting lost if for example the instance goes down.

**How**

One possibility for solving this without resorting to some kind of central authority could be to add the option to sign your account with [public-key cryptography](https://en.wikipedia.org/wiki/Public-key_cryptography). Then if you create an account on a different server you could prove that they have the same identity by signing that one as well.

So you would need two new entries in your profile for your public key and a signature for the account to prove it's authenticity. It would also be nice if there was an easy way to export account data to keep saved with your private key but that's something that could be added later.

**Additional benefits**

Adding a public key also has the obvious benefit of allowing [e2e encryption](https://en.wikipedia.org/wiki/End-to-end_encryption) for private messages. This would also help with choosing an instance since you don't need as much trust of the owner. 

You could also use your key to sign posts and comments to verify that they were written by you and not someone who stole your account. 

Your private key could also be used to recover your password instead of using email. This might be preferable to some as your account could be more anonymous.

You could allow someone with a public key to log into any instance without having to create a new account. Then if the original instance comes back and starts federating any posts/comments made on different servers could be verified (if signed) and added to the account on the original server as well. This might also be useful for sharing some of the workload across instances if one of them is under heavy load, then you could use a different one until it recovers.

This could make it easier for someone to follow/block/ban the user across multiple instances.

**Further reading**

(Mastadon) [Adding GPG for verified toots](https://github.com/mastodon/mastodon/issues/928)

(Matrix) [Decentralised user accounts](https://github.com/matrix-org/matrix-spec/issues/246)

**Comment by Nutomic** [comment] 2023-06-14 20:56
[FEP-2100](https://codeberg.org/GNUsocial/fep/src/branch/fep-8485/feps/fep-2100.md) has a proposal along these lines. Apparently it is implemented in a [GNU social plugin](https://socialhub.activitypub.rocks/t/fep-8485-unbound-actor/2200/22) (the link is not working for me). However it would take a lot of work to make this production ready for Lemmy.

**Comment by Nutomic** [comment] 2023-06-14 21:05
Duplicate of https://github.com/LemmyNet/lemmy/issues/3100

**Closed by Nutomic** 2023-06-14 21:05 UTC
Labels: enhancement, federation

**Comment by silverpill** [comment] 2023-06-15 22:56
@Nutomic I think what OP described here is closer to the idea of identity proofs: https://codeberg.org/silverpill/feps/src/branch/main/c390/fep-c390.md

A user can link their pubkey identity to an actor, and when two actors are linked to the same identity, servers can treat these actors as different representations of the same account.

I'm using this as a basis for account migration mechanism in my microblogging application, and although it is not finished yet and there are several UX issues, this approach actually works and provides a solution to unexpected server shutdowns. My software is written in Rust, so some code can be re-used in Lemmy (I'm thinking about releasing a crate containing necessary cryptographic primitives).

**Comment by uis246** [comment] 2024-05-21 16:21
I think this should be reopened because it has different scope(account as opposed to community)

**Comment by dessalines** [comment] 2024-05-21 18:04
If someone wants to work on it, we'll re-open and assign it to them.
