### ISSUE TITLE
Allow instance migration for communities and users

### ISSUE THREAD

**Issue by Popkornium18** [LemmyNet/lemmy#3057] opened 2023-06-13 05:37 UTC
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support.
- [x] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

There are a number of things that can go wrong with Lemmy instances:

- Can be overloaded/unreliable
- Be abandoned by moderators
- Changes in moderation policies that users might not agree with

Because of reasons like this it would be great to have a mechanism in place to migrate your user and/or communities you moderate to other Lemmy instances.

**Comment by pdelbarba** [comment] 2023-06-13 22:24
Another thing to consider is it probably should be possible to voluntarily merge and/or fork communities as necessary.

**Comment by elishamint** [comment] 2023-06-14 13:12
Finally, here it is. May I ask, how is it done here, if an issue will require a discussion of greater scope, with possibly a lot of people wanting to take part? Can we do this here, or would it be better to have a little more structured discussion perhaps on Lemmy?
Reason for my asking is because this will finally address a major structural flaw in LemmyNet's implementation of ActivityPub (specifically, the lack of a _persistent_ global namespace for objects -- object IDs are bound to domains which are of course not persistent). If this gets solved though, then also that problem with internal links might be more easily resolved etc.
This is a core problem; the solution might be quite simple but it may take a bit of re-thinking from developers.

**Comment by paxcoder** [comment] 2023-06-16 13:57
or for example: admin switches to different instance.
then what?
the group should be somehow possible to bring into the new instance

**Comment by pwd-github** [comment] 2023-07-03 11:46
Duplicate of #1985 ?

**Comment by Atemu** [comment] 2023-07-03 13:22
This one also includes communities; perhaps that's what this issue should focus on.

**Comment by Houkime** [comment] 2023-07-12 06:25
On Misskey/Pleroma/Mastodon migration does not include post history, exactly for performance and network reasons.
What it does include is a redirect that makes all followers automatically resubscribe to the new user.

In the case of community I think it also needs to redirect all new incoming federated posts to this community (either from other lemmy instances or mentions from Mastodon) to the new community.

**Comment by Houkime** [comment] 2023-07-12 06:30
I would also like to mention in this discussion one real case of communities willing to move/merge:
[!android@lemmy.world](https://lemmy.world/c/android) trying to merge with [!android@lemdro.id](https://lemmy.world/c/android@lemdro.id)

**Comment by jherazob** [comment] 2023-07-12 09:06
I feel that using the Mastodon user migration as a model is a bad idea, if the source server is down you cannot migrate followers, and even if it's all OK your posts are not moved with you, also recently realized followed hashtags are not touched at all either, and not even exported at all in backups. The objective would be to migrate seamlessly as far as user experience is related. Yes, don't make it *too* easy and quick to prevent abuse, but it should still be easy enough.

Also i feel that having the same ticket for both community and user migration is a mistake, they're very different and unrelated cases with very different priorities.

**Comment by weirdbeardgame** [comment] 2023-07-19 19:29
Yeah, I'd like to see something that copied post and comment history as well if an instance migration does happen

**Comment by lionirdeadman** [comment] 2023-07-19 19:50
> Yeah, I'd like to see something that copied post and comment history as well if an instance migration does happen

This would be really hard as now you need to modify all old posts/comments to point back to the new account unless it simply points to the new alias.

**Comment by 8ullyMaguire** [comment] 2023-08-01 11:25
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem? *

Currently, the Lemmy API makes it difficult to fetch and push all read and saved posts for account migration purposes, as there is no instance-agnostic way to link any post when using Lemmy. This limitation hinders the development of account migration tools like LASIM[^1].

### Describe the solution you'd like. *

I propose adding a feature to the Lemmy API that allows fetching and pushing all read and saved posts for a user. This would enable account migration tools like LASIM to efficiently transfer user data between instances, improving the user experience and facilitating seamless account migration.

### Describe alternatives you've considered. *

An alternative solution could be to improve the search API to allow filtering by creator and community more efficiently. However, this may still require searching through numerous pages to find the desired post, which is not an optimal solution.

### Additional context

This feature request is related to the existing issue [Allow fetching list of liked and disliked posts #3401](https://github.com/LemmyNet/lemmy/issues/3401). Implementing this feature would greatly enhance the functionality of account migration tools and improve the overall user experience on Lemmy.

Citations:
[^1]: https://github.com/CMahaff/lasim

**Comment by jfryton** [comment] 2023-08-14 16:04
I think there should be two options available, one for community moderators and another for instance administrators. This could be useful for supporting different kinds of mergers or temporary closures like are possible on Reddit. 

For community moderators - introduce an option for community mods to enable a splash page when locking a community. Splash page would display a message and could include a URL to another community located elsewhere. Reddit provides three options with the private being the one that displays a message ![image](https://github.com/LemmyNet/lemmy/assets/35437877/94208b2f-0d42-4f45-902e-8211cb6e36fb). But for lemmy, it'd be useful to be able to click to dismiss the banner and still access the locked content. Example of what appears when visiting a subreddit set to private: 
![image](https://github.com/LemmyNet/lemmy/assets/35437877/3deaf4d6-2884-4f0e-a8dc-f3f7f37a8d89).

For instance administrators - similar to [#3048](https://github.com/LemmyNet/lemmy/issues/3048), introduce an option to link a URL to another community to automatically redirect. For example, https://lemdro.id/c/asklemmy would point to https://lemdro.id/c/asklemmy@lemmy.ml. It could also be useful to enable for communities within an instance - like if instance admin wanted to automatically redirect https://lemmy.world/c/apple to https://lemmy.world/c/apple_enthusiast (unless implementing the ability to rename instances is feasible then that would be preferable).

**Closed** 2023-10-20 11:30 UTC
Labels: enhancement, area: migration
