### ISSUE TITLE
Allow post creation from Friendica

### ISSUE THREAD

**Issue by xundeenergie** [LemmyNet/lemmy#2144] opened 2022-03-22 10:24 UTC
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Issue Summary

Posting a NEW posting from friendica in a lemmy-community fails

I think, it's similar to the friendica-federation bug a few weeks ago for commenting. The error-message seems the same.

### Steps to Reproduce

1. Join to a community on lemmy from friendica
2. Create a new posting

### Technical details

```
lemmy_1     | 2022-03-22T10:21:37.202728Z  INFO HTTP request{http.method=POST http.scheme="http" http.host=lemmy.schuerz.at http.target=/inbox otel.kind="server" request_id=492c3682-a6f0-4911-b86c-a93380c31f45}:shared_inbox: lemmy_apub::http: Received shared inbox activity {"@context":["https://www.w3.org/ns/activitystreams","https://w3id.org/security/v1",{"vcard":"http://www.w3.org/2006/vcard/ns#","dfrn":"http://purl.org/macgirvin/dfrn/1.0/","diaspora":"https://diasporafoundation.org/ns/","litepub":"http://litepub.social/ns#","toot":"http://joinmastodon.org/ns#","schema":"http://schema.org#","manuallyApprovesFollowers":"as:manuallyApprovesFollowers","sensitive":"as:sensitive","Hashtag":"as:Hashtag","directMessage":"litepub:directMessage","discoverable":"toot:discoverable","PropertyValue":"schema:PropertyValue","value":"schema:value"}],"id":"https://soc.schuerz.at/objects/4edd2508-2662-39a3-305d-8ca330868827/Create","type":"Create","actor":"https://soc.schuerz.at/profile/jakob","published":"2022-03-22T10:21:36Z","instrument":{"type":"Service","name":"Friendica 'Siberian Iris' 2022.05-dev-1452","url":"https://soc.schuerz.at"},"to":["https://lemmy.schuerz.at/c/test"],"cc":["https://www.w3.org/ns/activitystreams#Public","https://lemmy.schuerz.at/c/test/followers"],"object":{"id":"https://soc.schuerz.at/objects/4edd2508-2662-39a3-305d-8ca330868827","type":"Article","summary":"","inReplyTo":null,"diaspora:guid":"4edd2508-2662-39a3-305d-8ca330868827","published":"2022-03-22T10:21:36Z","url":"https://soc.schuerz.at/display/4edd2508-2662-39a3-305d-8ca330868827","attributedTo":"https://soc.schuerz.at/profile/jakob","sensitive":false,"context":"https://soc.schuerz.at/objects/4edd2508-2662-39a3-305d-8ca330868827#context","name":"Test from friendica","content":"<span class=\"h-card\"><a href=\"https://lemmy.schuerz.at/c/test\" class=\"u-url mention\">!<span>test</span></a></span><br><br>Test from friendica","contentMap":{"de":"<bdi>!<a href=\"https://lemmy.schuerz.at/c/test\" class=\"userinfo mention\" title=\"test\">test</a></bdi><br><br>Test from friendica"},"source":{"content":"![url=https://lemmy.schuerz.at/c/test]This is a Testcommunity[/url]\n\nTest from friendica","mediaType":"text/bbcode"},"attachment":[],"tag":[{"type":"Mention","href":"https://lemmy.schuerz.at/c/test","name":"@test@lemmy.schuerz.at"}],"to":["https://lemmy.schuerz.at/c/test"],"cc":["https://www.w3.org/ns/activitystreams#Public","https://lemmy.schuerz.at/c/test/followers"]},"signature":{"type":"RsaSignature2017","nonce":"b2cffb52849d97fa34217eec0ad18dee67e4725a7864d9cff408026672cb8636","creator":"https://soc.schuerz.at/profile/jakob#main-key","created":"2022-03-22T10:21:37Z","signatureValue":"CJaHnbhQGby60BEwB40+1R3lknAz6LtUTMiEXs+T8DTPHElKr0FkAW3KmfqQlhge5Q2eQb0n55cZUjFs+pR4RyOpvGvZelz2MXCidZUbrKLKuA5qrIP+134f6qZT2YlcLxxpvvesHCtMfzk7bt3sOqWllN2YgS2aCGYiz2oEvseeRVEod4wtrlYCSg/lPZIHLd3CFCglVAuM7OvV8gI0w+JyMsQ9x9z8OdNyPJ0r4FmktW1jbNv4U+9rWMrO3fi3wXTMuenhe2QaO5d0AJGdugXuLP1IE8ln2HEWlGeK6EVlxZvMwuaFPLNKf0vQEtB9RGvjpAa2C+GD6xaevQsG0P0Ui3Evdzvp4OHzuJ/y3Z/Wl64Y5wfYgsRu4AqcmRgtWLzP30G0DjZl+1lfxcUNARX265HtlD+CLFvJk3tu3YJJ4OaAdDQ8BV2HQuaXhf+VcV/HsjM7c32eTGlEbgfO+PNNdr4JF1GLIl518UnJNv8GearKJWhNLfCDmB5SBbq8TNm41Glc6dgIfBdCo94XrGdh8nM+n0H/qU9oMF+ru/lsO8NlzPzct3LbqUKxANhLaGaDKu7346D14/ipROH7VEckL6bOE8fFNQOIhDaDN8uik7zHrIkeo71qmGjCqujC9MpizyEtnHCsvtxTNUsqZylSGzdoRH8X7MaSWOyp+t8="}}
lemmy_1     | 2022-03-22T10:21:37.204832Z  WARN Error encountered while processing the incoming HTTP request: lemmy_server::root_span_builder: data did not match any variant of untagged enum SharedInboxActivities at line 1 column 3117
lemmy_1     |    0: lemmy_apub::http::shared_inbox
lemmy_1     |              at crates/apub/src/http/mod.rs:41
lemmy_1     |    1: lemmy_server::root_span_builder::HTTP request
lemmy_1     |            with http.method=POST http.scheme="http" http.host=lemmy.schuerz.at http.target=/inbox otel.kind="server" request_id=492c3682-a6f0-4911-b86c-a93380c31f45 http.status_code=400 otel.status_code="OK"
lemmy_1     |              at src/root_span_builder.rs:16
lemmy_1     |    2: tokio::task::runtime.spawn
lemmy_1     |            with kind=local task.name= loc.file="/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/task/local.rs" loc.line=302 loc.col=22
lemmy_1     |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/util/trace.rs:16
lemmy_1     |    3: tokio::task::runtime.spawn
lemmy_1     |            with kind=local task.name= loc.file="/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/task/local.rs" loc.line=302 loc.col=22
lemmy_1     |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/util/trace.rs:16
lemmy_1     |    4: tokio::task::runtime.spawn
lemmy_1     |            with kind=local task.name= loc.file="/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/task/local.rs" loc.line=302 loc.col=22
lemmy_1     |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/util/trace.rs:16
lemmy_1     |    5: tokio::task::runtime.spawn
lemmy_1     |            with kind=local task.name= loc.file="/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/task/local.rs" loc.line=302 loc.col=22
lemmy_1     |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/util/trace.rs:16
lemmy_1     |    6: tokio::task::runtime.spawn
lemmy_1     |            with kind=block_on task.name= loc.file="/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/task/local.rs" loc.line=466 loc.col=12
lemmy_1     |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/util/trace.rs:16
lemmy_1     | LemmyError { message: None, inner: data did not match any variant of untagged enum SharedInboxActivities at line 1 column 3117, context: "SpanTrace" }
```

**Comment by Nutomic** [comment] 2022-03-22 15:16
This activity creates an `Article`, which is not supported by Lemmy (we use `Page` for posts). We could add support for receiving this though, but first i would like to be sure that its the best solution. Is there any other way to make a post in Friendica which could result in a `Page`? Or some documentation which lists the objects used by Friendica? If you dont know, it woud be good to talk to a Friendica dev about this.

For reference, here is the activity properly formatted:
```
{
	"@context": [
		"https://www.w3.org/ns/activitystreams",
		"https://w3id.org/security/v1",
		{
			"vcard": "http://www.w3.org/2006/vcard/ns#",
			"dfrn": "http://purl.org/macgirvin/dfrn/1.0/",
			"diaspora": "https://diasporafoundation.org/ns/",
			"litepub": "http://litepub.social/ns#",
			"toot": "http://joinmastodon.org/ns#",
			"schema": "http://schema.org#",
			"manuallyApprovesFollowers": "as:manuallyApprovesFollowers",
			"sensitive": "as:sensitive",
			"Hashtag": "as:Hashtag",
			"directMessage": "litepub:directMessage",
			"discoverable": "toot:discoverable",
			"PropertyValue": "schema:PropertyValue",
			"value": "schema:value"
		}
	],
	"id": "https://soc.schuerz.at/objects/4edd2508-2662-39a3-305d-8ca330868827/Create",
	"type": "Create",
	"actor": "https://soc.schuerz.at/profile/jakob",
	"published": "2022-03-22T10:21:36Z",
	"instrument": {
		"type": "Service",
		"name": "Friendica 'Siberian Iris' 2022.05-dev-1452",
		"url": "https://soc.schuerz.at"
	},
	"to": [
		"https://lemmy.schuerz.at/c/test"
	],
	"cc": [
		"https://www.w3.org/ns/activitystreams#Public",
		"https://lemmy.schuerz.at/c/test/followers"
	],
	"object": {
		"id": "https://soc.schuerz.at/objects/4edd2508-2662-39a3-305d-8ca330868827",
		"type": "Article",
		"summary": "",
		"inReplyTo": null,
		"diaspora:guid": "4edd2508-2662-39a3-305d-8ca330868827",
		"published": "2022-03-22T10:21:36Z",
		"url": "https://soc.schuerz.at/display/4edd2508-2662-39a3-305d-8ca330868827",
		"attributedTo": "https://soc.schuerz.at/profile/jakob",
		"sensitive": false,
		"context": "https://soc.schuerz.at/objects/4edd2508-2662-39a3-305d-8ca330868827#context",
		"name": "Test from friendica",
		"content": "<span class=\"h-card\"><a href=\"https://lemmy.schuerz.at/c/test\" class=\"u-url mention\">!<span>test</span></a></span><br><br>Test from friendica",
		"contentMap": {
			"de": "<bdi>!<a href=\"https://lemmy.schuerz.at/c/test\" class=\"userinfo mention\" title=\"test\">test</a></bdi><br><br>Test from friendica"
		},
		"source": {
			"content": "![url=https://lemmy.schuerz.at/c/test]This is a Testcommunity[/url]\n\nTest from friendica",
			"mediaType": "text/bbcode"
		},
		"attachment": [],
		"tag": [{
			"type": "Mention",
			"href": "https://lemmy.schuerz.at/c/test",
			"name": "@test@lemmy.schuerz.at"
		}],
		"to": [
			"https://lemmy.schuerz.at/c/test"
		],
		"cc": [
			"https://www.w3.org/ns/activitystreams#Public",
			"https://lemmy.schuerz.at/c/test/followers"
		]
	},
	"signature": {
		"type": "RsaSignature2017",
		"nonce": "b2cffb52849d97fa34217eec0ad18dee67e4725a7864d9cff408026672cb8636",
		"creator": "https://soc.schuerz.at/profile/jakob#main-key",
		"created": "2022-03-22T10:21:37Z",
		"signatureValue": "CJaHnbhQGby60BEwB40+1R3lknAz6LtUTMiEXs+T8DTPHElKr0FkAW3KmfqQlhge5Q2eQb0n55cZUjFs+pR4RyOpvGvZelz2MXCidZUbrKLKuA5qrIP+134f6qZT2YlcLxxpvvesHCtMfzk7bt3sOqWllN2YgS2aCGYiz2oEvseeRVEod4wtrlYCSg/lPZIHLd3CFCglVAuM7OvV8gI0w+JyMsQ9x9z8OdNyPJ0r4FmktW1jbNv4U+9rWMrO3fi3wXTMuenhe2QaO5d0AJGdugXuLP1IE8ln2HEWlGeK6EVlxZvMwuaFPLNKf0vQEtB9RGvjpAa2C+GD6xaevQsG0P0Ui3Evdzvp4OHzuJ/y3Z/Wl64Y5wfYgsRu4AqcmRgtWLzP30G0DjZl+1lfxcUNARX265HtlD+CLFvJk3tu3YJJ4OaAdDQ8BV2HQuaXhf+VcV/HsjM7c32eTGlEbgfO+PNNdr4JF1GLIl518UnJNv8GearKJWhNLfCDmB5SBbq8TNm41Glc6dgIfBdCo94XrGdh8nM+n0H/qU9oMF+ru/lsO8NlzPzct3LbqUKxANhLaGaDKu7346D14/ipROH7VEckL6bOE8fFNQOIhDaDN8uik7zHrIkeo71qmGjCqujC9MpizyEtnHCsvtxTNUsqZylSGzdoRH8X7MaSWOyp+t8="
	}
}
```

**Comment by xundeenergie** [comment] 2022-03-22 18:35
I asked the friendica devs to have a look on this issue

**Comment by dessalines** [comment] 2022-03-22 18:57
Also, is `Page` demanded by any other platform? If no, then both ours should decide on one to use, instead of trying to build support for both.

**Comment by annando** [comment] 2022-03-23 05:48
Currently Friendica uses either `Article` (when the post contains a title) or `Note` when creating posts. Systems like Mastodon or Pleroma only are using `Note`. If we had to use `Page` to make the communication work with Lemmy, then we had to distinguish between different group implementations, thus requiring having some reliable way of knowing the system on the other side. We are using this `instrument` value for that purpose, so that other systems always know with whom they are speaking with.

**Comment by Nutomic** [comment] 2022-03-23 15:43
We could switch from `Page` to `Article`, but there are also other projects which send `Page` (lotide and GNU social). So unless they do the same switch, it seems more reasonable for Lemmy to keep sending `Page` for backwards compat, and also accept receiving `Article`, as they seem equivalent. cc @vpzomtrrfrt 

@annando It also needs another change which is not merged yet. Try with ds9.lemmy.ml, that has a fixed version which should federate fine. Also, it would be good if you could send a list of all activitypub objects/activities sent by Friendica, so that i can add support for all of them at once.

**Comment by diogogithub** [comment] 2022-03-23 15:53
We adopted `Page` because we wanted to be friendly with Lemmy's Groups. GNU social v3 (the only release with groups over ActivityPub) is not being used by any instance. For us, switching from `Page` to `Article` is completely harmless, and the latter seems to fit better in this context.

@annando We don't have any platform-specific code in GNU social, and would like to avoid having to, but we will add the instrument property to our activities when federating out.

For reference:
* Article: https://www.w3.org/TR/activitystreams-vocabulary/#dfn-article
* Page: https://www.w3.org/TR/activitystreams-vocabulary/#dfn-page

**Comment by Nutomic** [comment] 2022-03-23 16:26
Okay so it seems the best solution for Lemmy is to accept receiving both `Page` and `Article`, and treat them as equivalent. But we would keep sending as `Page`, to avoid any incompatibility with older Lemmy versions or with other software.

**Comment by annando** [comment] 2022-03-23 17:35
@diogogithub we don't have any platform specific code in Friendica either - and we really want to avoid that as well. But I see it like with the "Nodeinfo" mechanism. It is nice to know each other.

Concerning the differences between the two types: AFAIK all these fields can be used for both types, so we are safe here.

@Nutomic accepting both `Page` and `Article` (and maybe `Note`?) seems like a good idea. It fits into the "Robustness principle".

**Comment by annando** [comment] 2022-03-23 18:58
@Nutomic with manually set the type to `Page` the message arrived at the test group: https://ds9.lemmy.ml/post/13652 - that's great!

**Comment by Nutomic** [comment] 2022-03-23 21:10
Great! Could you please send json of your activitypub objects and activities? Basically whats in the link below, for inclusion in our tests. Dont make a PR, as it needs code changes as well. Once i have that, i will make the necessary changes.

https://github.com/LemmyNet/lemmy/tree/main/crates/apub/assets

**Comment by annando** [comment] 2022-03-24 04:31
Do you want the whole set of articles, pages, comments, likes and dislikes?

Here is an `Article`:
```
{
    "@context": [
        "https://www.w3.org/ns/activitystreams",
        "https://w3id.org/security/v1",
        {
            "vcard": "http://www.w3.org/2006/vcard/ns#",
            "dfrn": "http://purl.org/macgirvin/dfrn/1.0/",
            "diaspora": "https://diasporafoundation.org/ns/",
            "litepub": "http://litepub.social/ns#",
            "toot": "http://joinmastodon.org/ns#",
            "schema": "http://schema.org#",
            "manuallyApprovesFollowers": "as:manuallyApprovesFollowers",
            "sensitive": "as:sensitive",
            "Hashtag": "as:Hashtag",
            "directMessage": "litepub:directMessage",
            "discoverable": "toot:discoverable",
            "PropertyValue": "schema:PropertyValue",
            "value": "schema:value"
        }
    ],
    "id": "https://pirati.ca/objects/ec054ce7-5162-3bf2-504c-16d024994850/Create",
    "type": "Create",
    "actor": "https://pirati.ca/profile/heluecht",
    "published": "2022-03-24T04:23:44Z",
    "instrument": {
        "type": "Service",
        "name": "Friendica 'Siberian Iris' 2022.05-dev-1452",
        "url": "https://pirati.ca"
    },
    "to": [
        "https://ds9.lemmy.ml/c/testcom"
    ],
    "cc": [
        "https://www.w3.org/ns/activitystreams#Public",
        "https://ds9.lemmy.ml/c/testcom/followers"
    ],
    "object": {
        "id": "https://pirati.ca/objects/ec054ce7-5162-3bf2-504c-16d024994850",
        "type": "Article",
        "summary": "",
        "inReplyTo": null,
        "diaspora:guid": "ec054ce7-5162-3bf2-504c-16d024994850",
        "published": "2022-03-24T04:23:44Z",
        "url": "https://pirati.ca/display/ec054ce7-5162-3bf2-504c-16d024994850",
        "attributedTo": "https://pirati.ca/profile/heluecht",
        "sensitive": false,
        "context": "https://pirati.ca/objects/ec054ce7-5162-3bf2-504c-16d024994850#context",
        "name": "From Friendica to Lemmy",
        "content": "Hello Lemmy!",
        "contentMap": {
            "de": "<bdi>!<a href=\"https://ds9.lemmy.ml/c/testcom\" class=\"userinfo mention\" title=\"testcom\">testcom</a></bdi> Hello Lemmy!"
        },
        "source": {
            "content": "![url=https://ds9.lemmy.ml/c/testcom]testcom[/url] Hello Lemmy!",
            "mediaType": "text/bbcode"
        },
        "attachment": [],
        "tag": [
            {
                "type": "Mention",
                "href": "https://ds9.lemmy.ml/c/testcom",
                "name": "@testcom@ds9.lemmy.ml"
            }
        ],
        "to": [
            "https://ds9.lemmy.ml/c/testcom"
        ],
        "cc": [
            "https://www.w3.org/ns/activitystreams#Public",
            "https://ds9.lemmy.ml/c/testcom/followers"
        ]
    },
    "signature": {
        "type": "RsaSignature2017",
        "nonce": "d1b75df08009e59510606604758732d499c3c385b4ce6ee374e6d8c2ee86230b",
        "creator": "https://pirati.ca/profile/heluecht#main-key",
        "created": "2022-03-24T04:26:55Z",
        "signatureValue": "nmAyEh/6Zq5Ki0AYtTFDxGom67HOTuWDzToGuEorm0cOzsNv7OIUgGjkOtKOVJA91J7NaS1hCCSMrhM7HCurIQyE3wDa3NAzhDQORVbbRF6+NxpB70nlJaOaInAS4bmVsed0rBg2aYQfrai0QB4F8zhN8JIa6zu0EAtLMh0vkzDFOCeGbvahLkSJO+sZKEqAWsr3VfMmJ8TCd+JWUKyy2/Hd87czj58oMk8yKzKKHlL0z+rbP2LbpaZspHCT+kfkZy0IOjrdcvgENCwCsPA9Y5kJmH08NXkKG6D6CGIti2zhnkNMxBuZ5sPU6PcE535J/UjfrGN3ikGoxjO3bRqFI42TbhTxBRk/yMv0BVIPLzAbPAJdJ6VAwq5UAjI6G4ejjQ9LKRqjxlG96PNo+YVKFhKTmmSMWLmdWckC8PRL2nZvq4UtIf4cd+p1pQ+TnfjD8ZHadb10tHJEXrUIz9Q/pWmfLvTSodbdYRSurWFNYaJ3gCEjSoCoHxA7GeEoivSA0IuuDRKo0tFEv09/BA9m8m04kjQ8q/ZxAb2P4TICcPZrhGKoDkRTc1P5vSNeuw8GFV/5Dy7NWKarJUlzCA1OoHo/cKWhY3fVc/lANssTyxsMakp4ofN0zRoToQAx6hDLgESJcn04tUO4JvluYkGggBEhPfhLNSyc6yUWahjh9Gc="
    }
}
```

From my tests it seems as if a title (`name`) is always needed, isn't it?

**Comment by annando** [comment] 2022-03-24 07:08
@Nutomic just some additional information: I'm currently preparing a change in Friendica so that posts that contain an external url will be a `Page` while a post without it, will be an `Article` or `Note`.

The difference between `Article` and `Note` is that a `Note` doesn't have got a title. Since Lemmy requires a title, it would be okay for me to only accept `Article` and `Page`.

Also there is one significant difference between those two types: On an `Article` the `url` will always point to the original URL of the post, while an `url` from a `Page` will point to the linked paged. So it would be the best, if Lemmy could handle that value differently concerning these two types (at least when receiving them).

**Comment by Nutomic** [comment] 2022-03-28 12:02
@annando Perfect, thank you! All I had to change was accept `Article` type for posts, thats it. Your change in https://github.com/friendica/friendica/pull/11375 is really not necessary though, we dont make any difference between posts with or without url. Well it will get you some partial compatibility with older Lemmy versions.

> Also there is one significant difference between those two types: On an Article the url will always point to the original URL of the post, while an url from a Page will point to the linked paged. So it would be the best, if Lemmy could handle that value differently concerning these two types (at least when receiving them).

This is strange for me. We already show a link which points to the post's original instance (based on the id field). You can for example see it [on this page](https://ds9.lemmy.ml/post/15552) (the colored fediverse icon). I dont see any reason to (ab)use the url field to send this url a second time. Current behaviour will be that such articles will have the content rendered in Lemmy, and also have the title link to Friendica, so there are two ways to read the same text which might be confusing. To avoid this, we would have to ignore the url field for all articles, which seems strange (and would cause problems for other software that tries to create an article with url).

**Comment by annando** [comment] 2022-03-28 12:50
We currently don't support the chat messages. But this sounds interesting.

Concerning this `Article` thing: On a lot of systems in the Fediverse a post is reachable via two different URL. One is used for the technical stuff and the other is the link to the post when watched via a regular user. So the message with the ID `https://pirati.ca/objects/ec054ce7-4962-3bea-1323-2bb743505014` is accessible via the URL `https://pirati.ca/display/ec054ce7-4962-3bea-1323-2bb743505014`. This is a common pattern that is also used for example by Mastodon. The `Note` with the ID `https://mastodon.social/users/fsfe/statuses/108033351292131346` for example is using the URL `https://mastodon.social/@fsfe/108033351292131346` when displayed. Because of this they present this value in the `URL` field.

Since we also have got a look at the requested content types we always return the requested content (either the JSON content or the HTML content). But there are systems out there that always return the JSON content at their `ID` URL.

The best way to cope with this is indeed to have different treatments for the different types. The easiest solution for Lemmy surely would be to simply drop the content of the `URL` field on incoming `Article` posts.

**Comment by Nutomic** [comment] 2022-03-28 13:58
We could do that, but it would lead to very unexpected behaviour if some other software tries to create an `Article` which links to an external website via `url` field. That link would be silently dropped, and it would be complicated to figure out why. 

I think the real problem here is that we are using a single field for two different purposes. One, in Lemmy the `url` field is for links to external websites, and two, in Friendica it is used for the canonical url of that object. [activitystreams-vocabulary](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-url) defines url as "Identifies one or more links to representations of the object". So it seems your usage is correct and ours is wrong. I dont see any other field which could be used for this purpose, so it seems we would have to add a custom field? Honestly I dont like that idea, as `url` is a very fundamental part of Lemmy, and it would cause compatibility problems with a lot of other software.

**Comment by annando** [comment] 2022-03-28 14:19
From my point of view the `url` field does serve different purposes depending of the type. So with `Article` and `Note` it refers to this "representation" of the object. And with the type `Page` the `url` refers to the external page. But we can also argue that this "representation" for a `Page` is the referred page and for `Article` it is the post itself. So this is no violation of the standard.

Best would be that for `Article` the content of `url` is used for the link to the federated post, while for `Page` the `id` is used for that purpose. Then the `url` is used for the preview of the external page.

**Comment by Nutomic** [comment] 2022-03-28 14:34
Maybe that makes sense from Friendica perspective. But for Lemmy the only change i made is that `Article` can be received, sending is still done entirely using `Page`. So Lemmy can send `Page` with only external link as `url`, only text body as `content`, or both of those, or neither (only `name`). Lemmy doesnt use the `url` field to refer to the object representation. 

So i'm not really sure what to do. I think its worth discussing this with other project devs as well, before making any decision (maybe on socialhub).

**Comment by diogogithub** [comment] 2022-03-28 20:58
Okay, I guess there are a couple of different issues on the table...

> @annando: From my point of view the url field does serve different purposes depending of the type. So with Article and Note it refers to this "representation" of the object. And with the type Page the url refers to the external page. But we can also argue that this "representation" for a Page is the referred page and for Article it is the post itself. So this is no violation of the standard.

Although this makes sense. Because of this:

> @annando: Since we also have got a look at the requested content types we always return the requested content (either the JSON content or the HTML content). But there are systems out there that always return the JSON content at their ID URL.

GNU social is using the `url` attribute, when available, for the permalink: https://code.undefinedhackers.net/GNUsocial/gnu-social/src/branch/v3/plugins/ActivityPub/Util/Model/Note.php#L164

On the other hand, we had a Bookmarks plugin in version 2, that isn't federating via ActivityPub yet. The way we had thought of federating it was with a details html element in the `content`, and the link to the webpage would be a source with mediaType https://www.rfc-editor.org/rfc/rfc2483#section-5.

Something like:
...
```json
...
"type": "Page",
"title": "The title of this post about GNU",
"content": "<details><summary>Some briefing of what I'm sharing about GNU</summary>Let me elaborate more on my thoughts</details>",
"mediaType": "text/html"
"source": {
  "content": "http://gnu.org\r\n",
  "mediaType": "content-type text/uri-list"
}
...
```

Nonetheless, I agree that moving this to SocialHub would be a good idea.

**Comment by vpzomtrrfrt** [comment] 2022-03-28 21:06
I don't think the source field is correct for that either, since it's specified as "source from which the content markup was derived" which it wouldn't be if the user is adding their own comments

Maybe a Link in `attachment` or `tag`?

**Comment by annando** [comment] 2022-03-29 08:13
@diogogithub like @vpzomtrrfrt suggested, I think that an `attachment` would be the best solution.

**Comment by diogogithub** [comment] 2022-03-29 11:35
@vpzomtrrfrt and @annando  I agree. The main reason why we wrote that draft idea I shared, was because we didn't want to parse the content of type `text/plain` differently in function of the object Type to extract the Summary and Description of the bookmark.

```
"type": "Page",
"title": "The title of this post about GNU",
"content": "<details><summary>Some briefing of what I'm sharing about GNU</summary>Let me elaborate more on my thoughts</details>",
"mediaType": "text/html"
"source": {
  "content": "Bookmark: http://gnu.org
Summary: Some briefing of what I'm sharing about GNU
Description: Let me elaborate more on my thoughts",
  "mediaType": "text/plain"
}
"attachment": [
  {
    "url": "http://gnu.org",
    "type": "Document",
    "mediaType": "text/html"
  }
]
```

**Closed** 2022-03-29 15:48 UTC
Labels: enhancement, federation

**Comment by vpzomtrrfrt** [comment] 2022-03-29 18:46
Started a SocialHub thread to further discuss the semantics of link posts: https://socialhub.activitypub.rocks/t/explicitly-attached-links/2357

**Comment by raphaeljolivet** [comment] 2022-11-08 12:11
Hi, 

I really feel that being able to create new topics from remote instances would be a **game changer**.
Lemmy would de facto become the "groups feature" the Fediverse is missing so much.

Putting Mastodon is the game would really help.

Do you have a specific issue to track federation with Mastodon ? 
Or is it ok to comment on this one ?

My understanding at this point is that mastodon only sends **Notes**, missing a title.

One workaround would be to consider the first sentence of a Note as title. 
If we want to enforce it more, we could force an _empty line_ between title and body, or force a _custom syntax_ (like [title] for instance).

In any case, a federated user sending a bad request (bad type of message, bad format, anything) should be informed it has failed and why : maybe with a private message to him ? 
I don't know if this follows ActivityPub protocol : are they recommendation on how to handle user errors / feedbacks ?

Anyway, thanks for this amazing work !

**Comment by Nutomic** [comment] 2022-11-08 14:09
@raphaeljolivet Thats completely offtopic, open a new issue or use the search function.
