### ISSUE TITLE
Fediverse comment does not shows everywhere

### ISSUE THREAD

**Issue by skariko** [LemmyNet/lemmy#2341] opened 2022-06-29 13:37 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When a user create a post on a different Lemmy server, the fediverse comment (example from Mastodon) are displayed only on the original server author and not on the server where the post were created.

### Steps to Reproduce

1. Create a post on a different Lemmy server, example: I have created a post from feddit.it user to lemmy.ml community (https://lemmy.ml/post/341993)
2. Comment the post from a Mastodon account
3. The comment from Mastodon are displayed only on feddit.it (author's server) and not on lemmy.ml (where the post are created):

Original post: https://lemmy.ml/post/341993
Post from author's server: https://feddit.it/post/18730

**Comment by Nutomic** [comment] 2022-06-30 09:43
This is a duplicate of https://github.com/LemmyNet/lemmy/issues/2218#issuecomment-1106433626. Basically Mastodon doesnt send the new comment to lemmy.ml, so the server doesnt know about it at all.

**Closed by Nutomic** 2022-06-30 09:43 UTC
Labels: bug
