### ISSUE TITLE
Fetch and Push All Read and Saved Posts for Account Migration

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#3582] opened 2023-07-11 08:41 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem? *

Currently, the Lemmy API makes it difficult to fetch and push all read and saved posts for account migration purposes, as there is no instance-agnostic way to link any post when using Lemmy. This limitation hinders the development of account migration tools like LASIM[^1].

### Describe the solution you'd like. *

I propose adding a feature to the Lemmy API that allows fetching and pushing all read and saved posts for a user. This would enable account migration tools like LASIM to efficiently transfer user data between instances, improving the user experience and facilitating seamless account migration.

### Describe alternatives you've considered. *

An alternative solution could be to improve the search API to allow filtering by creator and community more efficiently. However, this may still require searching through numerous pages to find the desired post, which is not an optimal solution.

### Additional context

This feature request is related to the existing issue [Allow fetching list of liked and disliked posts #3401](https://github.com/LemmyNet/lemmy/issues/3401). Implementing this feature would greatly enhance the functionality of account migration tools and improve the overall user experience on Lemmy.

Citations:
[^1]: https://github.com/CMahaff/lasim

**Comment by lionirdeadman** [comment] 2023-07-20 21:47
I think this is ultimately a duplicate of https://github.com/LemmyNet/lemmy/issues/3057

**Closed by lionirdeadman** 2023-07-20 21:47 UTC
Labels: enhancement
