### ISSUE TITLE
Remote posts are hidden in local community

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1302] opened 2020-12-02 16:18 UTC
Noticed this while testing something else. The problem looks pretty simple, when viewing a local community (like [this one](https://voyager.lemmy.ml/c/main)), it only displays local posts. If you go to the [front page](https://voyager.lemmy.ml/), you can see many posts in the same community that simply werent shown before. Take [this post](https://voyager.lemmy.ml/post/125) as example.

**Post is shown on the frontpage as expected**:

![Screenshot_20201202_171624](https://user-images.githubusercontent.com/1044450/100899549-e0cc1f80-34b9-11eb-999a-7c813db2711f.jpg)

**Post is nowhere to be found when viewing main directly**: (both screenshots are taken directly on voyager)

![Screenshot_20201202_171641](https://user-images.githubusercontent.com/1044450/100899586-eb86b480-34b9-11eb-94a9-870eb4da2422.jpg)

**Comment by dessalines** [comment] 2020-12-02 21:00
Methinks this is a dupe of #1283 :

```
lemmy=# select local, community_local, community_actor_id from post_view where id = 125 and user_id is null;
 local | community_local |       community_actor_id
-------+-----------------+---------------------------------
 f     | t               | https://voyager.lemmy.ml/c/main
```

There's a chance this filter should be `community_local`, and not local: https://github.com/LemmyNet/lemmy/blob/main/lemmy_db/src/post_view.rs#L283

But that shouldn't affect this here, since you're a local user, making a post to a local community.

**Closed** 2020-12-03 11:55 UTC
Labels: bug, federation
