### ISSUE TITLE
Moving user profile to a new instance

### ISSUE THREAD

**Issue by vin047** [LemmyNet/lemmy#1985] opened 2021-12-10 00:40 UTC
### Is your proposal related to a problem?

Unable to move my user profile from one instance to another.

### Describe the solution you'd like

An option to move my user profile, complete with post and comment history and saved posts to a new instance.

### Describe alternatives you've considered

Creating a new profile with the same user handle on a new instance. Unfortunately that won't save post and comment history and saved posts. It also doesn't preserve account settings like blocked users etc.

### Additional context

I thought about whether this is necessary – with email you don't "move" accounts to a new server after all. But email is a form of communication and doesn't have the notion of "profile history". Social media does. It seems to me then that a users profile on Lemmy is more than just a communication endpoint. So the ability to move to a different instance, especially if you later on disagree with the way a particular instance is being run, seems important to me.

**Comment by Nutomic** [comment] 2021-12-11 13:38
Or you could just put a link to your old account into your bio. So this might be a useful feature, but very very low priority.

More useful could be import/export of settings and subscriptions (also much easier to implement).

**Comment by dessalines** [comment] 2021-12-12 02:13
I also don't fully understand how mastodon does this. Is it recreating toots in the past with no replies?

**Comment by Nutomic** [comment] 2021-12-12 16:39
No idea. And there seem to be no docs about the implementatio either (as usual).

**Comment by vin047** [comment] 2021-12-12 17:49
> More useful could be import/export of settings and subscriptions

Yes I think import/export of settings and subscriptions would fulfil this requirement, since lemmy doesn't have profile karma (anymore).

**Comment by Nutomic** [comment] 2021-12-14 13:23
Then its a duplicate of #506.

**Comment by Atemu** [comment] 2023-06-12 01:34
Export/import functionality is nice but it can't facilitate users moving from one instance to another because the content they have produced would still be linked to the old account.

**Comment by Gladox114** [comment] 2023-06-13 16:49
> Then its a duplicate of #506.

While the priority suddenly changed to just exporting subs shouldnt mean it should be closed, at least not in others people favor.

I see myself stuck on lemmy.ml because I made posts and still would want to get messages from my old posts on my old instance. I cant be the only one who has this urge to not switch the instance because the account is not transferable, but I would want to because lemmy.ml is struggling.

**Comment by calculuschild** [comment] 2023-06-13 21:05
Found this after being asked by multiple people how to do this coming from Reddit.

> I think import/export of settings and subscriptions would fulfil this requirement, since lemmy doesn't have profile karma (anymore).

The problem is, a (Reddit) account is much more than just your Karma points. It's the persona of your username and your associated post history, etc. I find myself looking back through my old posts all the time. Whether it's to delete something I realized contains too much personal information, to locate an old private messsge I made to someone, or to edit an old post when someone asks a question in a comment months later. 

I certainly don't want to be locked into a failing instance just to retain editing access to my old posts. There's s reason phone companies let you keep your phone number when you get a new device; switching addresses and personas is a hassle.

Compare to an MMORPG: "Don't worry about which server you choose; your character can cross-play with everyone!" But they fail to tell you that you have to start a brand new character and forfeit all your progress if you want switch servers with better ping. Just importing subscriptions is like getting to keep your unlocked cosmetics, but the effort building your character is lost.

**Comment by PoorPocketsMcNewHold** [comment] 2023-06-14 21:01
This feature should help people already on big servers, migrate on other ones for better Federation.
Comming from myself, a lemmy.nl user.

**Comment by Venthe** [comment] 2023-06-14 21:40
This is the single thing stopping me from using lemmy

**Comment by eitland** [comment] 2023-06-15 05:38
I think the concept several comments here seems to be talking about without naming is "nomadic identity" which (I think) was first implemented in Red Matrix which (I think) in turn became Hubzilla.

AFAIK nomadic identity is supported both by [Hubzilla ](https://hubzilla.org/page/hubzilla/discover) which seems to be the canonical implementation these days and [Streams](https://codeberg.org/streams/streams) which seems to be a cleaned up version of Hubzilla with less features and more  QA.

I am experimenting with Hubzilla on my account here BTW: https://zotum.net/channel/erik

**Comment by jakariyab** [comment] 2023-08-02 18:16
I can see how it can be hard to implement such as creating a new account in a new instance and be able to retain your old posts/comments from another account from another instance! How about some type of user id linking between the old and new id in the backend so the old account's history (posts/comments/activities) also gets shown/loaded with the new user id? (When clicking on the profile of course) And importing/exporting settings and subscriptions can be done too... Giving a somewhat complete user profile migration!? (Just my 2 cents)

**Comment by DraconicNEO** [comment] 2023-08-15 01:16
I really hope we can get this or some kind of real account migration feature like what Mastodon has, it's really frustrating having your account locked to a specific Instance it was created on with you only being able to edit or change the posts and comments from that specific instance. Account Migration on Lemmy is an absolute must, not being able to do it essentially means for better or for worse Instance owners own your account, this is particularly bad when it comes to defederation and the blocking of communities.

**Comment by Nutomic** [comment] 2023-09-29 15:03
https://github.com/LemmyNet/lemmy/pull/3976

**Closed by Nutomic** 2023-09-29 15:03 UTC
Labels: enhancement, extra: popular, area: migration

**Comment by Atemu** [comment] 2023-09-29 15:39
@Nutomic https://github.com/LemmyNet/lemmy/issues/1985#issuecomment-1586438679 still applies, does it?

**Comment by dessalines** [comment] 2023-09-29 18:14
Yes it does, this PR only deals with a user's settings being portable, not their historical content.

We can't import / rewrite historical data unfortunately. IE a comment you made months ago in reply to another comment can't be "overwritten historically" via an import.

There is #506 yet to be done, but that still won't allow history-rewriting, just a full account data export.

**Comment by Spunkie** [comment] 2023-09-29 22:09
I agree this issue is not yet resolved, can you please reopen it @Nutomic 
___
For now a possibly easier step in the direction of a full account move is simply a user setting that allows setting an account to forward to a new account. Exposing this forwarding setting on the public API would also allow other servers to reestablish subscriptions.


I guess this would also allow other servers to add an addition UI overlayed on top of rendering old posts/comments that would show info of both the old and new forwarded account. Without actually having to edit/rewrite the original post/comment on the old server.

**Comment by calculuschild** [comment] 2023-09-29 23:39
> a user setting that allows setting an account to forward to a new account.

Or similarly, some kind of account linking feature? Allow users to link multiple accounts and give them all shared access to historical data?

**Comment by dessalines** [comment] 2023-09-30 00:36
I would rather not codify any account forwarding, just rather let ppl optionally link any other accounts they'd like to in their new or old bios. That's much simpler and more versatile.

@Spunkie what else does this need to be resolved?

**Comment by Spunkie** [comment] 2023-09-30 01:33
@dessalines Codifying account forwarding, aka moving instances is basically what this whole issue is about. People want to be able to move between instances without feeling like they have to take a loss.

Losing all your current subscribers, and all future traffic, and all future conversations that stem from your "old" accounts content is clearly a heavy loss and leads to people feeling locked in to their current instance.

I don't think a "link in your bio" nor a user settings export meaningfully remedies these issues.

**Comment by dessalines** [comment] 2023-09-30 02:00
> Losing all your current subscribers,

You can't subscribe to users in lemmy. 

Also how is a box that says 'profile moved to X', any different than than that exact same line in your old bio(other than it being less versatile because you could only link one account)? 

> and all future traffic, and all future conversations that stem from your "old" accounts content

How does mastodon migrate your account history?

**Comment by calculuschild** [comment] 2023-09-30 02:07
> Losing all your current subscribers,

>> You can't subscribe to users in lemmy.

I think what they mean is losing the credibility/goodwill associated with your account. Your online persona builds up a track record over time and losing your connection to that legacy can be a pain to recover from.

**Comment by Kommynct** [comment] 2023-09-30 22:56
They can trust it's still you because you put a link to the new profile on the old one and said you're moving the account, right?

**Comment by Atemu** [comment] 2023-10-01 02:58
It's also about getting messages from replies to your old posts, DMs, retaining moderator status and your votes.

**Comment by DraconicNEO** [comment] 2023-10-01 03:22
> It's also about getting messages from replies to your old posts, DMs, retaining moderator status and your votes.

Yeah and not to mention that if you transfer them to the new server they'll still be there and accessible if the old one goes offline, not the case though if you're just pointing a link at the old account.

**Comment by Baerbeisser** [comment] 2024-01-08 13:26
I'm in this boat currently, my instance got unbearable unreliable and slow the last month.
There's [LASIM](https://github.com/CMahaff/lasim) but as you can see there, it can only copy some parts, last update 5 months ago.
Especially comment history and saved posts would be important.

**Comment by Nutomic** [comment] 2024-01-08 14:00
Lemmy 0.19 has a builtin import/export functionality for user data.

**Comment by Baerbeisser** [comment] 2024-01-08 15:46
Cool! So the apps aren't up to speed then?

**Comment by Atemu** [comment] 2024-01-08 16:25
As mentioned before, import/export is adjacent but not the same as account migration.

The functionality requested here does not exist, no matter which app.

**Comment by 8ullyMaguire** [comment] 2024-03-02 10:27
https://github.com/LemmyNet/lemmy/issues/4493

**Comment by Aaargh20318** [comment] 2025-05-23 11:30
> I would rather not codify any account forwarding, just rather let ppl optionally link any other accounts they'd like to in their new or old bios. That's much simpler and more versatile.

Account forwarding is not the solution, a full migration feature is needed. I'm currently running into this issue because the instance I'm on has announced they will be shutting down in a few months. You can't exactly put a message in your bio if the instance that profile is on no longer exists.  Lemmy instances will come and go, it will not exactly instil confidence in the ecosystem as every time an instance shuts down all users lose everything.  At the very least there needs to be some way for another instance to 'adopt' all user accounts from a instance that will be shutting down.

**Comment by Nutomic** [comment] 2025-05-26 10:17
That would mean creating duplicates of all the posts and comments, or getting other instances to change the ids of all the existing posts. It is completely impractical and I dont think any Fediverse platform allows that.

**Comment by Atemu** [comment] 2025-05-26 10:43
We should still desire proper account mobility between instances but what @uniquePWD proposed sounds like a very good first step indeed; a proper, standardised, verifiable mean of communicating that an account has moved just like mastodon has it.

When the protocol is amended (or a feasible solution thought up that doesn't require a protocol change) which would allow for proper account mobility, then we can re-open this issue. (It should remain closed until that point is in sight as it wouldn't be actionable otherwise.)

**Comment by eeriemyxi** [comment] 2025-05-26 11:09
I wonder what happens when an instance is closed, do the user history of that instance disappear from other instances at some point? If not, then I wonder if something like an account migration could be simulated on the client-side instead.

For example, when viewing a post, if a particular comment is found whose poster's instance has been closed but the user specified a redirect profile (the migrated profile or whatever), then the client could try to fetch the profile of migrated profile and display that instead. And if the user of the client tries to reply to the comment, the client could instead somehow notify the migrated profile instead. 

Obviously for this kind of feature there are few things that instances must support:
- a setting that lets users put a redirect link to their migrated profile.
- instances should be advised to cache the migrated profile info whenever feasible
- a system which lets other instances notify users of another instance

> [!NOTE]
> I don't know if this would actually work. It's just a random idea that I had.

**Comment by Nutomic** [comment] 2025-05-26 11:52
If an instance is down then posts, comments and user profiles from that instance are still visible on other Lemmy instances ([example](https://lemm.ee/c/freemediaheckyeah@lemmy.fmhy.ml)).

**Comment by dessalines** [comment] 2025-05-27 18:04
> Why would there be a need to redirect after full account migration? With full migration I mean moving everything, including comments made, etc. to the new instance and propagate this change to all federated instances.

This is called rewriting history, and its not possible in distributed systems, any more than its possible to get every email server to rewrite their email histories when you get a new email address.

As @Nutomic stated, if an instance plans to close down, you need to make a new account elsewhere, and link the new one in your old bio.

**Comment by Smona** [comment] 2025-05-28 19:49
@Nutomic yes, but does that aggregate content from the old account to the new one? Ultimately without a pointer from the old account to the new one, there's no way to associate content from the old account with the new one, right?

Honestly nomadic identity as described above would be a much simpler solution to this problem, but it does put key management in the hands of the users, which is a real UX problem. The "tree of account pointers" alternative i described was just an attempt to move this conversation forward, because I feel like there is a bit of a disconnect going on here. It's been suggested that preserving attribution through instance changes is incompatible with a decentralized design, e.g. that it requires duplicating history or re-writing history, and my suggestion was an attempt to demonstrate that that's not necessarily true.

It sounds like you believe that a (non-machine-readable) link from new account to old is sufficient to resolve the concern of losing attribution for old content when moving between instances for potential users, but for someone like me it isn't, because there would still be no way for someone viewing an old post of mine to find my current identity without manually traversing a chain of bio links (assuming I even had time to add one to my bio before the previous instance shut down). There are potential solutions to this problem that would make Lemmy more suitable to unseat Reddit, which is ultimately what I hope to see from the project, but without willingness from the maintainers those solutions will never be considered, much less put to the test.

Ultimately it is your project and your hard work that has brought Lemmy to the (already quite impressive) point where it is today, so it's your decision. But it is sad to see a promising project unnecessarily limit itself in ways that prevent users who believe in its mission from making the switch. I'll just continue to wait and hope that y'all change your minds.

**Comment by dessalines** [comment] 2025-05-28 21:46
@Smona This isn't a problem unique to lemmy. It affects **all distributed systems**, including the entire fediverse, and others like email. 

If you change your email address, you can't get every other email service to agree to rewrite their histories to update to your new one either.

**Comment by Smona** [comment] 2025-05-29 02:24
Well sure, in the case of email there's no mechanism for address migration or redirecting built into the protocol, and that ship has probably sailed at this point. But I think your claim that this problem is universal & inherent to distributed systems is demonstrably false. Even within the fediverse, it seems like Mastodon [does have some version](https://docs.joinmastodon.org/user/moving/#migration) of both profile redirecting and migration, which proves this isn't some fundamental, theoretically insurmountable limitation.

Why couldn't profile redirects be sent out to other instances like any other type of published content, and then consulted by clients when loading posts & comments? Even if there are some clients that don't support them, wouldn't most clients end up supporting them if they become part of the protocol and are supported by the first-party UI? Or is the protocol already set in stone and unable to be progressively enhanced?

I'm very aware of my ignorance of the technical details behind Lemmy and its protocol, and I hope my arguments don't come across as arrogant or uninformed. But the confidence that this feature is impossible to implement feels poorly founded. If y'all maintainers had just said "we don't think this feature is important so we won't implement it" I wouldn't have said anything, but if the only rationale for permanently closing out this feature request is a belief that it wouldn't be possible to implement, it feels like some significant value is being missed out on.

**Comment by calculuschild** [comment] 2025-05-29 02:54
> If you change your email address, you can't get every other email service to agree to rewrite their histories to update to your new one either.

But, you can export your current email storage into a new account, and thus still have access to all of your contacts and old emails. Sure, the other email services don't know about your email change. But your personal info is still intact and you maintain access to your content.

That's what I would personally want out if this. If I can currently search for all the posts I wrote, topics I upvoted, private messages recieved... I would like to somehow transfer access to that list in a new account. *Other people* don't need to get updated links to all of my content.

I would like calculuschild2 to see posts by both calculuschild1 and calculuschild2  when looking through my post history. Like a username alias.
