### ISSUE TITLE
Pages with OG info not being pulled into Lemmy

### ISSUE THREAD

**Issue by harcesz** [LemmyNet/lemmy#1796] opened 2021-09-28 14:11 UTC
We're seeing some websites, that seem to have working OG information, that's not being pulled properly into Lemmy, most notably; 

-  https://oko.press/
- https://wyborcza.pl/

other cases:
- https://outride.rs/

**Comment by dessalines** [comment] 2021-09-28 15:15
I'm not sure, would have to add a unit test and see what's going on there.

**Comment by rgroothuijsen** [comment] 2021-12-20 09:50
For the first site, at least, the issue is that the OG tags have been placed in the body. The HTML parser expects them to be present in the head.

**Comment by dessalines** [comment] 2022-01-03 16:02
dupe of #1858

**Comment by harcesz** [comment] 2022-04-20 17:46
Hi, this has been closed, as the supposed duplicate, but the problem persists.

**Comment by dessalines** [comment] 2022-04-20 19:17
@harcesz since these sites are outliers, could you inspect the pages and figure out if the OG tags are in the correct place?

**Comment by harcesz** [comment] 2022-04-20 22:37
If putting them in the header is the standard than apparently not. But that misses the point from my perspective. Lemmy has to be able to pull them nevertheless, otherwise we land with users seeing that "it works on facebook so it's lemmy that's broken". I took a random link from one of them; https://oko.press/goworit-moskwa-10-uzasadnien-zniszczenia-mariupola/ dropped it into 3 different OG validators, including facebooks;

https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Foko.press%2Fgoworit-moskwa-10-uzasadnien-zniszczenia-mariupola%2F
https://opengraphcheck.com/result.php?url=https%3A%2F%2Foko.press%2Fgoworit-moskwa-10-uzasadnien-zniszczenia-mariupola%2F
https://smallseotools.com/open-graph/

and all of them would pull all the required tags from this link. While lemmy can't even suggest the title and gives a 'blank' post. And that's while being dependant on a facebook's de facto standard and tags that are there, not even non-standard website with no identifiable titles and images in which case it would still be preferred that Lemmy could offer something to the publishing user.

**Comment by rysiekpl** [comment] 2022-04-20 22:49
On one hand I strongly agree that standards matter. Getting out of "anything goes tag soup" stage of Web took us a decade or so, and it was ugly.

On the other hand, I see the need for Lemmy to not be seen as "defective", to bring more users aboard.

I feel like there could be a compromise here. It could be something along the lines:
 - implement extract the OG tags from `<body>`; but also
 - tag posts with such incorrect, non-standard, broken OG as "broken" or some such in a visible way.

That way:
1. Lemmy gets to not look bad compared to the walled gardens.
2. Site operators get very clear feedback: this is wrong, fix it.

**Comment by harcesz** [comment] 2022-04-20 23:14
Maybe we could add a referrer tag of "get your sh*t together" for anyone reading the logs to pester the people responsible and not the end users? 

Meanwhile, I've went through tok.fm and the main problem might be that it's a hot steaming pile of sh*t. Sseriously, the headers itself is >690 lines. But also has `<meta charset="ISO-8859-2">` statement is there, and I'm not sure what Lemmy should actually do with such eccentric ideas, but it would be nice to display it without going full windings.

**Comment by dessalines** [comment] 2022-04-20 23:21
Just a note that lemmy uses this rust library to extract open-graph / tag information. 

https://github.com/orottier/webpage-rs

I can help with making PRs or issues to that repo after we've identified issues, but lemmy doesn't have its own custom tag fetcher.

**Comment by Nutomic** [comment] 2023-06-30 10:25
https://github.com/LemmyNet/lemmy/pull/3338

**Closed by Nutomic** 2023-06-30 10:25 UTC
Labels: bug
