### ISSUE TITLE
[Bug]: A post being unpinned in a federated community while the instance is down never gets handled by the instance

### ISSUE THREAD

**Issue by Ategon** [LemmyNet/lemmy#3867] opened 2023-08-11 02:51 UTC
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

For a community on another instance, if there is a post that gets unpinned while your instance is down for whatever reason, it never actually gets unpinned for your instance specifically and just hangs around until the post is pinned and then unpinned again.

Was an issue where there was posts pinned for 2 months in a community on my instance when looked at from various other instances. When I experimented with fixing it and rnded up fixing it from pinning and then unpinning the messages, lemmy.blahaj.zone was down so the fix never went through to them. Im leaving it up as an example until this bug is fixed and you can see the discrepancy by looking at https://programming.dev/c/godot for what it should be and https://lemmy.blahaj.zone/c/godot@programming.dev for what lemmy.blahaj.zone sees

The same may be true for pinning but haven't been able to test it

### Steps to Reproduce

1. Make your instance be able to see a community on another instance
2. Pin a post on that community
3. Turn off your instance
4. Unpin the post in that community
5. Bring your instance back up

### Technical Details

N/A

### Version

0.18.4

### Lemmy Instance URL

programming.dev

**Comment by RocketDerp** [comment] 2023-08-11 16:16
On this topic... there is a category of problems I have called "remote-home-remote", replication of data and changes to data when a community is homed on an instance and activity takes place on a downstream subscribed instance to that community.

Right now, with main, my testing shows that feature flagging does not get replicated by the home instance. In the most dramatic terms, that means with 1500 Lemmy servers out there, only 2 get updated, 1498 do not.  I have a api_tests file named remote_home_remote.spec.ts that I can go into the gritty details of the test if you want. I'm still working to get these enhanced tests merged into main.

I publicly confirmed the bug on July 27 in https://github.com/LemmyNet/lemmy/issues/3544

**Comment by dessalines** [comment] 2023-10-24 18:52
We resend actions for failures, but if the instance is down for a really long time, I believe its now kicked out of that queue. cc @Nutomic I think this one is already handled in the same way as others.

**Comment by Nutomic** [comment] 2023-10-25 10:00
Yep there is no difference to other activity types in terms of sending/retry.

**Comment by ISibboI** [comment] 2024-02-16 15:59
This is an issue on e.g. https://sopuli.xyz/c/dach@feddit.de

There is a three month old pinned post that is not pinned anymore on https://feddit.de/c/dach

Since pinned posts are permanent, would it be possible to implement a fix for that?

For example, periodically poll pinned posts. Then it gets resolved after a while. Or, whenever sending a pin or unpin event, then instead send a complete list of the pinned posts. This way the issue gets resolved whenever the next post is pinned or unpinned.

**Comment by dessalines** [comment] 2024-02-16 23:16
This doesn't just apply to pinned posts, but every action done while their recipients were offline. Apub is based on sends / pushes, and isn't meant to be a history fetching service.

**Comment by ISibboI** [comment] 2024-02-17 05:00
Sure. For most cases, a missed send or push does not matter much. For
example, if an instance misses a post or a comment, then that is a little
bit annoying, but the post or comment will anyways become irrelevant over
time. And if really necessary, one can make an account on another instance
to interact with that post or comment.

But when it comes to missed unpins, the community will appear broken
forever, because the pinned message will just stay forever. It doesn't just
fix itself over time. And it's especially annoying, because the pinned
message is always shown on top, and every user always needs to scroll past
it.

**Closed** 2024-02-26 14:45 UTC
Labels: bug, area: federation
