### ISSUE TITLE
add option to disable & discard comment votes

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/lemmy#4527] opened 2024-03-12 16:57 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Increasingly small instances struggle with database i/o on cheap and older hardware due to the high amount of incoming federated vote activities.

### Describe the solution you'd like.

Votes on comments (as opposed to votes on posts) add only little to most threads compared to chronological comment sorting, but still represent a significant database load.

If would be good if instance admins had the option to disable votes on comments and automatically discard all incoming federated comment votes to lessen the database load.

### Describe alternatives you've considered.

Vote batching would also help, but requires significantly more development effort and likely additions to the ActivityPub specs.

### Additional context

Somewhat related issue: https://github.com/LemmyNet/lemmy/issues/4086

**Comment by poVoq** [comment] 2024-03-13 11:25
Also relevant for geografically distant instances it seems: https://reddthat.com/comment/8316861

**Comment by Nutomic** [comment] 2024-09-12 10:38
Similar to https://github.com/LemmyNet/lemmy/issues/5016

**Comment by dessalines** [comment] 2024-09-13 14:27
Might be a dupe of #4086 , where I propose that we either have options to block all federated votes (or have instance allowlist/blocklists for them).

**Comment by poVoq** [comment] 2024-09-13 14:40
I think from a UI perspective disabling all comment votes is less confusing. It would be an instance option similar to disabling down-votes.

**Comment by Nutomic** [comment] 2024-11-12 09:29
Already implemented.

**Closed by Nutomic** 2024-11-12 09:29 UTC
Labels: enhancement, area: performance
