### ISSUE TITLE
PeerTube support (integration)

### ISSUE THREAD

**Issue by ghost** [LemmyNet/lemmy#156] opened 2019-05-24 22:11 UTC

**Comment by dessalines** [comment] 2019-05-28 19:31
Im not sure what the integration would be, this would mainly be just linking to peertube instances right?

Since the federation in lemmy is following communities, and not people, that part of it might not apply.

**Comment by anewton1998** [comment] 2019-05-28 23:21
Perhaps pulling the preview image from a peertube video for display? That's what I would imagine, I guess.

**Comment by Zig-03** [comment] 2019-05-29 09:07
> Perhaps pulling the preview image from a peertube video for display? That's what I would imagine, I guess.

Yes and then one click and you're watching the video. Just like reddit with youtube videos. 
Maybe there are other 'clever' ways of integrating peertube into lemmy but for now that's all I can think of.

**Comment by dessalines** [comment] 2019-05-29 18:02
If anyone knows of a good library to get html previews from a link (like imgur link to `<img`, youtube to `<video`, let me know cause I haven't been able to find one. And it'd be super useful for ppl who just want to paste in links to wherever as opposed to providing an image URL for the post URL.

RES has some code for this, but its a monster, and they have to keep updating it every time these services change their schemes.

**Comment by anewton1998** [comment] 2019-05-29 18:10
Would this opengraph library work?
https://github.com/kumabook/opengraph

**Comment by dessalines** [comment] 2019-05-29 18:16
It would only work for image previews / thumbnails, not for videos, audio previews, etc. I want a library that takes in everything from a soundcloud url, to a youtube link, to imgur, giphy, peertube, and builds html previews, or links to the source urls and says their type.

The other thing is I'd *really* like to keep url processing and transforms on the front end.

**Comment by filippodb** [comment] 2019-05-31 16:12
> It would only work for image previews / thumbnails, not for videos, audio previews, etc. I want a library that takes in everything from a soundcloud url, to a youtube link, to imgur, giphy, peertube, and builds html previews, or links to the source urls and says their type.
> 
> The other thing is I'd _really_ like to keep url processing and transforms on the front end.

a possible solution that support 600 media providers is here: https://embed.ly/providers

an open alternative is: https://noembed.com

or: https://oembed.com

none of them support peer tube yet.

**Comment by Zig-03** [comment] 2019-06-09 21:56
> an open alternative is: https://noembed.com
> 
> or: https://oembed.com

I could open a new issues in those repos (https://github.com/leedo/noembed and https://github.com/iamcal/oembed) and ask to support peertube links.

**Comment by dessalines** [comment] 2019-06-10 00:37
Would be a good idea.

**Comment by DontUseGithub** [comment] 2020-01-04 09:19
Since this issue has been closed, does this mean that no PeerTube support is planned?

**Comment by dessalines** [comment] 2020-01-04 17:11
Its a link aggregator, peertube links are accepted. If its about embedding videos into lemmy the same way there are image previews, then that's a different issue that needs an embed provider for all kinds of content, not just peertube.

**Comment by filippodb** [comment] 2020-01-05 10:19
peertube is on activitypub, it's part of the fediverse like lemmy, so it it's strange to see it's not fully supported.
I mean, fediverse projects should help each other and peertube support should come before supporting youtube, vimeo, etc.

**Comment by filippodb** [comment] 2020-01-05 10:22
maybe you can see how mastodon works integrating peertube video.

**Comment by dessalines** [comment] 2020-01-05 13:23
What does fully supported mean?

**Comment by filippodb** [comment] 2020-01-05 23:48
fully supported like on mastodon, so the comments made on lemmy to be published on peertube and replies on peertube to show on lemmy too, see the video:

https://peertube.cpy.re/videos/watch/da2b08d4-a242-4170-b32a-4ec8cbdca701?autoplay=1&auto_play=1

I believe this integration will help both platform.

**Comment by dessalines** [comment] 2020-01-05 23:52
Ah. Okay so that is a federated user follow. Eventually these will be supported in lemmy, but after the federated community follow.

**Comment by dessalines** [comment] 2020-07-22 19:32
Dupe of #752

**Closed by dessalines** 2020-07-22 19:32 UTC
Labels: Component: Frontend, enhancement
