### ISSUE TITLE
Question: Why doesn't Lemmy include the `replies` attribute in ActivityPub objects?

### ISSUE THREAD

**Issue by anderspitman** [LemmyNet/lemmy#4262] opened 2023-12-13 21:46 UTC
### Question

If you curl a Mastodon post the object returned includes the `replies` attribute, which is an `OrderedCollection` of replies. This is very useful for crawling a comment tree to find all responses. I noticed that Lemmy doesn't include this information, and was curious if this was an intentional design decision and if you would consider adding this functionality?

**Comment by Nutomic** [comment] 2023-12-14 09:45
Because no one has implemented it yet. Duplicate of https://github.com/LemmyNet/lemmy/issues/2004.

**Closed by Nutomic** 2023-12-14 09:45 UTC
