### ISSUE TITLE
[Bug]: Broken number of posts, comments, and votes

### ISSUE THREAD

**Issue by gummyhulk** [LemmyNet/lemmy#5182] opened 2024-11-10 12:44 UTC
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I recently created a new account because I wanted to move away from my old one, and subscribed to some of the communities my old account had.

However, the number of posts, comments, and votes are inaccurate. Most posts do not have comments at all, most of them only have 1 upvote, and whenever I try refreshing the feed I am unable to see new posts. When I enter a community on my new profile, I can only see posts from more than a week ago despite sorting by new or hot.

### Steps to Reproduce

1. Create a new account
2. Subscribe to communities as your old account
3. Compare the post- comment- and vote number.

### Technical Details

I have compared this issue on the web app and official apps with the same result. I am running GrapheneOS.

### Version

BE 0.19.6

### Lemmy Instance URL

aussie.zone

**Comment by dessalines** [comment] 2024-11-10 15:31
Do you have any language filters, or other blocks?

**Comment by gummyhulk** [comment] 2024-11-10 17:06
No blocks of any kind.

**Comment by Nutomic** [comment] 2024-11-11 08:57
Does this happen only for remote communities? Most likely they were not federated before, and you need to subscribe in order to receive comments and votes. Local communities should be working fine.

**Comment by gummyhulk** [comment] 2024-11-11 12:08
Local communities seem to work fine on my new account, however their content isn't accurate for my old account (non-aussie.zone). I have subscribed to the communities on my new account and they are broken anyway. On a few of them I'm "pending," but no matter, it's still the sane result for them all.

**Comment by dessalines** [comment] 2024-11-12 13:52
Dupe of #5186 , closing this since the other has more info.

**Closed by dessalines** 2024-11-12 13:52 UTC
Labels: bug
