### ISSUE TITLE
[Bug]: 0.19.4-beta.2 - icon, banner and public_key no longer exist under /api/v3/site

### ISSUE THREAD

**Issue by ticoombs** [LemmyNet/lemmy#4605] opened 2024-04-08 02:18 UTC
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

$Title

### Steps to Reproduce

1. Update to 0.19.4-beta.2
2. Open Admin Section
3. You no longer have a banner or Favicon
![image](https://github.com/LemmyNet/lemmy/assets/2687896/64b96483-c91c-4237-9510-a5ce980fdc72)
4. Open Jerboa and you get a big warning about public_key no longer existing

### Technical Details

N/A

### Version

0.19.4-beta.2

### Lemmy Instance URL

N/A

**Comment by Nutomic** [comment] 2024-04-08 13:34
The [public_key](https://github.com/LemmyNet/lemmy/blob/main/crates/db_schema/src/source/site.rs#L40) is only for federation and not used by the api so it was marked as `serde(skip)`. However we should revert that and wait until 0.20 as its a breaking change.

I can reproduce the problem with site icon, its not returned despite being set in the database. But in this case theres no `serde(skip)` and nothing in the code that would exclude it, so I dont know what might cause it.

Thanks for testing the beta by the way, its really helpful to find out about these problems before release!

**Comment by Nutomic** [comment] 2024-04-09 10:08
I believe the missing icon was because of caching, as the data in `/api/v3/site` is only updated every 60 seconds. Now its showing up on [voyager](https://voyager.lemmy.ml/), and the banner as well.

Ive made a PR to add the public_key back for now.

**Closed** 2024-04-09 14:10 UTC
Labels: bug, area: api

**Comment by ticoombs** [comment] 2024-05-01 01:14
We should reopen this as it is still happening.

Upon lemmy container restart/update/upgrade it somehow loses the Image(s).

You can see it currently on voyager.lemmy.ml after you upgraded to -beta.6

**Comment by Nutomic** [comment] 2024-05-02 09:11
Voyager does have a banner both in the db and api. However there is a "broken" placeholder shown in the sidebar, so this looks like a problem with lemmy-ui.

**Comment by ticoombs** [comment] 2024-05-02 09:58
:shrug: All I know is that it keep disappearing from `api/v3/site`.

**Comment by Nutomic** [comment] 2024-05-02 10:40
Voyager has a banner in the api, you can see it in `https://voyager.lemmy.ml/api/v3/site`. @dessalines did you set a banner manually after upgrading?

**Comment by dessalines** [comment] 2024-05-02 16:58
I must have, but I removed it now. But icon, banner, and public key [are still fine, and shouldn't have any issues.](https://github.com/LemmyNet/lemmy/blob/main/crates/db_schema/src/source/site.rs#L27)
