### ISSUE TITLE
Adding a Discovery Feed alongside Subscribed/Local/All

### ISSUE THREAD

**Issue by zinklog2** [LemmyNet/lemmy#2986] opened 2023-06-09 10:28 UTC
One heavily discussed problem is the lack of discoverability of new communities to join so I've been thinking of ways how it can be addressed.

Adding a Discovery Feed which *only* shows posts from communities that do not appear in 'All' could be useful. The main problem is that Communities haven't yet been cached in local db and fetching every single one would be too resource heavy. So my idea is to randomly fetch 3-4 communities from different federated instances (numbers can be tweaked) and show them in the 'Discover' feed, and then users can subscribe if a community seems interesting.

This should allow much greater exposure to smaller instances and their communities and make things more interconnected.

**Comment by zinklog2** [comment] 2023-06-09 13:12
That's true. I'm not a developer so I'm not sure how to implement this but I imagine there might be a sliding window way of clearing up older content that's fetched by discovery feed. That way new content can be shown and the communities that no one subscibed to can eventually be cleared away from the db.

**Comment by servoparmi** [comment] 2023-06-12 02:40
I'd like to propose an alternative Watched Instances feed, which sits somewhere between All and Subscribed.  It would essentially be a filtered All, the subset of communities defined by my choice as a user to mark some of the instances visible in All as ones I'm interested in potentially interacting with.

Example use case:
I have joined Mytown.net and am interested in my local physical community's opinions on things from A-Z so I mark mytown.net as Watched and see it in my Watched Instances feed.  I interact with /c/LostCats on it and am also interested in the new community /c/NewCafes which I would discover and subscribe to.  However, another instance farwaytown.com, which appears in All, doesn't interest me as much.  I have not marked it as watched so it doesn't appear in Watched Instances, but it does still appear in All.

**Comment by dessalines** [comment] 2023-10-18 20:49
Mostly a dupe of #2951 . We can't randomly fetch unknown communities, but relying on some service to discover new ones might be doable.

**Closed by dessalines** 2023-10-18 20:49 UTC
Labels: enhancement, area: discovery
