### ISSUE TITLE
Balance Post Scores Based on Instance Monthly Active Users

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#3642] opened 2023-07-17 09:50 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?
Yes, the proposal is related to the problem of underrepresentation of smaller instances on the main feed in Lemmy, as mentioned in issue #1026.

### Describe the solution you'd like.
The solution proposed is to balance instance scores based on monthly active users instead of the size of the community. By considering the monthly active users, smaller instances will have a fair chance of being represented on the main feed, ensuring a more diverse representation of instances.

### Describe alternatives you've considered.
The approach considered on issue #1026 can be particularly important in the subscribed feed, where communities should be equally represented. Or even better allow for weighted community subscription as proposed in issue #3518. This would ensure that you see more from communities that you like more.

### Additional context
Balancing communities would dilute the uniqueness and individual themes of each instance. Instead of balancing communities, balancing instance scores based on monthly active users would accomplish the goal of achieving a more inclusive and diverse experience for users while still maintaining the individuality of each instance.
 
Considering the possibility of Meta making a federated Reddit alternative with millions of active users, the feed of every federated instance would be dominated by the communities of that instance. Implementing a balanced scoring system based on monthly active users would help prevent this domination and promote a more diverse and inclusive experience for users on Lemmy.

**Comment by dessalines** [comment] 2023-09-07 13:16
Instances don't have scores, only posts and comments. This seems like a dupe of #1026

**Comment by 8ullyMaguire** [comment] 2023-09-07 14:13
> Instances don't have scores, only posts and comments. This seems like a dupe of #1026

It's referring to balancing post cores based on the instance monthly active users instead of the communities monthly active users. No, it's no a dupe of #1026, you can see how they differ if you read the issue.

**Comment by dessalines** [comment] 2023-09-07 14:18
Okay. Can you work on this?

**Comment by 8ullyMaguire** [comment] 2023-09-07 14:27
I will try it at some point when I learn to use this stack. I'd do it as a user setting to be applied to the other filters if that's okay.

**Comment by dessalines** [comment] 2023-09-07 14:33
Sure, let me know if you run into any issues.

**Comment by 8ullyMaguire** [comment] 2023-09-08 16:31
Since you just implemented `Scaled` filter, and it's fresh on your mind it would be great if you could also add a similar filter for scaling by instance monthly active users. That way, I only have to focus on figuring out how to turn it into a user setting that applies to the other filters.

**Comment by Nutomic** [comment] 2023-09-28 10:55
https://github.com/LemmyNet/lemmy/pull/3907

**Closed by Nutomic** 2023-09-28 10:55 UTC
Labels: enhancement, area: sorting
