### ISSUE TITLE
[Bug]: Pagination doesn't work for GetComments if max_depth is set

### ISSUE THREAD

**Issue by leinardi** [LemmyNet/lemmy#3585] opened 2023-07-11 14:28 UTC
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

It seems not possible to fetch anything else than the first 300 comments if `max_depth` is set.

### Steps to Reproduce

1. Open a post with more than 300 comments, like this one: https://lemmy.ml/api/v3/comment/list?post_id=1846338&max_depth=8&page=1. The response will contain only the first 300.
2. Try to fetch the next 300 increasing the page value: https://lemmy.ml/api/v3/comment/list?post_id=1846338&max_depth=8&page=2
3. The same 300 from the 1st get will be retrieved.

### Technical Details

This post contains 914 comments, what is the best way to fetch them with pagination and a max_depth value?
https://lemmy.ml/api/v3/post?id=1846338

### Version

BE: 0.18.2

### Lemmy Instance URL

lemmy.ml

**Comment by lionirdeadman** [comment] 2023-07-20 04:06
This sounds related to https://github.com/LemmyNet/lemmy/pull/3306

**Comment by leinardi** [comment] 2023-07-20 07:27
@lionirdeadman oh yeah, that PR seems very related. I would still keep this issue open until a proper fix is available.

**Comment by Nutomic** [comment] 2024-03-15 11:00
Duplicate of https://github.com/LemmyNet/lemmy/issues/3065

**Closed by Nutomic** 2024-03-15 11:00 UTC
Labels: bug, area: api
