### ISSUE TITLE
Post shows a negative number of new comments

### ISSUE THREAD

**Issue by Adda0** [LemmyNet/lemmy#2883] opened 2023-05-27 16:55 UTC
### Issue Summary

A post shows that it has a negative number of new comments, as shown in the picture.
![lemmy_negative_number_of_comments](https://github.com/LemmyNet/lemmy/assets/52529234/e35a16c8-765b-4716-9b1b-5be7e0d0ca4c)

### Steps to Reproduce

1. Open [lemmy.ml](https://lemmy.ml/).
2. Look for posts which show a negative number of new comments.
4. When you see the post (open the post), the negative number is still shown, but the comments are marked as *seen* and the number dissapears when revisiting the post again or looking at the post on the main timeline.

### Technical details
- The shown post is a [federated Mastodon post](https://aus.social/@ajsadauskas/109334791235861940), seen as [Lemmy post](https://lemmy.ml/post/952323). 
- I have no specific language selected (all are deselected).
- Any browser console errors? No.
- There is a [new comment](https://lemmy.ml/comment/433376), that was deleted by the author of the comment.

**Comment by dessalines** [comment] 2023-05-27 23:25
Oops, sorry, thought we had an issue for this. Possibly #2826

**Comment by Adda0** [comment] 2023-05-28 06:21
#2826 only covers cases where the number of all the comments for a post is higher than what you are able to see in the comment feed, if I understand correctly. Even if the cause of both issues might be the same, I would say that the issues themselves are different, even if related.

**Comment by lionirdeadman** [comment] 2023-07-23 04:17
Likely related to https://github.com/LemmyNet/lemmy/issues/2998

**Comment by dessalines** [comment] 2023-10-18 20:47
Dupe of #3722

**Closed by dessalines** 2023-10-18 20:47 UTC
Labels: bug, area: database
