### ISSUE TITLE
Allow to disable voting by specific instances

### ISSUE THREAD

**Issue by db0** [LemmyNet/lemmy#4034] opened 2023-10-11 09:00 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

This is a another tool in the moderation toolset to be used instead of outright de-federation. It could be used against instances which are not problematic enough to be blocked, but ideologically different enough where the parent instance does not wish to record their voting patterns. 

This would be similar to mastodon's silencing features in strength.

### Describe the solution you'd like.

Allow the lemmy admins to provide another list of "Vote silenced" instances (another name for this list is also fine). Votes from those instances on posts or comments would be silently dropped.

### Describe alternatives you've considered.

No alternatives exist

**Comment by ThisIsMissEm** [comment] 2023-10-11 14:18
Rather than just lists of servers for a specific moderation action, I'd definitely recommend thinking about this more in terms of "domain filters" much like a firewall, you can "allow" federation, you can "deny or reject federation" and you can also "filter federation" where you apply some sort of logic that constrains how they can federate.

So for instance, here, you might end up with a domain filter that says "filter instance XYZ.example by ignoring dislike and like activities from this instance, but allow other activities through".

That sort of model is quite flexible and should hopefully allow for all the potential moderation needs around domains/instances.

**Comment by dessalines** [comment] 2023-10-24 20:02
Sry I didn't see this one, gonna close it as a dupe of #4086 , which has a potential solution.

**Closed by dessalines** 2023-10-24 20:02 UTC
Labels: enhancement, area: moderation
