### ISSUE TITLE
[Feature request] community groups

### ISSUE THREAD

**Issue by Hikiru** [LemmyNet/lemmy#3443] opened 2023-07-01 20:23 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Decentralization means it’s inevitable that multiple communities of the same name get created across instances.

Copy and pasted from gkasdorf, memmy developer:

1. You can only make a request to Lemmy for all posts or a single community's post. Given that, we would need to make multiple requests (either concurrently or consecutively, but neither is a good option for the reasons below) to obtain all of these posts before sorting them and displaying them.
2. Trying to make a bunch of concurrent requests could work, but then we'd probably need to make it so that you can't add a community from the same instance to the group more than once or MAYBE twice. This is because of how fragile the servers are right now (in part due to ineffeciencies with Lemmy). We'd get a lot of failed requests if we didn't limit the number.
3. For obvious reasons, consecutive requests are not ideal. There'd be a longer delay (growing with each community added) and that delay would be pretty noticeable because of the issues going on with servers in general.

### Describe the solution you'd like.

There should be some way to retrieve a set of posts from a number of instances rather than just one or all.

### Describe alternatives you've considered.

Not sure

**Comment by yrahul3910** [comment] 2023-07-01 20:48
+1. This would be a massive win for fragmented communities.

**Comment by BlueEther** [comment] 2023-07-01 21:39
+1 one as well

A list of 'Favourite' communities within the subscribed communities.
I currently get around this by using the search function, but that only works as I want to read posts on lemmy.nz first so is a simple search that doesn't return thousands of posts

**Comment by sunbeam60** [comment] 2023-07-01 22:27
This would be huge! As the fediverse grows I keep seeing the same things posted on multiple instances and it kills the front page.

**Comment by gkasdorf** [comment] 2023-07-01 22:56
If anyone wants to point out a better solution than what I described here (or maybe I am wrong too) let me know. But yea, right now it seems we need a better way to retrieve results from multiple communities at once.

**Comment by Castone22** [comment] 2023-07-02 21:53
Other solutions might include something akin to multireddits or even a concept like meta communities that aggregate a list of communities.  Could even also communities to subscribe to other communities.

**Comment by yrahul3910** [comment] 2023-07-02 21:59
Yeah, I was going to suggest multireddits but with (a) option to make them public or private (b) import/export options so that (i) if you have public "multireddits", then I can click a button and import them, copying it to my profile (ii) I can also export it as a JSON/etc. and you can import it. I didn't want to suggest something too grandiose and difficult to implement, though 😄

**Comment by Hikiru** [comment] 2023-07-03 06:22
my idea isnt completely like multireddits from what i understand they are. with my idea you could implement the groups into your home feed, and when clicking on the community name it'd take you to the group rather than the specific community it was posted to. basically a seamless way for the user to combine fragmented communities rather than just a way to view multiple communities at once

**Comment by tmarkov** [comment] 2023-07-04 23:34
But everyone shouldn't have to do the work of creating community groups over and over again, when a lot of people's groups would overlap.

The best suggestion I've seen is, I think, allowing communities to follow other communities. That allows creating multireddits, but also allows for similar communities to follow each other if they want, or for a new community to get initial content, etc.

**Comment by AlphaFoxCharlie** [comment] 2023-07-06 21:54
Would love to see this.

**Comment by lionirdeadman** [comment] 2023-07-23 03:12
Duplicate of https://github.com/LemmyNet/lemmy/issues/818

**Closed by lionirdeadman** 2023-07-23 03:12 UTC
Labels: type: duplicate, enhancement
