### ISSUE TITLE
Remove/skip media server (pictrs) installation for legal reasons.

### ISSUE THREAD

**Issue by therealmaxmoon** [LemmyNet/lemmy#3860] opened 2023-08-09 19:53 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

In some countries (especially in the European Union) the maintainer of a Lemmy instance can get into serious trouble if users upload protected/illegal content on their servers and it's really critical that there is a record of the evidence on e.g. archive.org, which can be used against the maintainer. 

### Describe the solution you'd like.

Provide an option while installing Lemmy (with ansible) to remove the ability that users can upload media, except of thumbnails of links, if a user creates a post or icons and banners of communities.

### Describe alternatives you've considered.

This issue was discussed [here](https://github.com/LemmyNet/lemmy-ansible/issues/147#issue-1843745971), including a workaround with already running instances.

**Update (2023-08-10):** The workaround doesn't work correctly, if people are allowed to create new posts. Thumbnails of provided links will not show up.

**Comment by codyro** [comment] 2023-08-11 02:45
Duplicate/additional context from the developers here: https://github.com/LemmyNet/lemmy/issues/1118

**Comment by lionirdeadman** [comment] 2023-08-11 03:15
Good catch, I did think I saw this before. Closing as duplicate of https://github.com/LemmyNet/lemmy/issues/1118

**Closed by lionirdeadman** 2023-08-11 03:15 UTC
Labels: enhancement, area: media
