### ISSUE TITLE
Suggesting a categorization of communities to avoid duplicates

### ISSUE THREAD

**Issue by arsg0etia** [LemmyNet/lemmy#2946] opened 2023-06-07 03:59 UTC
Hello,

I am a user of Lemmy and I really enjoy the platform. However, I noticed that there are a lot of duplicate communities between different Lemmy instances. For example, there are multiple communities for technology, gaming, politics, etc. This makes it hard to find and join the most active and relevant communities for my interests.

I suggest that Lemmy should have a categorization of communities based on topics or themes, such as entertainment, news, science, etc. This way, users can easily browse and discover communities that match their preferences. It would also help to reduce the duplication and fragmentation of communities across instances.

I think this feature would improve the user experience and the federation of Lemmy. What do you think?

Thank you for your hard work and dedication to this project.

**Comment by dessalines** [comment] 2023-06-07 19:06
We have an issue for post tagging #317 , but none for community tagging yet. If anyone would like to work on this, that'd be good.

**Comment by lionirdeadman** [comment] 2023-07-23 04:13
Duplicate of https://github.com/LemmyNet/lemmy/issues/3564

**Closed by lionirdeadman** 2023-07-23 04:13 UTC
Labels: type: duplicate, enhancement
