### ISSUE TITLE
Allow use of external thumbnails

### ISSUE THREAD

**Issue by kroese** [LemmyNet/lemmy#3784] opened 2023-08-01 00:16 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

For instances that want to avoid hosting  copyrighted content, it would be nice if the admin could decide to use external `thumbnail_url`'s. Another use-case would be to reduce the amount of diskspace required to run an instance.

### Describe the solution you'd like.

Ideally, there would be 2 admin settings:

First one to decide if thumbnails from federated posts will be locally stored or externally linked.

Second one that applies to locally created posts.

In addition to these global settings, it would be very nice if you could override them per user. For example, to let some bots post with external thumbnails but the rest of the users use internal ones or vice versa.

### Describe alternatives you've considered.

There are no alternatives as far as Im aware.

**Comment by lionirdeadman** [comment] 2023-08-02 00:30
This issue seems to partially be a duplicate to https://github.com/LemmyNet/lemmy/issues/3747

As for hosting the thumbnail, that is needed and cannot be optional. The instance should always proxy it for privacy, safety and security concerns #2947

**Comment by lionirdeadman** [comment] 2023-08-02 02:38
> @lionirdeadman Im fully aware of the privacy concerns by directly linking to remote servers. But on the other hand, I can provide you with examples of people getting sued in my country for posting links to newspapers articles on social media, if that platform shows a preview thumbnail (like Facebook). Because for the law that means you duplicated the image without permission. The only method that is allowed is to directly link to the original image.
> 
> So yes, I understand people value not being tracked, but most people value not being sued even more! I think it should be up to the instance operator to make a decision about this, and users that dont agree with that decision can just avoid using that instance.

Yeah, I can agree with it being an admin setting rather than a posting option. Would you like to modify this feature request to reflect that?

**Comment by dessalines** [comment] 2023-10-18 20:42
This seems to be a duplicate of the two above issues. We also already have a pictrs setting for `cache_remote_images`

**Closed by dessalines** 2023-10-18 20:42 UTC
Labels: enhancement, area: administration, area: media

**Comment by dessalines** [comment] 2023-10-20 14:45
Open up a new issue with that specifically if you would.
