### ISSUE TITLE
User-based Community Groups

### ISSUE THREAD

**Issue by trueluckdude** [LemmyNet/lemmy#3193] opened 2023-06-19 04:51 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

This is a user facing feature request for a method of organizing and viewing/filtering subscribed communities.

### Describe the solution you'd like.

I’d like to see a simple grouping feature at the user level. Allow the user to make their own groups of communities, they can then view these groups as if looking at a filtered subscribed view. Then, when posting, there should be a default community in the group to post to, of the users choosing (editable), which they can change with a drop-down populated with all the user’s communities in that group, and perhaps give the option to post to all in the user’s group.

### Describe alternatives you've considered.

There’s a request about making this feature on a community level, but I think that over complicates things for everyone involved.

**Comment by boehs** [comment] 2023-06-23 02:42
duplicate of https://github.com/LemmyNet/lemmy/issues/818

**Closed** 2023-06-29 11:14 UTC
Labels: enhancement
