### ISSUE TITLE
Some page optimizable details

### ISSUE THREAD

**Issue by ceecx** [LemmyNet/lemmy#907] opened 2020-07-05 01:25 UTC
**I'm looking for more details on the issues and updating this Issues. we'll discuss how to fix or avoid these issues. Resolved issues I will remove from here.**

----

2020-07-10 Update

6. Do you consider adding `navigation to follow the page scrolling` and `return to the top button` ? This is an effective way to avoid taking a long time to get to the top if there are too many comments.

----

1. [(Fixed)](https://github.com/LemmyNet/lemmy/commit/34f6e617652ad1e78505cd8b962e09ed1e182200) title in the arrow position in the picture, I think it should just be changed to `username`, not `/u/username`.
![image](https://user-images.githubusercontent.com/18570103/86523573-07e9db00-bea1-11ea-9bfe-12475cb52b0a.png)

2. In the absence of more content, I can still click on `prev`/`next`, so maybe that shouldn't be? Perhaps a notification could be returned?
![image](https://user-images.githubusercontent.com/18570103/86523590-44b5d200-bea1-11ea-8687-664cb15e073b.png)

3. The message prompt is too short, and you cannot edit or delete the image after it disappears.
![image](https://user-images.githubusercontent.com/18570103/86524194-17b9ed00-beaa-11ea-8e4d-21d2f0deb78d.png)

4. After deleting the image, the system will return the URL of the deleted image, resulting in a `405 error`.
![dPtcOMngjC](https://user-images.githubusercontent.com/18570103/86524152-877ba800-bea9-11ea-88dc-b11673d18d4c.gif)

5. These categories don't support modifications on the front end and aren't added to the translation effort, maybe we should add them.
![image](https://user-images.githubusercontent.com/18570103/86524234-9c0c7000-beaa-11ea-8f4e-35a8957701a6.png)

**Comment by dessalines** [comment] 2020-07-05 14:32
1) I'm gonna change it to `@`, and need to work on the page titles a bit. Kinda a dupe of #801 
2) Please make a ticket for that, I need to do it across the whole UI for every prev / next.
3) I do want a dissappearing thing, how long do you think it should stay up?
4) For some reason `window.location.replace(deleteUrl);` doesn't load up a new window on my firefox, it just correctly calls the GET. What browser, so I can replicate?
5) Yes this is a big problem, categories currently have no i18n support. Could you make a ticket for this? Thanks.

**Comment by ceecx** [comment] 2020-07-07 05:09
@dessalines 
1. Your solution is not bad either.
2. #914 
3. I think it should be fully visible during editing, and the ideal solution would be to add delete or edit buttons after the URLs.
4. Google Chrome 83.0.4103.116
5. #915

**Comment by dessalines** [comment] 2020-07-07 13:39
Thx for making these, the categories one especially is very needed.

**Comment by ceecx** [comment] 2020-07-07 13:44
> Thx for making these, the categories one especially is very needed.

I am more than happy to ask different questions to discuss with you to make Lemmy better. Thank you for your work. :)

**Comment by ceecx** [comment] 2020-07-10 08:14
@dessalines I have some new details to suggest that I should continue to post here or reopen an Issues? 
I have updated this Issues.

**Comment by dessalines** [comment] 2020-07-10 12:42
Re-open new issues if you would, and make sure its one feature per issue.

**Closed** 2020-08-11 20:04 UTC
Labels: enhancement
