### ISSUE TITLE
Mastodon cannot follow Lemmy commmunity if a user has the same name as the community

### ISSUE THREAD

**Issue by sgornick** [LemmyNet/lemmy#1922] opened 2021-11-19 03:45 UTC
For a community in which there is also a user with the same name:

- https://lemmy.ml/u/bitcoin works (well, shows hourglass / waiting approval)
- https://lemmy.ml/c/bitcoin does not work, does not show any result to the search.

Same for !crypto, ...  https://lemmy.ml/c/crypto, does not work, but I can follow https://lemmy.ml/u/crypto

Yet other groups, where there is no user with the same name as the group, I was able to follow.  no problem

The Mastodon instance I was trying this from runs Mastodon v3.4.3.

**Comment by sgornick** [comment] 2021-11-19 03:48
This would cause a problem, I suspect, if a person were to register a name for an existing group (e.g., asklemmy) and then Mastodon users trying to follow that community would not be able to.

**Comment by Nutomic** [comment] 2021-11-19 12:56
This is a Mastodon problem.

**Comment by VictorVenema** [comment] 2021-11-19 22:14
> This is a Mastodon problem.

Mastodon also does not feel responsible. https://github.com/mastodon/mastodon/issues/17008

Would be great if you guys would talk to each other directly.

Is it possible in Lemmy to change the name of a community? I would be happy to change my community from OpenScience to OpenScienceFeed. 

Even if they are two different name spaces, it may be an idea to not allow names of communities and accounts to be the same in future.

**Comment by Nutomic** [comment] 2021-11-22 14:37
@VictorVenema I replied in the linked issue. As the comment by Claire mentions, this problem is caused by unfortunate UX and database design in Mastodon, which means it is their responsibility. Note that user/community with identical names work just fine in Pleroma.

Renaming a community is not possible, you would have to create a new one. But on an instance with open signup, someone could create a user account with the same name at any time. Maybe it would be fine with Mastodon if the community is known first, i dont know.

Disallowing identical names for users and communities seems like a severe limitation. For example, some people like to create a community as a personal blog. All of that works perfectly fine between Lemmy and Pleroma at least, so the problem in Mastodon is not enough of a reason for such a change. At most it could be an admin option.

**Comment by VictorVenema** [comment] 2021-11-22 23:11
In Mastodon it is possible to start a new account and move your followers and followed to that new account.* Is something like that already implemented in Lemmy? Then I would be happy to start a new account (somewhere else where they are willing to avoid clashes between groups and users).

_* I feel this is important functionality, 1) it sets the Fediverse apart that we do not lock people in, but that they are free to move, like changing your mobile phone provider and 2) because it helps with servers no longer being maintained, which is unavoidable in a distributed system. 3) It helps keep the system distributed when people who will mostly start at the main site can move to another server once the know their way around._

**Comment by Nutomic** [comment] 2021-11-23 12:06
No, that is not currently possible in Lemmy.

**Comment by whatSocks** [comment] 2021-12-04 17:15
> Disallowing identical names for users and communities seems like a severe limitation.

How about displaying a warning? If someone doesn't care about mastodon, they can ignore it.

**Comment by whatSocks** [comment] 2021-12-04 20:10
> https://lemmy.ml/u/bitcoin works (well, shows hourglass / waiting approval)

did it actually work? the hourglass thing is confusing. Also trying to follow a community and made sure there is no user with the same name.

**Comment by VictorVenema** [comment] 2021-12-04 20:26
> How about displaying a warning? If someone doesn't care about mastodon, they can ignore it.

Who does the warning go to? The new person making an account or the community that is kicked off of Mastodon? Or would you only let the same person make an account and community by the same name?

I really do not understand why @Nutomic thinks not being able to make a community and an account with the same name is a "severe limitation". I would call it a hardly perceptible limitation. 

In addition, it is an improvement in clarity: My blog is called Variable Variability and once someone write a comment about "VV" and I had no clue whether they were talking about the blog or me, while that made a difference. So allowing such confusing double names forces people to always formally use the handle @ or ! lest they write something that is unclear.

Why not simply call yourself, e.g., Victor and the community VictorHome, VictorCommunity, VictorFeed, VictorBlog, VictorNews or whatever? Much clearer when the write about Victor and do not specify @victor or !victor. And it is interoperable, which is supposed to be one of the main selling points of the Fediverse that is flushed down the drain here.

**Comment by victor** [comment] 2021-12-05 01:17
Funny that you are discussing a problem about naming clashes and decide to @-mention me so carelessly

**Comment by Nutomic** [comment] 2021-12-05 16:51
> I really do not understand why @Nutomic thinks not being able to make a community and an account with the same name is a "severe limitation". I would call it a hardly perceptible limitation.

Lemmy treats users and communities completely separately, and they are stored in different database tables. So enforcing unique names between both of them doesnt really make sense as far as Lemmy is concerned. Adding such a limitation just because a single project cant handle it properly doesnt make much sense either in my opinion. Note that this problem doesnt happen with Pleroma, so there is no clear reason why it should be fixed in Lemmy instead of Mastodon.

**Comment by asonix** [comment] 2021-12-05 23:41
activitypub makes no guarantees about the uniqueness of `name` or `preferredUsername` fields, only that `id` uniquely identifies an object

**Comment by Nutomic** [comment] 2022-01-20 23:05
This is improved with https://github.com/LemmyNet/lemmy/pull/2047. If there are a community and user with the same name, Mastodon now prefers the community (but the user doesnt work).

**Comment by VictorVenema** [comment] 2022-01-31 22:44
Thanks for the great news. That solves my personal problem. I first thought the problem was still there because the avatar (likely cached) was of the user OpenScience, but the link went to the community OpenScience.

**Comment by Nutomic** [comment] 2022-06-27 10:42
It would be possible to add a workaround for this, namely a config option `federation.mastodon_compat` (disabled by default). If enabled, it would prevent creation of a community, if a user with the same name already exists. This would solve the problem of an existing user being effectively hidden by a new community. If there is enough interest, I can implement this and instance admins could decide to activate the option (or not).

Another option for instance admins is to enable "Only Admins can create Communities".

**Comment by VictorVenema** [comment] 2022-06-27 13:50
>  If enabled, it would prevent creation of a community, if a user with the same name already exists.

Maybe this was intended, but I would implement it both ways and also prevent the creation of a user if a community with the same name already exist to avoid that this user would be hidden on Mastodon. At sign up the user may not know the community yet or realized the consequences of the chosen user name.

**Comment by silverpill** [comment] 2022-12-02 21:28
@Nutomic 

>Additionally, I dont think the Activitypub spec prohibits having multiple actors with the same name on an instance (tell me if I am wrong). So if a project like Mastodon has additional requirements, beyond the requirements of the spec and of similar projects like Pleroma, its not our responsibility to work around that.

Webfinger is not a part of ActivityPub spec. The `acct:` URI, in particular, is defined in [RFC7565](https://datatracker.ietf.org/doc/html/rfc7565):

>The "Internet resource" identified by an 'acct' URI is a user's account hosted at a service provider, where the service provider is typically associated with a DNS domain name.  Thus, a particular 'acct' URI is formed by setting the "user" portion to the user's account name at the service provider and by setting the "host" portion to the DNS domain name of the service provider.

But in Lemmy acct URI does not identify an account, because it may point to both user and group at the same time.

**Closed** 2023-06-30 10:24 UTC
Labels: wontfix

**Comment by Die4Ever** [comment] 2026-08-30 21:22
> > If enabled, it would prevent creation of a community, if a user with the same name already exists.
> 
> Maybe this was intended, but I would implement it both ways and also prevent the creation of a user if a community with the same name already exist to avoid that this user would be hidden on Mastodon. At sign up the user may not know the community yet or realized the consequences of the chosen user name.

Yea I could imagine a user maliciously creating accounts with the same names as communities. Someone could create a bunch of these user accounts just to be annoying. I don't think users should be able to use the same name as an existing community.
