### ISSUE TITLE
Configuration in source and documentation does not match

### ISSUE THREAD

**Issue by Phlogi** [LemmyNet/lemmy#2405] opened 2022-08-16 05:54 UTC
### Issue Summary

Which one is correct?

1. https://join-lemmy.org/docs/en/administration/configuration.html
2. https://github.com/LemmyNet/lemmy/blob/release/v0.16/config/defaults.hjson

For example the entries for pictrs are different.

**Comment by Nutomic** [comment] 2022-08-24 11:24
The second link is correct for Lemmy 0.16.x. The config in the documentation is from development branch, which will be used from Lemmy 0.17.0. Sorry for the confusion.

**Comment by Phlogi** [comment] 2022-08-24 13:52
No problem, i learned about the stable mainline branching model you're using. But that could be more present here on the readme maybe. 

On a side note: It's not clear what the minimal needed config is so that lemmy works properly. Could you state that in the config or define a minimal default config?

**Comment by Nutomic** [comment] 2022-08-24 15:23
The only required field is the hostname. 

If there are things you would like to improve in the documentation, I would really appreciate if you could do that yourself. For me as developer its really hard to know what is unclear for normal users, or how to explain things in a way that they can understand. The files are [here](https://github.com/LemmyNet/lemmy-docs/tree/main/src/en).

**Comment by dessalines** [comment] 2022-08-29 18:51
The [lemmy-ansible](https://github.com/LemmyNet/lemmy-ansible) repo (the preferred install method) also has a minimal lemmy.hjson template, that it instructs you to copy.

**Comment by dessalines** [comment] 2022-08-29 18:52
Dupe of https://github.com/LemmyNet/lemmy-docs/issues/146

**Closed by dessalines** 2022-08-29 18:52 UTC
Labels: bug
