### ISSUE TITLE
Media proxy to combat censorship

### ISSUE THREAD

**Issue by ashrude** [LemmyNet/lemmy#3474] opened 2023-07-03 22:54 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

blahaj.zone is now blocked in the UAE. However, they can access posts by using other instances, but they can’t access any media attached to those posts, as all media is only linked to, and the client has to retrieve the content from the other server.

### Describe the solution you'd like.

An optional http media proxy that admins can enable, or maybe it’s a separate service that clients can request images or media from other instances through.

it could also cache popular files.

Each client would first try accessing the content from the provided link directly, then use the proxy if necessary.

### Describe alternatives you've considered.

You could also just download all media to the local pictrs instance, and replace the client-side image url. But that may be a bit heavier. However it would be nice to have that option as well, to lessen the load on some servers.

**Comment by lionirdeadman** [comment] 2023-07-22 21:47
Duplicate of https://github.com/LemmyNet/lemmy/issues/2947

**Closed by lionirdeadman** 2023-07-22 21:47 UTC
Labels: type: duplicate, enhancement
