### ISSUE TITLE
DB insert fighting for the Site, Person, and Community tables.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2865] opened 2023-05-17 16:19 UTC
The lemmy back-end periodically fetches sites, persons, and communities from federated instances, to pick up new changes / updates to their fields. It should theoretically only do this once per day.

Unfortunately, the federation workers seem to be duplicating that work, and refetching the same data concurrently, causing insert fighting, and a permanent state of database lock.

Potential solutions:

- Check for why these duplicated inserts are happening, and fix that.
- Remove the `on_conflict_upsert` for those tables, and make sure that does a read-check on the `last_updated` column before any upsert.
- Make these inserts are queued, and not run on the same DB connection pool as everything else.

**Comment by Nutomic** [comment] 2023-05-18 11:01
I looked into this but couldnt find anything in the logs that would indicate a high number of inserts. I used `SELECT query FROM pg_stat_activity;` on lemmy.ml and only saw lots of select queries. 

However I did notice a different problem. When fetching a remote community, it also fetches the outbox with up to 20 posts. For each post link, `fetch_site_data()` is called which makes 2 HTTP requests. Each request is retried up to 3 times if it fails (so 4 times including initial attempt). So fetching a community outbox can result in 80 HTTP requests in the worst case, all within a few seconds. You can partially reproduce this by creating a post with an invalid url like `http://test.com`. In this case Im seeing 4 requests from  `fetch_site_metadata()` and 3 from `is_image_content_type()`. 

Going through the git history, it looks like reqwest retry functionality was [originally added for federation](https://github.com/LemmyNet/lemmy/commit/a074564458b8a108b77d98e5e8ce24168656763a#diff-7debcc28b1a8f961d744b3bffcc700c9288708217d60756c7c96bb9eed79ef8cR12) (sending out activities). But there is now a separate retry functionality for activity sending, so doing it via reqwest is not necessary anymore.

**Comment by Nutomic** [comment] 2023-05-25 10:17
Closing in favor of https://github.com/LemmyNet/lemmy/issues/2877, the slow query logs dont list any inserts or updates.

**Closed by Nutomic** 2023-05-25 10:17 UTC
Labels: bug, database
