### ISSUE TITLE
Can't follow Lemmy from GoToSocial

### ISSUE THREAD

**Issue by kvibber** [LemmyNet/lemmy#3029] opened 2023-06-12 00:17 UTC
I've mentioned this previously at https://socialhub.activitypub.rocks/t/help-improving-federation-between-lemmy-and-other-projects/2308/38 but never got around to opening an issue for the actual project!

GoToSocial is able to retrieve a Lemmy profile (community or user), an individual comment, or the top level of a post, but can't follow a Lemmy account or otherwise interact with it. GTS requires signed fetches, similar to Mastodon running in secure mode. As I understand it, Lemmy doesn't implement this yet, which is likely the main reason they can't federate interactions.

**Comment by Nutomic** [comment] 2023-06-12 12:05
Dupe of https://github.com/LemmyNet/lemmy/issues/868

**Closed by Nutomic** 2023-06-12 12:05 UTC
Labels: bug
