### ISSUE TITLE
Option to prevent users from deleting all of their posts

### ISSUE THREAD

**Issue by liratin** [LemmyNet/lemmy#1624] opened 2021-05-30 09:29 UTC
For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Is your proposal related to a problem?

When going through old threads on reddit and other forums, you see mass deleted posts which make other posts replying to that post unreadable.

### Describe the solution you'd like

Option to delete the account WITHOUT deleting posts for the sake of readability. 

### Describe alternatives you've considered

The only alternative is the one that exists, allowing users to delete all posts when deleting their account.

**Comment by Nutomic** [comment] 2021-05-31 14:02
Duplicate of #1617.

**Closed by Nutomic** 2021-05-31 14:02 UTC
Labels: enhancement
