### ISSUE TITLE
Twitter Cards

### ISSUE THREAD

**Issue by Nicedude-git** [LemmyNet/lemmy#648] opened 2020-04-21 06:13 UTC
Hello.

It would be nice to be able to post a link to a lemmy post and get a preview on the  twitter post showing featured image if available and extract of text (just like Discourse).

More descriptive urls would be nice too.

**Comment by dessalines** [comment] 2020-04-21 12:34
This is a single-page web app, where most of the data is loaded after the initial page load, making the SEO stuff not easy. Dupe of #226

**Closed by dessalines** 2020-04-21 12:34 UTC
