### ISSUE TITLE
Mastodon can not follow lemmy cummunities on my instance, always shows "requesting"

### ISSUE THREAD

**Issue by pullopen** [LemmyNet/lemmy#2024] opened 2022-01-08 11:13 UTC
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Issue Summary

A summary of the bug.

### Steps to Reproduce

1. Try to follow `!fediversefutures@lemmy.ml` and`!announcements@lemmy.ml` from mastodon
2. The previous one succeed immediately, and the latter shows "requesting" and succeed automatically after 10 minutes.
3. Try to follow the community or users on my own lemmy instance (v0.14.3), also shows "requesting" and not change after an hour or so.

### Technical details

* Please post your log: `sudo docker-compose logs > lemmy_log.out`. 
Not sure which part is relevant.
* What OS are you trying to install lemmy on?  Debian 10 & docker

**Comment by Nutomic** [comment] 2022-01-08 12:33
Duplicate of https://github.com/LemmyNet/lemmy/issues/1984 (even though it mentions Pleroma, its the same problem). If you run your own Mastodon instance, maybe you can find something useful in the logs. Otherwise, this probably needs debugging from a Mastodon/Pleroma dev.

**Closed by Nutomic** 2022-01-08 12:33 UTC
Labels: bug
