### ISSUE TITLE
Feature proposal: user-customizable slur filter

### ISSUE THREAD

**Issue by private-hell** [LemmyNet/lemmy#1481] opened 2021-03-04 18:47 UTC
### Is your proposal related to a problem?

Some marginalized people have reclaimed certain slurs while others in the same demographic(s) have not. The current slur filter does not allow slurs in any context, nor does it enable users to decide which slurs they are comfortable or uncomfortable seeing.

### Describe the solution you'd like

A feature where each user can decide what slurs they're uncomfortable seeing and filter out posts and comments that contain those slurs. 

### Describe alternatives you've considered

Allowing the mods of each community to decide what slurs are acceptable in their community is another possible solution. However, slur reclamation is often controversial within marginalized groups. It may be difficult for communities of marginalized people to agree on what words are acceptable.

### Additional context

Lemmy's slur filter is currently made only for American English, which makes it difficult to account for words that are slurs in some languages but not others.

**Comment by dessalines** [comment] 2021-05-13 14:22
Dupe of #1464

**Closed by dessalines** 2021-05-13 14:22 UTC
Labels: duplicate, enhancement, moderation
