### ISSUE TITLE
New sorting option: top 3 hours

### ISSUE THREAD

**Issue by willhansen** [LemmyNet/lemmy#3457] opened 2023-07-02 19:21 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

There's a significant gap between the shortest two sorting options: 1 hour and 6 hours.  3 hours would fill it

| Existing sorting option  | Multiplicative difference |
| ------------- | ------------- |
|  TopHour |
| | x6 (Big!)
|  TopSixHour
| | x2
|  TopTwelveHour
| | x2 
|  TopDay |  |  
| | x7 (Big!)
|  TopWeek
| | x~4
|  TopMonth
| | x3
|  TopThreeMonths
| | x2
|  TopSixMonths
| | x1.5
|  TopNineMonths |
| | x1.33
|  TopYear

### Describe the solution you'd like.

An additional TopThreeHours sorting option.

| Sorting option  | Multiplicative difference |
| ------------- | ------------- |
|  TopHour |
| | x3
|  TopThreeHour |
| | x2
|  TopSixHour

I suppose the table supports a TopThreeDays sorting option as well.

| Sorting option  | Multiplicative difference |
| ------------- | ------------- |
|  TopDay |  |  
| | x3
|  TopThreeDay |  |  
| | x2.33
|  TopWeek

### Describe alternatives you've considered.

Top 2 hours and top 4 hours

| Sorting option  | Multiplicative difference |
| ------------- | ------------- |
|  TopHour |
| | x2)
|  TopTwoHour |
| | x2
|  TopFourHour |
| | x1.5
|  TopSixHour

The 4 to 6 step is a bit small

| Sorting option  | Multiplicative difference |
| ------------- | ------------- |
|  TopHour |
| | x2
|  TopTwoHour |
| | x3
|  TopSixHour

A TopTwoHour option has the same step gaps as with TopThreeHour, just switched around.  I like TopThreeHour because it falls on the arithmetic mean of 1 and 6, and so looks more "in the middle", but this would be probably just as good.

### Additional context

Looks like the month gaps were filled in recently: https://github.com/LemmyNet/lemmy/issues/3217

**Comment by josephrocca** [comment] 2023-07-03 00:02
Great work putting those tables together! I was actually going to ask for top 3 days (I've always wished reddit had this), which would fill the other big multiplier in your table.

The reason is that my "natural cadence" for checking a bunch of subreddits was "every few days". I'd rarely check daily, and I'd rarely go a full week without checking. Not sure if others also had this issue with reddit.

**Comment by M4rtineski** [comment] 2023-07-04 19:36
I love the idea! Top 3 hours and top 3 days 1000% should be there. Also it's nice to see how my idea for top 3, 6 and 9 months got implemented.

@josephrocca "The reason is that my "natural cadence" for checking a bunch of subreddits was "every few days". I'd rarely check daily, and I'd rarely go a full week without checking. Not sure if others also had this issue with reddit."

Yes, I had the exact same problems with reddit, I wasn't checking things daily but every 2-3 days and having to look at posts that you have seen from earlier this week that you have already seen is annoying.

**Comment by moosetwin0** [comment] 2023-09-01 11:44
You could also do something like "Top ____ Hours(/Days)" and have the user give a number of hours.

**Comment by willhansen** [comment] 2023-09-01 13:09
User choice paralysis and ease of database indexing lean against that, but I'm not 100% on either of those.

**Comment by 8ullyMaguire** [comment] 2023-09-06 14:55
While we are at it, do people use `TopNineMonths`? Can't we go from 6 months to a year?

**Comment by lv01-GreyCat** [comment] 2024-07-25 13:58
I would really like a top 3 days as well, if you haven't checked lemmy over the week-end or the beginning/end of the work week, it would allow you to catch up on stuff you have missed over a few days.

**Comment by dessalines** [comment] 2024-07-28 15:52
Dupe of #4340

**Closed by dessalines** 2024-07-28 15:52 UTC
Labels: enhancement, area: sorting
