### ISSUE TITLE
Did you ever add a privacy policy?

### ISSUE THREAD

**Issue by nathgit** [LemmyNet/lemmy#1623] opened 2021-05-29 11:57 UTC
[privacypolicies.com](https://www.privacypolicies.com/blog/privacy-policies-legally-required/) clearly states that any site collecting personal information MUST have a privacy policy. There are tools for creating one. Privacy issues is one problem people have with reddit.

**Comment by dessalines** [comment] 2021-05-29 13:26
Dupe of https://github.com/LemmyNet/lemmy/issues/721

**Closed by dessalines** 2021-05-29 13:26 UTC
Labels: question
