### ISSUE TITLE
Custom privacy policies / terms for each instance

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1655] opened 2021-07-09 15:53 UTC
Masto has a custom "terms" page for each instance: https://mastodon.social/terms

We should probably fill in a "default" policy for whatever we come up with for #721 , or at least link to that.

**Comment by Nutomic** [comment] 2022-03-15 15:17
Duplicate of https://github.com/LemmyNet/lemmy/issues/721. This issue had a better title so i renamed the other one.

**Closed by Nutomic** 2022-03-15 15:17 UTC
Labels: enhancement, database, api
