### ISSUE TITLE
Searching for Peertube-Channels does not work

### ISSUE THREAD

**Issue by xundeenergie** [LemmyNet/lemmy#2699] opened 2023-02-03 15:42 UTC
Found a bug? Please fill out the sections below. 👍

For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Issue Summary

Searching for peertube-channels does not work any more on lemmy 0.17.0

Log on searching for "!phalio_tech@diode.zone" (with exclamationmark for community)
```
lemmy_1     | 2023-02-03T15:34:59.799502Z ERROR lemmy_server::api_routes_websocket: Error during message handling couldnt_find_object: Failed to resolve actor for phalio_tech@diode.zone
lemmy_1     |    0: lemmy_apub::fetcher::search::search_query_to_object_id
lemmy_1     |              at crates/apub/src/fetcher/search.rs:17
lemmy_1     |    1: lemmy_apub::api::resolve_object::perform
lemmy_1     |            with self=ResolveObject { q: "!phalio_tech@diode.zone", auth: Some(Sensitive) }
lemmy_1     |              at crates/apub/src/api/resolve_object.rs:21
```
Log on searching for "phalio_tech@diode.zone" (the raw username)
```
lemmy_1     | 2023-02-03T15:37:09.056461Z ERROR lemmy_server::api_routes_websocket: Error during message handling couldnt_find_object: invalid query
lemmy_1     |    0: lemmy_apub::fetcher::search::search_query_to_object_id
lemmy_1     |              at crates/apub/src/fetcher/search.rs:17
lemmy_1     |    1: lemmy_apub::api::resolve_object::perform
lemmy_1     |            with self=ResolveObject { q: "phalio_tech@diode.zone", auth: Some(Sensitive) }
lemmy_1     |              at crates/apub/src/api/resolve_object.rs:21
```

Log on searching for "@phalio_tech@diode.zone" (with @ for user-search)
```
lemmy_1     | 2023-02-03T15:37:15.074870Z ERROR lemmy_server::api_routes_websocket: Error during message handling couldnt_find_object: Failed to resolve actor for phalio_tech@diode.zone
lemmy_1     |    0: lemmy_apub::fetcher::search::search_query_to_object_id
lemmy_1     |              at crates/apub/src/fetcher/search.rs:17
lemmy_1     |    1: lemmy_apub::api::resolve_object::perform
lemmy_1     |            with self=ResolveObject { q: "@phalio_tech@diode.zone", auth: Some(Sensitive) }
lemmy_1     |              at crates/apub/src/api/resolve_object.rs:21
```

**Comment by Nutomic** [comment] 2023-02-03 16:27
Duplicate of #2689

**Closed by Nutomic** 2023-02-03 16:27 UTC
Labels: bug
