### ISSUE TITLE
[Bug]: `panic` with lemmy.ml data on `0.19.6`: `apub person not found.`

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#5165] opened 2024-11-04 23:31 UTC
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I loaded the lemmy.ml database into my local DB, to make sure the `0.19.6` migrations are okay, and I'm getting this error with lemmy_federate, which panics with an empty stacktrace, then restarts lemmy:

```
lemmy-1  | 2024-11-04T23:12:49.705631Z  WARN lemmy_federate::worker: sending https://lemmy.ml/activities/delete/813f47fb-053a-4d7b-9d76-760901a06358 errored internally, skipping activity: failed getting actor instance (was it marked deleted / removed?)
lemmy-1  |     err getting actor Person https://lemmy.ml/u/Quail4789: apub person not found
lemmy-1 | Stack backtrace: ....
```

### Steps to Reproduce

See above

### Technical Details

NA

### Version

release/v0.19

**Comment by Nutomic** [comment] 2024-11-05 08:56
You need to remove [this line](https://github.com/LemmyNet/lemmy/blob/main/Cargo.toml#L37) to get a stack trace, and possibly set `RUST_BACKTRACE=1`.

**Comment by dessalines** [comment] 2024-11-05 14:52
K, starting that now.

**Comment by Nutomic** [comment] 2024-11-05 15:09
Anyway there have been no changes in that code, so its likely caused by your local setup.

**Comment by dessalines** [comment] 2024-11-05 15:15
Most likely, and now the error seems to have gone away. 

Its [this line](https://github.com/LemmyNet/lemmy/blob/main/crates/federate/src/util.rs#L168), so it has to do with caching missing / deleted actors.

I spose this isn't a blocker for the release then, but its something we should keep open, because it does cause a hard crash.

cc @phiresky

**Comment by Nutomic** [comment] 2024-11-05 15:23
That line has been unchanged since [0.19.0](https://github.com/LemmyNet/lemmy/blob/0.19.0/crates/federate/src/util.rs#L142) and we havent heard about any problems in production. It also shouldnt cause a crash but simply return an error during activity sending. Your log also shows a warning, not a crash.

**Comment by Nutomic** [comment] 2024-11-12 09:29
Closing this as it doesnt happen in production.

**Closed by Nutomic** 2024-11-12 09:29 UTC
Labels: bug
