### ISSUE TITLE
Add a "List" or "Multicommunity" feed

### ISSUE THREAD

**Issue by JackFromWisconsin** [LemmyNet/lemmy#2647] opened 2023-01-09 03:58 UTC
Hello,
I would like a feature to create "lists" of communities to throw into a single feed. Basically, a way to view !science, !fuckcars, and !socialism (for example) in a feed. 

I am torn on whether this should be private and defined per user, or alternatively to allow multicommunities to be public. Private seems easier and less work for moderators so that's probably best. 

Kind of a low-priority but would greatly enhance my Lemmy experience.

**Comment by dessalines** [comment] 2023-01-09 23:11
Dupe of #818

**Closed by dessalines** 2023-01-09 23:11 UTC
Labels: enhancement
