### ISSUE TITLE
Deleted posts are accessible

### ISSUE THREAD

**Issue by Porrumentzio** [LemmyNet/lemmy#1313] opened 2020-12-08 11:26 UTC
### Issue Summary

When deleting a post, it's still accessible with its link.
In fact, they are not deleted, but hidden from the user interface. I know this is a database issue, but being able to view it it's not expected. And I think this is really great problem, because in that post there could be painful content and it does not get deleted. 

### Steps to Reproduce

1. Delete a post, for example `/post/36`
2. Even without logged in, go to that URL (`https://instan.ce/post/36`) and you'll see the post.

**Comment by Nutomic** [comment] 2020-12-08 12:54
Are you only talking about posts deleted by the creator, or also about those removed by mods/admins? In the second case, hiding the post completely would make the mod log kind of useless. Maybe a compromise would be that only logged in users could see removed posts. Or have a separate action "remove + wipe from database" for admins/mods.

**Comment by Porrumentzio** [comment] 2020-12-08 14:13
I tested it removing the post as a user.
As for moderation, yes, they should be visible somehow. But not those deleted by users

**Comment by dessalines** [comment] 2020-12-08 15:44
This is a dupe of #904 . Deleted and even removed posts should still be accessible by link, otherwise the mod log and concerns around that are pointless. For truly heinous content tho, there needs to be a way to purge it from the database, which would make it inaccessible, which is what #904 is about.

IMO posts deleted by users should still be accessible, it after all might have comments by others (IE content not created by the post creator) that are useful.

**Comment by StaticallyTypedRice** [comment] 2020-12-22 08:45
> IMO posts deleted by users should still be accessible, it after all might have comments by others (IE content not created by the post creator) that are useful.

I think this is a reasonable way of doing it as long as it's made clear to the user deleting their own post, and there is a way to permanently delete it (you can just edit it to nonsense, like the word "deleted" or something)

**Comment by boehs** [comment] 2021-10-05 19:57
This has been implemented

**Comment by dessalines** [comment] 2021-10-06 20:07
#1680

**Closed by dessalines** 2021-10-06 20:07 UTC
Labels: bug, moderation
