### ISSUE TITLE
Sync modlogs between instances

### ISSUE THREAD

**Issue by StaticallyTypedRice** [LemmyNet/lemmy#1644] opened 2021-07-01 07:27 UTC
I think there should be a way at the very least for admins to view a log of moderation actions taken by other instances they federate with. For example, if instances A and B are federated, but instance A has a rule breaking post that is removed by instance A's own mods, there should be a way for that to show up on instance B's modlog.

**Comment by Nutomic** [comment] 2021-07-01 13:56
Duplicate of #1489.

**Closed by Nutomic** 2021-07-01 13:56 UTC
Labels: enhancement
