### ISSUE TITLE
Add Mastodon like per user content filters and content warnings

### ISSUE THREAD

**Issue by pixiekat** [LemmyNet/lemmy#4898] opened 2024-07-14 12:29 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

There are certain topics that I either want hidden behind a click or removed all together for mental health sake. I can do this on Mastodon with filters but I don't see any way to do this on Lemmy. 

### Describe the solution you'd like.

Add an option to your profile where you can add one or many words to filter and an option to either hide it completely or lock it behind a click to view it. It should have an expiration date or be allowed to last forever. You would also have the option to enter content warnings when making a post (ie, "politics", etc) which would then hide the post content behind a click for the user who is viewing lemmy. 

### Describe alternatives you've considered.

It works great in Mastodon but I have not seen a similar option in Lemmy. The only closest alternative would be using the spoiler tag but that's not a lasting solution.

**Comment by dessalines** [comment] 2024-07-15 18:35
Filtering posts based on terms seems worthwhile, as a bunch of front-ends seem to be hacking that in. That's a dupe of #3710 

As far as content warnings for text, the spoiler tag should be used there, as you can put any reason in there. For posts, there's already the NSFW filter.

**Closed by dessalines** 2024-07-15 18:35 UTC
Labels: enhancement
