### ISSUE TITLE
Add option to add a child community

### ISSUE THREAD

**Issue by volanar** [LemmyNet/lemmy#1639] opened 2021-06-24 11:35 UTC
If in a classic forum we can assign a parent category, then in lemmy you can create a community without nested categories. This is acceptable for news resources, but inconvenient for technical and other resources for structuring information.

It would be great to be able to create child categories for users in their community with at least one level of nesting (communyty/sub-community).

In this way, you can structure your community by categories for the convenience of users.
You can also seriously compete with Discourse and other forums.

**Comment by dessalines** [comment] 2021-06-24 18:57
I'm kinda against creating trees of communities bc it could get incredibly complex... its much easier if each community stands on its own. At least on reddit, community linking is done via sidebars.

As far as categorizing, I think #317 is a much better way to do that besides creating more communities.

**Comment by volanar** [comment] 2021-06-25 21:09
I don't think that any forum is incredibly complex because of the category tree. On the contrary, it is very convenient. In Reddit, links to communities are made through sidebars because users do not have the opportunity to add a subcategory. Therefore, instead of creating one community, they create dozens of ssociety. I consider this a disadvantage of Reddit.
As for https://github.com/LemmyNet/lemmy/issues/317, then this is a good idea, only tags should be defined within a specific community.

**Comment by dessalines** [comment] 2021-06-26 01:00
Would you automatically be subscribed to child communities? What if the user doesn't want that? 

How would you find these child communities / where would they be displayed?

**Comment by remram44** [comment] 2021-06-29 16:22
An alternative might be tags/categories in a single community. Reddit has this in the form of "flairs", which can be searched on (e.g. [/r/AskReddit flair:Serious+Replies+Only](https://old.reddit.com/r/AskReddit/search?sort=new&restrict_sr=on&q=flair%3ASerious%2BReplies%2BOnly)). This might be easier.

Dealing with hierarchies is always problematic (people who use the feature are likely to find one community actually has two parents, or some top-level mods don't need access to all children, etc). Linking to other communities in the sidebar seems easy enough.

**Comment by weex** [comment] 2021-07-03 20:52
> inconvenient for technical and other resources for structuring information

Wikis are much better for this.

**Comment by volanar** [comment] 2021-07-05 01:55
> I'm kinda against creating trees of communities bc it could get incredibly complex... its much easier if each community stands on its own. At least on reddit, community linking is done via sidebars.
> 
> As far as categorizing, I think #317 is a much better way to do that besides creating more communities.

I named it incorrectly, not child communities, but sections within the community. You can improve the user experience if posts within the community are sorted by sections.
The logic of creating sections looks like this:
Create Post - "Community" - Select a community. When you click on the selected community, a window opens
   /
  Category1
  Category2
  Create Category

For example, I want to create a community about pets. I create such a community and create sections cats, dogs, ponies, etc. I don't need to create many communities by pet names and display them in the sidebars, I create one community. Users can go to the section about cats and read only posts about cats. Let's say they don't want to read posts about dogs. Globally, the script logic does not change. But users have the ability to read and write posts in sections. Reddit can't do this.

**Comment by dessalines** [comment] 2021-07-05 14:15
That would make this a dupe of #317

**Closed by dessalines** 2021-07-05 14:15 UTC
Labels: duplicate
