### ISSUE TITLE
Post to self (u/username) and ability to follow other users as well

### ISSUE THREAD

**Issue by je-vv** [LemmyNet/lemmy#1254] opened 2020-11-05 01:49 UTC
On reddit, besides having communities (r/<community>), there are also users (u/<username>), and users are allowed to post not just to communities, but also to themselves.  This is pretty useful in two fronts, oneself wanting to keep stuff which is useful for him/her, and to have it available for future reference, and also if enabling following users, then it might be interesting to watch content posted by followed users.

Associated, but not the same, the ability to search for posts one has made, whether to oneself or communities is important.  I believe this is pretty hard on reddit...

Thanks !

**Comment by Nutomic** [comment] 2020-11-05 12:23
This is a duplicate of #752. About the search, best leave a comment in #765.

**Closed** 2020-11-05 12:29 UTC
Labels: enhancement

**Comment by je-vv** [comment] 2020-11-05 20:23
I'm not sure the user following feature covers the ability to post to oneself, rather than any community.  I left a comment on #752 eny ways, but it's hard to know but just looking if it covers the same by just looking at it.  I also left a comment on #765 as you suggested.
