### ISSUE TITLE
Either photo upload or saving an URL

### ISSUE THREAD

**Issue by Bluetoothbrot** [LemmyNet/lemmy#2490] opened 2022-10-11 12:35 UTC
### One URL or photo

Lemmy enables you to save a link (that also loads an image from the site if available) or upload a photo to the respective lemmy server

### Several photos and an URL
It would be amazing if its possible to save an URL to a thread and upload one or several images!:)

**Comment by dessalines** [comment] 2022-10-13 00:22
You can currently do this by inserting as many images as you want into the post body.

I'd like to have some kind of "collection of photos" support, but not sure how to do that.

Dupe of #981

**Closed by dessalines** 2022-10-13 00:22 UTC
Labels: enhancement
