### ISSUE TITLE
Hide pinned posts

### ISSUE THREAD

**Issue by Undertakerrip** [LemmyNet/lemmy#3157] opened 2023-06-16 20:32 UTC
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

Currently pinned posts stay at the top even if I have seen them multiple times which is a bit annoying.
I only can hide already read posts in general (in the settings) but I don't want to hide all of them. I use the sort type "new" but obviously pinned posts stay at top. I want to see the latest posts at the top and if I reload I still want to see them for example to check them again for updates (hiding already seen posts would affect the user experience).

It is common usage being able to hide pinned posts

### Describe the solution you'd like.

Please add an option "Hide post" to allow users to hide specific posts if desired.

An alternative could be disabling pinned posts in user settings, so a pinned posts will be treated like any other for this user. But I guess this is a bit invasive

### Describe alternatives you've considered.

The only way to hide pinned posts is to hide all read posts but this comes along with other disadvantages.

**Comment by dessalines** [comment] 2023-10-18 21:23
Yep, its a dupe of #1403

**Closed by dessalines** 2023-10-18 21:23 UTC
Labels: enhancement, area: customization
